{
  "discoveryVersion": "v1",
  "baseUrl": "https://analyticsadmin.googleapis.com/",
  "resources": {
    "accounts": {
      "methods": {
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "DELETE",
          "path": "v1alpha/{+name}",
          "id": "analyticsadmin.accounts.delete",
          "flatPath": "v1alpha/accounts/{accountsId}",
          "description": "Marks target Account as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted accounts. However, they can be restored using the Trash Can UI. If the accounts are not restored before the expiration time, the account and all child resources (eg: Properties, GoogleAdsLinks, Streams, UserLinks) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found."
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1alpha/accounts/{accountsId}",
          "httpMethod": "PATCH",
          "id": "analyticsadmin.accounts.patch",
          "description": "Updates an account.",
          "path": "v1alpha/{+name}"
        },
        "getDataSharingSettings": {
          "path": "v1alpha/{+name}",
          "description": "Get data sharing settings on an account. Data sharing settings are singletons.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "flatPath": "v1alpha/accounts/{accountsId}/dataSharingSettings",
          "httpMethod": "GET",
          "id": "analyticsadmin.accounts.getDataSharingSettings"
        },
        "provisionAccountTicket": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1alpha/accounts:provisionAccountTicket",
          "description": "Requests a ticket for creating an account.",
          "id": "analyticsadmin.accounts.provisionAccountTicket",
          "flatPath": "v1alpha/accounts:provisionAccountTicket"
        },
        "get": {
          "id": "analyticsadmin.accounts.get",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "GET",
          "flatPath": "v1alpha/accounts/{accountsId}",
          "path": "v1alpha/{+name}",
          "description": "Lookup for a single Account."
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Returns all accounts accessible by the caller. Note that these accounts might not currently have GA4 properties. Soft-deleted (ie: \"trashed\") accounts are excluded by default. Returns an empty list if no relevant accounts are found.",
          "id": "analyticsadmin.accounts.list",
          "path": "v1alpha/accounts",
          "flatPath": "v1alpha/accounts",
          "httpMethod": "GET"
        }
      },
      "resources": {
        "userLinks": {
          "methods": {
            "delete": {
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "id": "analyticsadmin.accounts.userLinks.delete",
              "path": "v1alpha/{+name}",
              "description": "Deletes a user link on an account or property.",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks/{userLinksId}"
            },
            "audit": {
              "description": "Lists all user links on an account or property, including implicit ones that come from effective permissions granted by groups or organization admin roles. If a returned user link does not have direct permissions, they cannot be removed from the account or property directly with the DeleteUserLink command. They have to be removed from the group/etc that gives them permissions, which is currently only usable/discoverable in the GA or GMP UIs.",
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/userLinks:audit",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "id": "analyticsadmin.accounts.userLinks.audit",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:audit"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "path": "v1alpha/{+parent}/userLinks",
              "id": "analyticsadmin.accounts.userLinks.list",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks",
              "description": "Lists all user links on an account or property.",
              "httpMethod": "GET"
            },
            "batchUpdate": {
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+parent}/userLinks:batchUpdate",
              "description": "Updates information about multiple users' links to an account or property.",
              "id": "analyticsadmin.accounts.userLinks.batchUpdate",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchUpdate"
            },
            "batchCreate": {
              "id": "analyticsadmin.accounts.userLinks.batchCreate",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchCreate",
              "httpMethod": "POST",
              "description": "Creates information about multiple users' links to an account or property. This method is transactional. If any UserLink cannot be created, none of the UserLinks will be created.",
              "path": "v1alpha/{+parent}/userLinks:batchCreate"
            },
            "batchGet": {
              "description": "Gets information about multiple users' links to an account or property.",
              "httpMethod": "GET",
              "id": "analyticsadmin.accounts.userLinks.batchGet",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchGet",
              "path": "v1alpha/{+parent}/userLinks:batchGet"
            },
            "batchDelete": {
              "description": "Deletes information about multiple users' links to an account or property.",
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/userLinks:batchDelete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchDelete",
              "id": "analyticsadmin.accounts.userLinks.batchDelete"
            },
            "create": {
              "description": "Creates a user link on an account or property. If the user with the specified email already has permissions on the account or property, then the user's existing permissions will be unioned with the permissions specified in the new UserLink.",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks",
              "id": "analyticsadmin.accounts.userLinks.create",
              "path": "v1alpha/{+parent}/userLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "httpMethod": "POST"
            },
            "patch": {
              "httpMethod": "PATCH",
              "description": "Updates a user link on an account or property.",
              "id": "analyticsadmin.accounts.userLinks.patch",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks/{userLinksId}"
            },
            "get": {
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.accounts.userLinks.get",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks/{userLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "httpMethod": "GET",
              "description": "Gets information about a user's link to an account or property."
            }
          }
        }
      }
    },
    "properties": {
      "resources": {
        "iosAppDataStreams": {
          "methods": {
            "delete": {
              "flatPath": "v1alpha/properties/{propertiesId}/iosAppDataStreams/{iosAppDataStreamsId}",
              "description": "Deletes an iOS app stream on a property.",
              "path": "v1alpha/{+name}",
              "httpMethod": "DELETE",
              "id": "analyticsadmin.properties.iosAppDataStreams.delete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "create": {
              "flatPath": "v1alpha/properties/{propertiesId}/iosAppDataStreams",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.iosAppDataStreams.create",
              "path": "v1alpha/{+parent}/iosAppDataStreams",
              "description": "Creates an iOS app data stream with the specified location and attributes.",
              "httpMethod": "POST"
            },
            "get": {
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/iosAppDataStreams/{iosAppDataStreamsId}",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.iosAppDataStreams.get",
              "description": "Lookup for a single IosAppDataStream",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "patch": {
              "id": "analyticsadmin.properties.iosAppDataStreams.patch",
              "httpMethod": "PATCH",
              "path": "v1alpha/{+name}",
              "description": "Updates an iOS app stream on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/iosAppDataStreams/{iosAppDataStreamsId}"
            },
            "list": {
              "id": "analyticsadmin.properties.iosAppDataStreams.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/iosAppDataStreams",
              "flatPath": "v1alpha/properties/{propertiesId}/iosAppDataStreams",
              "description": "Returns child iOS app data streams under the specified parent property. iOS app data streams will be excluded if the caller does not have access. Returns an empty list if no relevant iOS app data streams are found."
            }
          }
        },
        "webDataStreams": {
          "methods": {
            "patch": {
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}",
              "id": "analyticsadmin.properties.webDataStreams.patch",
              "path": "v1alpha/{+name}",
              "description": "Updates a web stream on a property.",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "updateEnhancedMeasurementSettings": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}/enhancedMeasurementSettings",
              "path": "v1alpha/{+name}",
              "description": "Updates the singleton enhanced measurement settings for this web stream. Note that the stream must enable enhanced measurement for these settings to take effect.",
              "id": "analyticsadmin.properties.webDataStreams.updateEnhancedMeasurementSettings",
              "httpMethod": "PATCH"
            },
            "getEnhancedMeasurementSettings": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "description": "Returns the singleton enhanced measurement settings for this web stream. Note that the stream must enable enhanced measurement for these settings to take effect.",
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}/enhancedMeasurementSettings",
              "id": "analyticsadmin.properties.webDataStreams.getEnhancedMeasurementSettings",
              "path": "v1alpha/{+name}"
            },
            "get": {
              "id": "analyticsadmin.properties.webDataStreams.get",
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}",
              "httpMethod": "GET",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lookup for a single WebDataStream"
            },
            "list": {
              "path": "v1alpha/{+parent}/webDataStreams",
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Returns child web data streams under the specified parent property. Web data streams will be excluded if the caller does not have access. Returns an empty list if no relevant web data streams are found.",
              "id": "analyticsadmin.properties.webDataStreams.list"
            },
            "create": {
              "path": "v1alpha/{+parent}/webDataStreams",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates a web stream with the specified location and attributes.",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.webDataStreams.create",
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams"
            },
            "getGlobalSiteTag": {
              "httpMethod": "GET",
              "description": "Returns the Site Tag for the specified web stream. Site Tags are immutable singletons.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.webDataStreams.getGlobalSiteTag",
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}/globalSiteTag",
              "path": "v1alpha/{+name}"
            },
            "delete": {
              "httpMethod": "DELETE",
              "id": "analyticsadmin.properties.webDataStreams.delete",
              "description": "Deletes a web stream on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}"
            }
          }
        },
        "androidAppDataStreams": {
          "methods": {
            "get": {
              "description": "Lookup for a single AndroidAppDataStream",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.androidAppDataStreams.get",
              "httpMethod": "GET",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/androidAppDataStreams/{androidAppDataStreamsId}"
            },
            "create": {
              "flatPath": "v1alpha/properties/{propertiesId}/androidAppDataStreams",
              "id": "analyticsadmin.properties.androidAppDataStreams.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST",
              "description": "Creates an android app stream with the specified location and attributes.",
              "path": "v1alpha/{+parent}/androidAppDataStreams"
            },
            "delete": {
              "httpMethod": "DELETE",
              "flatPath": "v1alpha/properties/{propertiesId}/androidAppDataStreams/{androidAppDataStreamsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.androidAppDataStreams.delete",
              "path": "v1alpha/{+name}",
              "description": "Deletes an android app stream on a property."
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.androidAppDataStreams.list",
              "httpMethod": "GET",
              "description": "Returns child android app streams under the specified parent property. Android app streams will be excluded if the caller does not have access. Returns an empty list if no relevant android app streams are found.",
              "path": "v1alpha/{+parent}/androidAppDataStreams",
              "flatPath": "v1alpha/properties/{propertiesId}/androidAppDataStreams"
            },
            "patch": {
              "description": "Updates an android app stream on a property.",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/androidAppDataStreams/{androidAppDataStreamsId}",
              "id": "analyticsadmin.properties.androidAppDataStreams.patch",
              "path": "v1alpha/{+name}"
            }
          }
        },
        "googleAdsLinks": {
          "methods": {
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "id": "analyticsadmin.properties.googleAdsLinks.patch",
              "description": "Updates a GoogleAdsLink on a property",
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH"
            },
            "delete": {
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "httpMethod": "DELETE",
              "description": "Deletes a GoogleAdsLink on a property",
              "id": "analyticsadmin.properties.googleAdsLinks.delete",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/googleAdsLinks",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.googleAdsLinks.list",
              "description": "Lists GoogleAdsLinks on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks"
            },
            "create": {
              "description": "Creates a GoogleAdsLink.",
              "path": "v1alpha/{+parent}/googleAdsLinks",
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks",
              "id": "analyticsadmin.properties.googleAdsLinks.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            }
          }
        },
        "firebaseLinks": {
          "methods": {
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates a FirebaseLink. Properties can have at most one FirebaseLink.",
              "id": "analyticsadmin.properties.firebaseLinks.create",
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks",
              "path": "v1alpha/{+parent}/firebaseLinks"
            },
            "patch": {
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.firebaseLinks.patch",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks/{firebaseLinksId}",
              "description": "Updates a FirebaseLink on a property"
            },
            "delete": {
              "description": "Deletes a FirebaseLink on a property",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.firebaseLinks.delete",
              "httpMethod": "DELETE",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks/{firebaseLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "list": {
              "description": "Lists FirebaseLinks on a property. Properties can have at most one FirebaseLink.",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.firebaseLinks.list",
              "path": "v1alpha/{+parent}/firebaseLinks",
              "httpMethod": "GET"
            }
          }
        },
        "userLinks": {
          "methods": {
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Creates a user link on an account or property. If the user with the specified email already has permissions on the account or property, then the user's existing permissions will be unioned with the permissions specified in the new UserLink.",
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks",
              "path": "v1alpha/{+parent}/userLinks",
              "id": "analyticsadmin.properties.userLinks.create"
            },
            "audit": {
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:audit",
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/userLinks:audit",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "id": "analyticsadmin.properties.userLinks.audit",
              "description": "Lists all user links on an account or property, including implicit ones that come from effective permissions granted by groups or organization admin roles. If a returned user link does not have direct permissions, they cannot be removed from the account or property directly with the DeleteUserLink command. They have to be removed from the group/etc that gives them permissions, which is currently only usable/discoverable in the GA or GMP UIs."
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.userLinks.patch",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks/{userLinksId}",
              "description": "Updates a user link on an account or property.",
              "httpMethod": "PATCH"
            },
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "httpMethod": "GET",
              "description": "Lists all user links on an account or property.",
              "id": "analyticsadmin.properties.userLinks.list",
              "path": "v1alpha/{+parent}/userLinks"
            },
            "batchDelete": {
              "description": "Deletes information about multiple users' links to an account or property.",
              "id": "analyticsadmin.properties.userLinks.batchDelete",
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/userLinks:batchDelete",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchDelete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "batchCreate": {
              "httpMethod": "POST",
              "description": "Creates information about multiple users' links to an account or property. This method is transactional. If any UserLink cannot be created, none of the UserLinks will be created.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "id": "analyticsadmin.properties.userLinks.batchCreate",
              "path": "v1alpha/{+parent}/userLinks:batchCreate",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchCreate"
            },
            "batchUpdate": {
              "path": "v1alpha/{+parent}/userLinks:batchUpdate",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchUpdate",
              "id": "analyticsadmin.properties.userLinks.batchUpdate",
              "description": "Updates information about multiple users' links to an account or property."
            },
            "batchGet": {
              "path": "v1alpha/{+parent}/userLinks:batchGet",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchGet",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "description": "Gets information about multiple users' links to an account or property.",
              "id": "analyticsadmin.properties.userLinks.batchGet"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "description": "Gets information about a user's link to an account or property.",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.userLinks.get",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks/{userLinksId}"
            },
            "delete": {
              "description": "Deletes a user link on an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "id": "analyticsadmin.properties.userLinks.delete",
              "path": "v1alpha/{+name}",
              "httpMethod": "DELETE",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks/{userLinksId}"
            }
          }
        }
      },
      "methods": {
        "delete": {
          "flatPath": "v1alpha/properties/{propertiesId}",
          "id": "analyticsadmin.properties.delete",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1alpha/{+name}",
          "httpMethod": "DELETE",
          "description": "Marks target Property as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted properties. However, they can be restored using the Trash Can UI. If the properties are not restored before the expiration time, the Property and all child resources (eg: GoogleAdsLinks, Streams, UserLinks) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found, or is not an G[...]"
        },
        "get": {
          "id": "analyticsadmin.properties.get",
          "description": "Lookup for a single \"GA4\" Property.",
          "path": "v1alpha/{+name}",
          "flatPath": "v1alpha/properties/{propertiesId}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "GET"
        },
        "create": {
          "description": "Creates an \"GA4\" property with the specified location and attributes.",
          "path": "v1alpha/properties",
          "flatPath": "v1alpha/properties",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.properties.create"
        },
        "patch": {
          "description": "Updates a property.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1alpha/properties/{propertiesId}",
          "id": "analyticsadmin.properties.patch",
          "path": "v1alpha/{+name}",
          "httpMethod": "PATCH"
        },
        "list": {
          "flatPath": "v1alpha/properties",
          "id": "analyticsadmin.properties.list",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Returns child Properties under the specified parent Account. Only \"GA4\" properties will be returned. Properties will be excluded if the caller does not have access. Soft-deleted (ie: \"trashed\") properties are excluded by default. Returns an empty list if no relevant properties are found.",
          "path": "v1alpha/properties",
          "httpMethod": "GET"
        }
      }
    },
    "accountSummaries": {
      "methods": {
        "list": {
          "id": "analyticsadmin.accountSummaries.list",
          "description": "Returns summaries of all accounts accessible by the caller.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "GET",
          "path": "v1alpha/accountSummaries",
          "flatPath": "v1alpha/accountSummaries"
        }
      }
    }
  },
  "ownerDomain": "google.com",
  "version_module": true,
  "description": "",
  "kind": "discovery#restDescription",
  "batchPath": "batch",
  "name": "analyticsadmin",
  "mtlsRootUrl": "https://analyticsadmin.mtls.googleapis.com/",
  "fullyEncodeReservedExpansion": true,
  "rootUrl": "https://analyticsadmin.googleapis.com/",
  "title": "Google Analytics Admin API",
  "revision": "20201210",
  "basePath": "",
  "protocol": "rest",
  "id": "analyticsadmin:v1alpha",
  "canonicalName": "Google Analytics Admin",
  "documentationLink": "http://code.google.com/apis/analytics/docs/mgmt/home.html",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/analytics.manage.users": {
          "description": "Manage Google Analytics Account users by email address"
        },
        "https://www.googleapis.com/auth/analytics.readonly": {
          "description": "View your Google Analytics data"
        },
        "https://www.googleapis.com/auth/analytics.manage.users.readonly": {
          "description": "View Google Analytics user permissions"
        },
        "https://www.googleapis.com/auth/analytics.edit": {
          "description": "Edit Google Analytics management entities"
        }
      }
    }
  },
  "ownerName": "Google",
  "version": "v1alpha",
  "servicePath": ""
}
