{
  "fullyEncodeReservedExpansion": true,
  "mtlsRootUrl": "https://analyticsadmin.mtls.googleapis.com/",
  "documentationLink": "http://code.google.com/apis/analytics/docs/mgmt/home.html",
  "discoveryVersion": "v1",
  "basePath": "",
  "ownerDomain": "google.com",
  "name": "analyticsadmin",
  "protocol": "rest",
  "canonicalName": "Google Analytics Admin",
  "kind": "discovery#restDescription",
  "title": "Google Analytics Admin API",
  "resources": {
    "properties": {
      "resources": {
        "iosAppDataStreams": {
          "methods": {
            "delete": {
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/iosAppDataStreams/{iosAppDataStreamsId}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Deletes an iOS app stream on a property.",
              "id": "analyticsadmin.properties.iosAppDataStreams.delete"
            },
            "patch": {
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.iosAppDataStreams.patch",
              "httpMethod": "PATCH",
              "flatPath": "v1alpha/properties/{propertiesId}/iosAppDataStreams/{iosAppDataStreamsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Updates an iOS app stream on a property."
            },
            "list": {
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.iosAppDataStreams.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/iosAppDataStreams",
              "flatPath": "v1alpha/properties/{propertiesId}/iosAppDataStreams",
              "description": "Returns child iOS app data streams under the specified parent property. iOS app data streams will be excluded if the caller does not have access. Returns an empty list if no relevant iOS app data streams are found."
            },
            "create": {
              "id": "analyticsadmin.properties.iosAppDataStreams.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates an iOS app data stream with the specified location and attributes.",
              "flatPath": "v1alpha/properties/{propertiesId}/iosAppDataStreams",
              "path": "v1alpha/{+parent}/iosAppDataStreams",
              "httpMethod": "POST"
            },
            "get": {
              "description": "Lookup for a single IosAppDataStream",
              "id": "analyticsadmin.properties.iosAppDataStreams.get",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/iosAppDataStreams/{iosAppDataStreamsId}"
            }
          }
        },
        "androidAppDataStreams": {
          "methods": {
            "delete": {
              "id": "analyticsadmin.properties.androidAppDataStreams.delete",
              "httpMethod": "DELETE",
              "flatPath": "v1alpha/properties/{propertiesId}/androidAppDataStreams/{androidAppDataStreamsId}",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Deletes an android app stream on a property."
            },
            "create": {
              "id": "analyticsadmin.properties.androidAppDataStreams.create",
              "description": "Creates an android app stream with the specified location and attributes.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/androidAppDataStreams",
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/androidAppDataStreams"
            },
            "get": {
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.androidAppDataStreams.get",
              "description": "Lookup for a single AndroidAppDataStream",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/androidAppDataStreams/{androidAppDataStreamsId}"
            },
            "patch": {
              "id": "analyticsadmin.properties.androidAppDataStreams.patch",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Updates an android app stream on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/androidAppDataStreams/{androidAppDataStreamsId}",
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH"
            },
            "list": {
              "description": "Returns child android app streams under the specified parent property. Android app streams will be excluded if the caller does not have access. Returns an empty list if no relevant android app streams are found.",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/androidAppDataStreams",
              "path": "v1alpha/{+parent}/androidAppDataStreams",
              "id": "analyticsadmin.properties.androidAppDataStreams.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            }
          }
        },
        "userLinks": {
          "methods": {
            "list": {
              "id": "analyticsadmin.properties.userLinks.list",
              "path": "v1alpha/{+parent}/userLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks",
              "description": "Lists all user links on an account or property.",
              "httpMethod": "GET"
            },
            "patch": {
              "description": "Updates a user link on an account or property.",
              "httpMethod": "PATCH",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks/{userLinksId}",
              "id": "analyticsadmin.properties.userLinks.patch",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "delete": {
              "description": "Deletes a user link on an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "id": "analyticsadmin.properties.userLinks.delete",
              "httpMethod": "DELETE",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks/{userLinksId}",
              "path": "v1alpha/{+name}"
            },
            "batchUpdate": {
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchUpdate",
              "id": "analyticsadmin.properties.userLinks.batchUpdate",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Updates information about multiple users' links to an account or property.",
              "path": "v1alpha/{+parent}/userLinks:batchUpdate",
              "httpMethod": "POST"
            },
            "create": {
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks",
              "id": "analyticsadmin.properties.userLinks.create",
              "path": "v1alpha/{+parent}/userLinks",
              "description": "Creates a user link on an account or property. If the user with the specified email already has permissions on the account or property, then the user's existing permissions will be unioned with the permissions specified in the new UserLink.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "batchCreate": {
              "id": "analyticsadmin.properties.userLinks.batchCreate",
              "path": "v1alpha/{+parent}/userLinks:batchCreate",
              "description": "Creates information about multiple users' links to an account or property. This method is transactional. If any UserLink cannot be created, none of the UserLinks will be created.",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchCreate"
            },
            "batchGet": {
              "httpMethod": "GET",
              "description": "Gets information about multiple users' links to an account or property.",
              "id": "analyticsadmin.properties.userLinks.batchGet",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchGet",
              "path": "v1alpha/{+parent}/userLinks:batchGet"
            },
            "batchDelete": {
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchDelete",
              "description": "Deletes information about multiple users' links to an account or property.",
              "id": "analyticsadmin.properties.userLinks.batchDelete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+parent}/userLinks:batchDelete",
              "httpMethod": "POST"
            },
            "get": {
              "id": "analyticsadmin.properties.userLinks.get",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks/{userLinksId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "description": "Gets information about a user's link to an account or property."
            },
            "audit": {
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:audit",
              "description": "Lists all user links on an account or property, including implicit ones that come from effective permissions granted by groups or organization admin roles. If a returned user link does not have direct permissions, they cannot be removed from the account or property directly with the DeleteUserLink command. They have to be removed from the group/etc that gives them permissions, which is currently only usable/discoverable in the GA or GMP UIs.",
              "path": "v1alpha/{+parent}/userLinks:audit",
              "id": "analyticsadmin.properties.userLinks.audit"
            }
          }
        },
        "webDataStreams": {
          "methods": {
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}",
              "path": "v1alpha/{+name}",
              "description": "Lookup for a single WebDataStream",
              "id": "analyticsadmin.properties.webDataStreams.get",
              "httpMethod": "GET"
            },
            "updateEnhancedMeasurementSettings": {
              "description": "Updates the singleton enhanced measurement settings for this web stream. Note that the stream must enable enhanced measurement for these settings to take effect.",
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}/enhancedMeasurementSettings",
              "httpMethod": "PATCH",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.webDataStreams.updateEnhancedMeasurementSettings"
            },
            "create": {
              "description": "Creates a web stream with the specified location and attributes.",
              "id": "analyticsadmin.properties.webDataStreams.create",
              "path": "v1alpha/{+parent}/webDataStreams",
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST"
            },
            "list": {
              "id": "analyticsadmin.properties.webDataStreams.list",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Returns child web data streams under the specified parent property. Web data streams will be excluded if the caller does not have access. Returns an empty list if no relevant web data streams are found.",
              "path": "v1alpha/{+parent}/webDataStreams"
            },
            "getGlobalSiteTag": {
              "id": "analyticsadmin.properties.webDataStreams.getGlobalSiteTag",
              "description": "Returns the Site Tag for the specified web stream. Site Tags are immutable singletons.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}/globalSiteTag"
            },
            "patch": {
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH",
              "description": "Updates a web stream on a property.",
              "id": "analyticsadmin.properties.webDataStreams.patch",
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "delete": {
              "httpMethod": "DELETE",
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.webDataStreams.delete",
              "description": "Deletes a web stream on a property."
            },
            "getEnhancedMeasurementSettings": {
              "description": "Returns the singleton enhanced measurement settings for this web stream. Note that the stream must enable enhanced measurement for these settings to take effect.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}/enhancedMeasurementSettings",
              "id": "analyticsadmin.properties.webDataStreams.getEnhancedMeasurementSettings",
              "httpMethod": "GET",
              "path": "v1alpha/{+name}"
            }
          }
        },
        "firebaseLinks": {
          "methods": {
            "delete": {
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks/{firebaseLinksId}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Deletes a FirebaseLink on a property",
              "id": "analyticsadmin.properties.firebaseLinks.delete"
            },
            "create": {
              "description": "Creates a FirebaseLink. Properties can have at most one FirebaseLink.",
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/firebaseLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.firebaseLinks.create",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks"
            },
            "patch": {
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks/{firebaseLinksId}",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.firebaseLinks.patch",
              "httpMethod": "PATCH",
              "description": "Updates a FirebaseLink on a property",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "list": {
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/firebaseLinks",
              "id": "analyticsadmin.properties.firebaseLinks.list",
              "description": "Lists FirebaseLinks on a property. Properties can have at most one FirebaseLink.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks"
            }
          }
        },
        "googleAdsLinks": {
          "methods": {
            "delete": {
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Deletes a GoogleAdsLink on a property",
              "httpMethod": "DELETE",
              "id": "analyticsadmin.properties.googleAdsLinks.delete",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}"
            },
            "create": {
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.googleAdsLinks.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates a GoogleAdsLink.",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks",
              "path": "v1alpha/{+parent}/googleAdsLinks"
            },
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks",
              "id": "analyticsadmin.properties.googleAdsLinks.list",
              "description": "Lists GoogleAdsLinks on a property.",
              "path": "v1alpha/{+parent}/googleAdsLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET"
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Updates a GoogleAdsLink on a property",
              "httpMethod": "PATCH",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.googleAdsLinks.patch",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}"
            }
          }
        }
      },
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "GET",
          "description": "Lookup for a single \"GA4\" Property.",
          "flatPath": "v1alpha/properties/{propertiesId}",
          "id": "analyticsadmin.properties.get",
          "path": "v1alpha/{+name}"
        },
        "patch": {
          "flatPath": "v1alpha/properties/{propertiesId}",
          "id": "analyticsadmin.properties.patch",
          "path": "v1alpha/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "PATCH",
          "description": "Updates a property."
        },
        "create": {
          "flatPath": "v1alpha/properties",
          "id": "analyticsadmin.properties.create",
          "description": "Creates an \"GA4\" property with the specified location and attributes.",
          "path": "v1alpha/properties",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "list": {
          "httpMethod": "GET",
          "path": "v1alpha/properties",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "flatPath": "v1alpha/properties",
          "id": "analyticsadmin.properties.list",
          "description": "Returns child Properties under the specified parent Account. Only \"GA4\" properties will be returned. Properties will be excluded if the caller does not have access. Soft-deleted (ie: \"trashed\") properties are excluded by default. Returns an empty list if no relevant properties are found."
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "description": "Marks target Property as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted properties. However, they can be restored using the Trash Can UI. If the properties are not restored before the expiration time, the Property and all child resources (eg: GoogleAdsLinks, Streams, UserLinks) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found, or is not an G[...]",
          "httpMethod": "DELETE",
          "flatPath": "v1alpha/properties/{propertiesId}",
          "id": "analyticsadmin.properties.delete",
          "path": "v1alpha/{+name}"
        }
      }
    },
    "accounts": {
      "methods": {
        "provisionAccountTicket": {
          "path": "v1alpha/accounts:provisionAccountTicket",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "description": "Requests a ticket for creating an account.",
          "httpMethod": "POST",
          "id": "analyticsadmin.accounts.provisionAccountTicket",
          "flatPath": "v1alpha/accounts:provisionAccountTicket"
        },
        "delete": {
          "description": "Marks target Account as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted accounts. However, they can be restored using the Trash Can UI. If the accounts are not restored before the expiration time, the account and all child resources (eg: Properties, GoogleAdsLinks, Streams, UserLinks) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found.",
          "flatPath": "v1alpha/accounts/{accountsId}",
          "path": "v1alpha/{+name}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.accounts.delete"
        },
        "getDataSharingSettings": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.accounts.getDataSharingSettings",
          "path": "v1alpha/{+name}",
          "flatPath": "v1alpha/accounts/{accountsId}/dataSharingSettings",
          "description": "Get data sharing settings on an account. Data sharing settings are singletons.",
          "httpMethod": "GET"
        },
        "patch": {
          "httpMethod": "PATCH",
          "path": "v1alpha/{+name}",
          "description": "Updates an account.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1alpha/accounts/{accountsId}",
          "id": "analyticsadmin.accounts.patch"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Lookup for a single Account.",
          "httpMethod": "GET",
          "flatPath": "v1alpha/accounts/{accountsId}",
          "id": "analyticsadmin.accounts.get",
          "path": "v1alpha/{+name}"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Returns all accounts accessible by the caller. Note that these accounts might not currently have GA4 properties. Soft-deleted (ie: \"trashed\") accounts are excluded by default. Returns an empty list if no relevant accounts are found.",
          "path": "v1alpha/accounts",
          "flatPath": "v1alpha/accounts",
          "id": "analyticsadmin.accounts.list",
          "httpMethod": "GET"
        }
      },
      "resources": {
        "userLinks": {
          "methods": {
            "batchUpdate": {
              "httpMethod": "POST",
              "id": "analyticsadmin.accounts.userLinks.batchUpdate",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchUpdate",
              "path": "v1alpha/{+parent}/userLinks:batchUpdate",
              "description": "Updates information about multiple users' links to an account or property."
            },
            "audit": {
              "path": "v1alpha/{+parent}/userLinks:audit",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:audit",
              "description": "Lists all user links on an account or property, including implicit ones that come from effective permissions granted by groups or organization admin roles. If a returned user link does not have direct permissions, they cannot be removed from the account or property directly with the DeleteUserLink command. They have to be removed from the group/etc that gives them permissions, which is currently only usable/discoverable in the GA or GMP UIs.",
              "httpMethod": "POST",
              "id": "analyticsadmin.accounts.userLinks.audit",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ]
            },
            "batchCreate": {
              "description": "Creates information about multiple users' links to an account or property. This method is transactional. If any UserLink cannot be created, none of the UserLinks will be created.",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchCreate",
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/userLinks:batchCreate",
              "id": "analyticsadmin.accounts.userLinks.batchCreate",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "batchDelete": {
              "id": "analyticsadmin.accounts.userLinks.batchDelete",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchDelete",
              "httpMethod": "POST",
              "description": "Deletes information about multiple users' links to an account or property.",
              "path": "v1alpha/{+parent}/userLinks:batchDelete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "list": {
              "path": "v1alpha/{+parent}/userLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "description": "Lists all user links on an account or property.",
              "id": "analyticsadmin.accounts.userLinks.list",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks",
              "httpMethod": "GET"
            },
            "get": {
              "id": "analyticsadmin.accounts.userLinks.get",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks/{userLinksId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "description": "Gets information about a user's link to an account or property.",
              "path": "v1alpha/{+name}"
            },
            "patch": {
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks/{userLinksId}",
              "path": "v1alpha/{+name}",
              "description": "Updates a user link on an account or property.",
              "id": "analyticsadmin.accounts.userLinks.patch"
            },
            "batchGet": {
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchGet",
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/userLinks:batchGet",
              "description": "Gets information about multiple users' links to an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "id": "analyticsadmin.accounts.userLinks.batchGet"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Creates a user link on an account or property. If the user with the specified email already has permissions on the account or property, then the user's existing permissions will be unioned with the permissions specified in the new UserLink.",
              "path": "v1alpha/{+parent}/userLinks",
              "id": "analyticsadmin.accounts.userLinks.create",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks",
              "httpMethod": "POST"
            },
            "delete": {
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.accounts.userLinks.delete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Deletes a user link on an account or property.",
              "httpMethod": "DELETE",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks/{userLinksId}"
            }
          }
        }
      }
    },
    "accountSummaries": {
      "methods": {
        "list": {
          "description": "Returns summaries of all accounts accessible by the caller.",
          "id": "analyticsadmin.accountSummaries.list",
          "flatPath": "v1alpha/accountSummaries",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1alpha/accountSummaries"
        }
      }
    }
  },
  "ownerName": "Google",
  "baseUrl": "https://analyticsadmin.googleapis.com/",
  "version_module": true,
  "revision": "20210106",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/analytics.manage.users.readonly": {
          "description": "View Google Analytics user permissions"
        },
        "https://www.googleapis.com/auth/analytics.edit": {
          "description": "Edit Google Analytics management entities"
        },
        "https://www.googleapis.com/auth/analytics.manage.users": {
          "description": "Manage Google Analytics Account users by email address"
        },
        "https://www.googleapis.com/auth/analytics.readonly": {
          "description": "See and download your Google Analytics data"
        }
      }
    }
  },
  "id": "analyticsadmin:v1alpha",
  "version": "v1alpha",
  "description": "",
  "batchPath": "batch",
  "servicePath": "",
  "rootUrl": "https://analyticsadmin.googleapis.com/"
}
