{
  "discoveryVersion": "v1",
  "canonicalName": "Google Analytics Admin",
  "ownerDomain": "google.com",
  "documentationLink": "http://code.google.com/apis/analytics/docs/mgmt/home.html",
  "baseUrl": "https://analyticsadmin.googleapis.com/",
  "name": "analyticsadmin",
  "ownerName": "Google",
  "resources": {
    "properties": {
      "methods": {
        "patch": {
          "flatPath": "v1alpha/properties/{propertiesId}",
          "httpMethod": "PATCH",
          "id": "analyticsadmin.properties.patch",
          "path": "v1alpha/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "description": "Updates a property."
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "GET",
          "id": "analyticsadmin.properties.list",
          "path": "v1alpha/properties",
          "flatPath": "v1alpha/properties",
          "description": "Returns child Properties under the specified parent Account. Only \"GA4\" properties will be returned. Properties will be excluded if the caller does not have access. Soft-deleted (ie: \"trashed\") properties are excluded by default. Returns an empty list if no relevant properties are found."
        },
        "delete": {
          "id": "analyticsadmin.properties.delete",
          "flatPath": "v1alpha/properties/{propertiesId}",
          "description": "Marks target Property as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted properties. However, they can be restored using the Trash Can UI. If the properties are not restored before the expiration time, the Property and all child resources (eg: GoogleAdsLinks, Streams, UserLinks) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found, or is not an G[...]",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1alpha/{+name}",
          "httpMethod": "DELETE"
        },
        "create": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1alpha/properties",
          "id": "analyticsadmin.properties.create",
          "flatPath": "v1alpha/properties",
          "description": "Creates an \"GA4\" property with the specified location and attributes."
        },
        "get": {
          "flatPath": "v1alpha/properties/{propertiesId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.properties.get",
          "description": "Lookup for a single \"GA4\" Property.",
          "path": "v1alpha/{+name}"
        }
      },
      "resources": {
        "userLinks": {
          "methods": {
            "batchUpdate": {
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchUpdate",
              "description": "Updates information about multiple users' links to an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+parent}/userLinks:batchUpdate",
              "id": "analyticsadmin.properties.userLinks.batchUpdate",
              "httpMethod": "POST"
            },
            "get": {
              "id": "analyticsadmin.properties.userLinks.get",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks/{userLinksId}",
              "description": "Gets information about a user's link to an account or property.",
              "path": "v1alpha/{+name}"
            },
            "create": {
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks",
              "description": "Creates a user link on an account or property. If the user with the specified email already has permissions on the account or property, then the user's existing permissions will be unioned with the permissions specified in the new UserLink.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+parent}/userLinks",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.userLinks.create"
            },
            "batchCreate": {
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchCreate",
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/userLinks:batchCreate",
              "id": "analyticsadmin.properties.userLinks.batchCreate",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Creates information about multiple users' links to an account or property. This method is transactional. If any UserLink cannot be created, none of the UserLinks will be created."
            },
            "list": {
              "description": "Lists all user links on an account or property.",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks",
              "id": "analyticsadmin.properties.userLinks.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "path": "v1alpha/{+parent}/userLinks",
              "httpMethod": "GET"
            },
            "batchDelete": {
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.userLinks.batchDelete",
              "path": "v1alpha/{+parent}/userLinks:batchDelete",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchDelete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Deletes information about multiple users' links to an account or property."
            },
            "patch": {
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "id": "analyticsadmin.properties.userLinks.patch",
              "path": "v1alpha/{+name}",
              "description": "Updates a user link on an account or property.",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks/{userLinksId}"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "id": "analyticsadmin.properties.userLinks.delete",
              "httpMethod": "DELETE",
              "description": "Deletes a user link on an account or property.",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks/{userLinksId}"
            },
            "audit": {
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:audit",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "description": "Lists all user links on an account or property, including implicit ones that come from effective permissions granted by groups or organization admin roles. If a returned user link does not have direct permissions, they cannot be removed from the account or property directly with the DeleteUserLink command. They have to be removed from the group/etc that gives them permissions, which is currently only usable/discoverable in the GA or GMP UIs.",
              "path": "v1alpha/{+parent}/userLinks:audit",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.userLinks.audit"
            },
            "batchGet": {
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchGet",
              "path": "v1alpha/{+parent}/userLinks:batchGet",
              "id": "analyticsadmin.properties.userLinks.batchGet",
              "description": "Gets information about multiple users' links to an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ]
            }
          }
        },
        "iosAppDataStreams": {
          "methods": {
            "patch": {
              "id": "analyticsadmin.properties.iosAppDataStreams.patch",
              "flatPath": "v1alpha/properties/{propertiesId}/iosAppDataStreams/{iosAppDataStreamsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Updates an iOS app stream on a property.",
              "httpMethod": "PATCH",
              "path": "v1alpha/{+name}"
            },
            "delete": {
              "description": "Deletes an iOS app stream on a property.",
              "id": "analyticsadmin.properties.iosAppDataStreams.delete",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/iosAppDataStreams/{iosAppDataStreamsId}",
              "httpMethod": "DELETE"
            },
            "list": {
              "id": "analyticsadmin.properties.iosAppDataStreams.list",
              "flatPath": "v1alpha/properties/{propertiesId}/iosAppDataStreams",
              "httpMethod": "GET",
              "description": "Returns child iOS app data streams under the specified parent property. iOS app data streams will be excluded if the caller does not have access. Returns an empty list if no relevant iOS app data streams are found.",
              "path": "v1alpha/{+parent}/iosAppDataStreams",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "get": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/iosAppDataStreams/{iosAppDataStreamsId}",
              "id": "analyticsadmin.properties.iosAppDataStreams.get",
              "description": "Lookup for a single IosAppDataStream",
              "path": "v1alpha/{+name}"
            },
            "create": {
              "id": "analyticsadmin.properties.iosAppDataStreams.create",
              "flatPath": "v1alpha/properties/{propertiesId}/iosAppDataStreams",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/iosAppDataStreams",
              "description": "Creates an iOS app data stream with the specified location and attributes."
            }
          }
        },
        "googleAdsLinks": {
          "methods": {
            "create": {
              "description": "Creates a GoogleAdsLink.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.googleAdsLinks.create",
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/googleAdsLinks",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Deletes a GoogleAdsLink on a property",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "id": "analyticsadmin.properties.googleAdsLinks.delete",
              "path": "v1alpha/{+name}",
              "httpMethod": "DELETE"
            },
            "list": {
              "path": "v1alpha/{+parent}/googleAdsLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks",
              "id": "analyticsadmin.properties.googleAdsLinks.list",
              "description": "Lists GoogleAdsLinks on a property.",
              "httpMethod": "GET"
            },
            "patch": {
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "description": "Updates a GoogleAdsLink on a property",
              "id": "analyticsadmin.properties.googleAdsLinks.patch",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "PATCH"
            }
          }
        },
        "androidAppDataStreams": {
          "methods": {
            "list": {
              "path": "v1alpha/{+parent}/androidAppDataStreams",
              "description": "Returns child android app streams under the specified parent property. Android app streams will be excluded if the caller does not have access. Returns an empty list if no relevant android app streams are found.",
              "flatPath": "v1alpha/properties/{propertiesId}/androidAppDataStreams",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.androidAppDataStreams.list",
              "httpMethod": "GET"
            },
            "get": {
              "id": "analyticsadmin.properties.androidAppDataStreams.get",
              "description": "Lookup for a single AndroidAppDataStream",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/androidAppDataStreams/{androidAppDataStreamsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}"
            },
            "delete": {
              "description": "Deletes an android app stream on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/androidAppDataStreams/{androidAppDataStreamsId}",
              "id": "analyticsadmin.properties.androidAppDataStreams.delete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "httpMethod": "DELETE"
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.androidAppDataStreams.patch",
              "httpMethod": "PATCH",
              "flatPath": "v1alpha/properties/{propertiesId}/androidAppDataStreams/{androidAppDataStreamsId}",
              "path": "v1alpha/{+name}",
              "description": "Updates an android app stream on a property."
            },
            "create": {
              "flatPath": "v1alpha/properties/{propertiesId}/androidAppDataStreams",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.androidAppDataStreams.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/androidAppDataStreams",
              "description": "Creates an android app stream with the specified location and attributes."
            }
          }
        },
        "webDataStreams": {
          "methods": {
            "create": {
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.webDataStreams.create",
              "path": "v1alpha/{+parent}/webDataStreams",
              "description": "Creates a web stream with the specified location and attributes."
            },
            "delete": {
              "id": "analyticsadmin.properties.webDataStreams.delete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}",
              "path": "v1alpha/{+name}",
              "httpMethod": "DELETE",
              "description": "Deletes a web stream on a property."
            },
            "getEnhancedMeasurementSettings": {
              "description": "Returns the singleton enhanced measurement settings for this web stream. Note that the stream must enable enhanced measurement for these settings to take effect.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}/enhancedMeasurementSettings",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.webDataStreams.getEnhancedMeasurementSettings",
              "httpMethod": "GET"
            },
            "getGlobalSiteTag": {
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}/globalSiteTag",
              "path": "v1alpha/{+name}",
              "description": "Returns the Site Tag for the specified web stream. Site Tags are immutable singletons.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.webDataStreams.getGlobalSiteTag"
            },
            "updateEnhancedMeasurementSettings": {
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}/enhancedMeasurementSettings",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Updates the singleton enhanced measurement settings for this web stream. Note that the stream must enable enhanced measurement for these settings to take effect.",
              "id": "analyticsadmin.properties.webDataStreams.updateEnhancedMeasurementSettings",
              "httpMethod": "PATCH"
            },
            "list": {
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Returns child web data streams under the specified parent property. Web data streams will be excluded if the caller does not have access. Returns an empty list if no relevant web data streams are found.",
              "path": "v1alpha/{+parent}/webDataStreams",
              "id": "analyticsadmin.properties.webDataStreams.list"
            },
            "get": {
              "path": "v1alpha/{+name}",
              "description": "Lookup for a single WebDataStream",
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.webDataStreams.get",
              "httpMethod": "GET"
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH",
              "description": "Updates a web stream on a property.",
              "id": "analyticsadmin.properties.webDataStreams.patch",
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}"
            }
          }
        },
        "firebaseLinks": {
          "methods": {
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.firebaseLinks.list",
              "path": "v1alpha/{+parent}/firebaseLinks",
              "description": "Lists FirebaseLinks on a property. Properties can have at most one FirebaseLink.",
              "httpMethod": "GET"
            },
            "delete": {
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks/{firebaseLinksId}",
              "id": "analyticsadmin.properties.firebaseLinks.delete",
              "httpMethod": "DELETE",
              "path": "v1alpha/{+name}",
              "description": "Deletes a FirebaseLink on a property",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "patch": {
              "description": "Updates a FirebaseLink on a property",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "PATCH",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks/{firebaseLinksId}",
              "id": "analyticsadmin.properties.firebaseLinks.patch"
            },
            "create": {
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks",
              "id": "analyticsadmin.properties.firebaseLinks.create",
              "description": "Creates a FirebaseLink. Properties can have at most one FirebaseLink.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/firebaseLinks",
              "httpMethod": "POST"
            }
          }
        }
      }
    },
    "accounts": {
      "methods": {
        "get": {
          "flatPath": "v1alpha/accounts/{accountsId}",
          "path": "v1alpha/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Lookup for a single Account.",
          "id": "analyticsadmin.accounts.get",
          "httpMethod": "GET"
        },
        "patch": {
          "flatPath": "v1alpha/accounts/{accountsId}",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1alpha/{+name}",
          "description": "Updates an account.",
          "id": "analyticsadmin.accounts.patch"
        },
        "provisionAccountTicket": {
          "flatPath": "v1alpha/accounts:provisionAccountTicket",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "description": "Requests a ticket for creating an account.",
          "httpMethod": "POST",
          "id": "analyticsadmin.accounts.provisionAccountTicket",
          "path": "v1alpha/accounts:provisionAccountTicket"
        },
        "getDataSharingSettings": {
          "description": "Get data sharing settings on an account. Data sharing settings are singletons.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.accounts.getDataSharingSettings",
          "path": "v1alpha/{+name}",
          "httpMethod": "GET",
          "flatPath": "v1alpha/accounts/{accountsId}/dataSharingSettings"
        },
        "list": {
          "flatPath": "v1alpha/accounts",
          "httpMethod": "GET",
          "path": "v1alpha/accounts",
          "id": "analyticsadmin.accounts.list",
          "description": "Returns all accounts accessible by the caller. Note that these accounts might not currently have GA4 properties. Soft-deleted (ie: \"trashed\") accounts are excluded by default. Returns an empty list if no relevant accounts are found.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "delete": {
          "path": "v1alpha/{+name}",
          "httpMethod": "DELETE",
          "flatPath": "v1alpha/accounts/{accountsId}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.accounts.delete",
          "description": "Marks target Account as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted accounts. However, they can be restored using the Trash Can UI. If the accounts are not restored before the expiration time, the account and all child resources (eg: Properties, GoogleAdsLinks, Streams, UserLinks) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found."
        }
      },
      "resources": {
        "userLinks": {
          "methods": {
            "batchGet": {
              "path": "v1alpha/{+parent}/userLinks:batchGet",
              "httpMethod": "GET",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchGet",
              "id": "analyticsadmin.accounts.userLinks.batchGet",
              "description": "Gets information about multiple users' links to an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ]
            },
            "list": {
              "httpMethod": "GET",
              "id": "analyticsadmin.accounts.userLinks.list",
              "description": "Lists all user links on an account or property.",
              "path": "v1alpha/{+parent}/userLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks"
            },
            "delete": {
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks/{userLinksId}",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.accounts.userLinks.delete",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Deletes a user link on an account or property."
            },
            "get": {
              "id": "analyticsadmin.accounts.userLinks.get",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks/{userLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "path": "v1alpha/{+name}",
              "description": "Gets information about a user's link to an account or property.",
              "httpMethod": "GET"
            },
            "batchUpdate": {
              "description": "Updates information about multiple users' links to an account or property.",
              "id": "analyticsadmin.accounts.userLinks.batchUpdate",
              "path": "v1alpha/{+parent}/userLinks:batchUpdate",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchUpdate",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "audit": {
              "path": "v1alpha/{+parent}/userLinks:audit",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:audit",
              "httpMethod": "POST",
              "description": "Lists all user links on an account or property, including implicit ones that come from effective permissions granted by groups or organization admin roles. If a returned user link does not have direct permissions, they cannot be removed from the account or property directly with the DeleteUserLink command. They have to be removed from the group/etc that gives them permissions, which is currently only usable/discoverable in the GA or GMP UIs.",
              "id": "analyticsadmin.accounts.userLinks.audit",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ]
            },
            "create": {
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks",
              "path": "v1alpha/{+parent}/userLinks",
              "httpMethod": "POST",
              "id": "analyticsadmin.accounts.userLinks.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Creates a user link on an account or property. If the user with the specified email already has permissions on the account or property, then the user's existing permissions will be unioned with the permissions specified in the new UserLink."
            },
            "batchDelete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+parent}/userLinks:batchDelete",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchDelete",
              "httpMethod": "POST",
              "id": "analyticsadmin.accounts.userLinks.batchDelete",
              "description": "Deletes information about multiple users' links to an account or property."
            },
            "batchCreate": {
              "path": "v1alpha/{+parent}/userLinks:batchCreate",
              "description": "Creates information about multiple users' links to an account or property. This method is transactional. If any UserLink cannot be created, none of the UserLinks will be created.",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchCreate",
              "id": "analyticsadmin.accounts.userLinks.batchCreate",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "httpMethod": "POST"
            },
            "patch": {
              "path": "v1alpha/{+name}",
              "description": "Updates a user link on an account or property.",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks/{userLinksId}",
              "id": "analyticsadmin.accounts.userLinks.patch"
            }
          }
        }
      }
    },
    "accountSummaries": {
      "methods": {
        "list": {
          "flatPath": "v1alpha/accountSummaries",
          "path": "v1alpha/accountSummaries",
          "description": "Returns summaries of all accounts accessible by the caller.",
          "id": "analyticsadmin.accountSummaries.list",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        }
      }
    }
  },
  "kind": "discovery#restDescription",
  "protocol": "rest",
  "servicePath": "",
  "basePath": "",
  "description": "",
  "revision": "20201213",
  "title": "Google Analytics Admin API",
  "version": "v1alpha",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/analytics.manage.users": {
          "description": "Manage Google Analytics Account users by email address"
        },
        "https://www.googleapis.com/auth/analytics.edit": {
          "description": "Edit Google Analytics management entities"
        },
        "https://www.googleapis.com/auth/analytics.readonly": {
          "description": "See and download your Google Analytics data"
        },
        "https://www.googleapis.com/auth/analytics.manage.users.readonly": {
          "description": "View Google Analytics user permissions"
        }
      }
    }
  },
  "rootUrl": "https://analyticsadmin.googleapis.com/",
  "version_module": true,
  "fullyEncodeReservedExpansion": true,
  "batchPath": "batch",
  "id": "analyticsadmin:v1alpha",
  "mtlsRootUrl": "https://analyticsadmin.mtls.googleapis.com/"
}
