{
  "ownerName": "Google",
  "canonicalName": "Cloud Identity",
  "fullyEncodeReservedExpansion": true,
  "protocol": "rest",
  "basePath": "",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "View and manage your data across Google Cloud Platform services"
        },
        "https://www.googleapis.com/auth/cloud-identity.devices.lookup": {
          "description": "See your device details"
        },
        "https://www.googleapis.com/auth/cloud-identity.groups.readonly": {
          "description": "See any Cloud Identity Groups that you can access, including group members and their emails"
        },
        "https://www.googleapis.com/auth/cloud-identity.groups": {
          "description": "See, change, create, and delete any of the Cloud Identity Groups that you can access, including the members of each group"
        }
      }
    }
  },
  "baseUrl": "https://cloudidentity.googleapis.com/",
  "description": "API for provisioning and managing identity resources.",
  "version": "v1",
  "id": "cloudidentity:v1",
  "discoveryVersion": "v1",
  "batchPath": "batch",
  "mtlsRootUrl": "https://cloudidentity.mtls.googleapis.com/",
  "revision": "20210204",
  "name": "cloudidentity",
  "ownerDomain": "google.com",
  "title": "Cloud Identity API",
  "rootUrl": "https://cloudidentity.googleapis.com/",
  "servicePath": "",
  "kind": "discovery#restDescription",
  "version_module": true,
  "documentationLink": "https://cloud.google.com/identity/",
  "resources": {
    "devices": {
      "resources": {
        "deviceUsers": {
          "methods": {
            "delete": {
              "httpMethod": "DELETE",
              "id": "cloudidentity.devices.deviceUsers.delete",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}",
              "path": "v1/{+name}",
              "description": "Deletes the specified DeviceUser. This also revokes the user's access to device data."
            },
            "cancelWipe": {
              "httpMethod": "POST",
              "path": "v1/{+name}:cancelWipe",
              "description": "Cancels an unfinished user account wipe. This operation can be used to cancel device wipe in the gap between the wipe operation returning success and the device being wiped.",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:cancelWipe",
              "id": "cloudidentity.devices.deviceUsers.cancelWipe"
            },
            "list": {
              "flatPath": "v1/devices/{devicesId}/deviceUsers",
              "path": "v1/{+parent}/deviceUsers",
              "description": "Lists/Searches DeviceUsers.",
              "id": "cloudidentity.devices.deviceUsers.list",
              "httpMethod": "GET"
            },
            "block": {
              "httpMethod": "POST",
              "path": "v1/{+name}:block",
              "description": "Blocks device from accessing user data",
              "id": "cloudidentity.devices.deviceUsers.block",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:block"
            },
            "get": {
              "description": "Retrieves the specified DeviceUser",
              "path": "v1/{+name}",
              "httpMethod": "GET",
              "id": "cloudidentity.devices.deviceUsers.get",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}"
            },
            "lookup": {
              "id": "cloudidentity.devices.deviceUsers.lookup",
              "flatPath": "v1/devices/{devicesId}/deviceUsers:lookup",
              "description": "Looks up resource names of the DeviceUsers associated with the caller's credentials, as well as the properties provided in the request. This method must be called with end-user credentials with the scope: https://www.googleapis.com/auth/cloud-identity.devices.lookup If multiple properties are provided, only DeviceUsers having all of these properties are considered as matches - i.e. the query behaves like an AND. Different platforms require different amounts of infor[...]",
              "httpMethod": "GET",
              "path": "v1/{+parent}:lookup",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices.lookup"
              ]
            },
            "approve": {
              "id": "cloudidentity.devices.deviceUsers.approve",
              "path": "v1/{+name}:approve",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:approve",
              "description": "Approves device to access user data.",
              "httpMethod": "POST"
            },
            "wipe": {
              "path": "v1/{+name}:wipe",
              "id": "cloudidentity.devices.deviceUsers.wipe",
              "httpMethod": "POST",
              "description": "Wipes the user's account on a device. Other data on the device that is not associated with the user's work account is not affected. For example, if a Gmail app is installed on a device that is used for personal and work purposes, and the user is logged in to the Gmail app with their personal account as well as their work account, wiping the \"deviceUser\" by their work administrator will not affect their personal account within Gmail or other apps such as Photos.",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:wipe"
            }
          },
          "resources": {
            "clientStates": {
              "methods": {
                "get": {
                  "path": "v1/{+name}",
                  "id": "cloudidentity.devices.deviceUsers.clientStates.get",
                  "httpMethod": "GET",
                  "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates/{clientStatesId}",
                  "description": "Gets the client state for the device user"
                },
                "list": {
                  "httpMethod": "GET",
                  "id": "cloudidentity.devices.deviceUsers.clientStates.list",
                  "path": "v1/{+parent}/clientStates",
                  "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates",
                  "description": "Lists the client states for the given search query."
                },
                "patch": {
                  "path": "v1/{+name}",
                  "httpMethod": "PATCH",
                  "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates/{clientStatesId}",
                  "description": "Updates the client state for the device user **Note**: This method is available only to customers who have one of the following SKUs: Enterprise Standard, Enterprise Plus, Enterprise for Education, and Cloud Identity Premium",
                  "id": "cloudidentity.devices.deviceUsers.clientStates.patch"
                }
              }
            }
          }
        }
      },
      "methods": {
        "wipe": {
          "httpMethod": "POST",
          "id": "cloudidentity.devices.wipe",
          "description": "Wipes all data on the specified device.",
          "flatPath": "v1/devices/{devicesId}:wipe",
          "path": "v1/{+name}:wipe"
        },
        "get": {
          "id": "cloudidentity.devices.get",
          "description": "Retrieves the specified device.",
          "httpMethod": "GET",
          "path": "v1/{+name}",
          "flatPath": "v1/devices/{devicesId}"
        },
        "cancelWipe": {
          "description": "Cancels an unfinished device wipe. This operation can be used to cancel device wipe in the gap between the wipe operation returning success and the device being wiped. This operation is possible when the device is in a \"pending wipe\" state. The device enters the \"pending wipe\" state when a wipe device command is issued, but has not yet been sent to the device. The cancel wipe will fail if the wipe command has already been issued to the device.",
          "path": "v1/{+name}:cancelWipe",
          "httpMethod": "POST",
          "flatPath": "v1/devices/{devicesId}:cancelWipe",
          "id": "cloudidentity.devices.cancelWipe"
        },
        "list": {
          "description": "Lists/Searches devices.",
          "httpMethod": "GET",
          "id": "cloudidentity.devices.list",
          "flatPath": "v1/devices",
          "path": "v1/devices"
        },
        "delete": {
          "description": "Deletes the specified device.",
          "httpMethod": "DELETE",
          "path": "v1/{+name}",
          "flatPath": "v1/devices/{devicesId}",
          "id": "cloudidentity.devices.delete"
        },
        "create": {
          "httpMethod": "POST",
          "path": "v1/devices",
          "description": "Creates a device. Only company-owned device may be created. **Note**: This method is available only to customers who have one of the following SKUs: Enterprise Standard, Enterprise Plus, Enterprise for Education, and Cloud Identity Premium",
          "id": "cloudidentity.devices.create",
          "flatPath": "v1/devices"
        }
      }
    },
    "groups": {
      "resources": {
        "memberships": {
          "methods": {
            "lookup": {
              "description": "Looks up the [resource name](https://cloud.google.com/apis/design/resource_names) of a `Membership` by its `EntityKey`.",
              "path": "v1/{+parent}/memberships:lookup",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "id": "cloudidentity.groups.memberships.lookup",
              "flatPath": "v1/groups/{groupsId}/memberships:lookup"
            },
            "searchTransitiveGroups": {
              "flatPath": "v1/groups/{groupsId}/memberships:searchTransitiveGroups",
              "id": "cloudidentity.groups.memberships.searchTransitiveGroups",
              "path": "v1/{+parent}/memberships:searchTransitiveGroups",
              "httpMethod": "GET",
              "description": "Search transitive groups of a member. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. If the account of the member is not one of these, a 403 (PERMISSION_DENIED) HTTP status code will be returned. A transitive group is any group that has a direct or indirect membership to the member. Actor must have view permissions all transitive groups.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ]
            },
            "modifyMembershipRoles": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "id": "cloudidentity.groups.memberships.modifyMembershipRoles",
              "path": "v1/{+name}:modifyMembershipRoles",
              "description": "Modifies the `MembershipRole`s of a `Membership`.",
              "flatPath": "v1/groups/{groupsId}/memberships/{membershipsId}:modifyMembershipRoles",
              "httpMethod": "POST"
            },
            "list": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Lists the `Membership`s within a `Group`.",
              "id": "cloudidentity.groups.memberships.list",
              "path": "v1/{+parent}/memberships",
              "flatPath": "v1/groups/{groupsId}/memberships"
            },
            "create": {
              "httpMethod": "POST",
              "id": "cloudidentity.groups.memberships.create",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "flatPath": "v1/groups/{groupsId}/memberships",
              "path": "v1/{+parent}/memberships",
              "description": "Creates a `Membership`."
            },
            "getMembershipGraph": {
              "flatPath": "v1/groups/{groupsId}/memberships:getMembershipGraph",
              "path": "v1/{+parent}/memberships:getMembershipGraph",
              "httpMethod": "GET",
              "id": "cloudidentity.groups.memberships.getMembershipGraph",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Get a membership graph of just a member or both a member and a group. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. If the account of the member is not one of these, a 403 (PERMISSION_DENIED) HTTP status code will be returned. Given a member, the response will contain all membership paths from the member. Given both a group and a member, the respon[...]"
            },
            "checkTransitiveMembership": {
              "httpMethod": "GET",
              "id": "cloudidentity.groups.memberships.checkTransitiveMembership",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Check a potential member for membership in a group. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. If the account of the member is not one of these, a 403 (PERMISSION_DENIED) HTTP status code will be returned. A member has membership to a group as long as there is a single viewable transitive membership between the group and the member. The actor mu[...]",
              "path": "v1/{+parent}/memberships:checkTransitiveMembership",
              "flatPath": "v1/groups/{groupsId}/memberships:checkTransitiveMembership"
            },
            "delete": {
              "id": "cloudidentity.groups.memberships.delete",
              "description": "Deletes a `Membership`.",
              "httpMethod": "DELETE",
              "path": "v1/{+name}",
              "flatPath": "v1/groups/{groupsId}/memberships/{membershipsId}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ]
            },
            "get": {
              "path": "v1/{+name}",
              "httpMethod": "GET",
              "flatPath": "v1/groups/{groupsId}/memberships/{membershipsId}",
              "id": "cloudidentity.groups.memberships.get",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Retrieves a `Membership`."
            },
            "searchTransitiveMemberships": {
              "description": "Search transitive memberships of a group. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. If the account of the group is not one of these, a 403 (PERMISSION_DENIED) HTTP status code will be returned. A transitive membership is any direct or indirect membership of a group. Actor must have view permissions to all transitive memberships.",
              "flatPath": "v1/groups/{groupsId}/memberships:searchTransitiveMemberships",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "httpMethod": "GET",
              "id": "cloudidentity.groups.memberships.searchTransitiveMemberships",
              "path": "v1/{+parent}/memberships:searchTransitiveMemberships"
            }
          }
        }
      },
      "methods": {
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.groups.delete",
          "path": "v1/{+name}",
          "description": "Deletes a `Group`.",
          "flatPath": "v1/groups/{groupsId}",
          "httpMethod": "DELETE"
        },
        "lookup": {
          "id": "cloudidentity.groups.lookup",
          "flatPath": "v1/groups:lookup",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "httpMethod": "GET",
          "path": "v1/groups:lookup",
          "description": "Looks up the [resource name](https://cloud.google.com/apis/design/resource_names) of a `Group` by its `EntityKey`."
        },
        "patch": {
          "httpMethod": "PATCH",
          "flatPath": "v1/groups/{groupsId}",
          "id": "cloudidentity.groups.patch",
          "description": "Updates a `Group`.",
          "path": "v1/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ]
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "path": "v1/groups",
          "id": "cloudidentity.groups.list",
          "httpMethod": "GET",
          "flatPath": "v1/groups",
          "description": "Lists the `Group`s under a customer or namespace."
        },
        "create": {
          "path": "v1/groups",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.groups.create",
          "httpMethod": "POST",
          "description": "Creates a Group.",
          "flatPath": "v1/groups"
        },
        "search": {
          "id": "cloudidentity.groups.search",
          "description": "Searches for `Group`s matching a specified query.",
          "path": "v1/groups:search",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "flatPath": "v1/groups:search",
          "httpMethod": "GET"
        },
        "get": {
          "id": "cloudidentity.groups.get",
          "httpMethod": "GET",
          "description": "Retrieves a `Group`.",
          "flatPath": "v1/groups/{groupsId}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "path": "v1/{+name}"
        }
      }
    }
  }
}
