{
  "canonicalName": "Dfareporting",
  "mtlsRootUrl": "https://dfareporting.mtls.googleapis.com/",
  "ownerName": "Google",
  "protocol": "rest",
  "ownerDomain": "google.com",
  "revision": "20210210",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/ddmconversions": {
          "description": "Manage DoubleClick Digital Marketing conversions"
        },
        "https://www.googleapis.com/auth/dfareporting": {
          "description": "View and manage DoubleClick for Advertisers reports"
        },
        "https://www.googleapis.com/auth/dfatrafficking": {
          "description": "View and manage your DoubleClick Campaign Manager's (DCM) display ad campaigns"
        }
      }
    }
  },
  "documentationLink": "https://developers.google.com/doubleclick-advertisers/",
  "batchPath": "batch",
  "version": "v3.3",
  "rootUrl": "https://dfareporting.googleapis.com/",
  "discoveryVersion": "v1",
  "baseUrl": "https://dfareporting.googleapis.com/dfareporting/v3.3/",
  "resources": {
    "videoFormats": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "description": "Gets one video format by ID.",
          "id": "dfareporting.videoFormats.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/videoFormats/{id}",
          "flatPath": "userprofiles/{profileId}/videoFormats/{id}"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.videoFormats.list",
          "path": "userprofiles/{profileId}/videoFormats",
          "description": "Lists available video formats.",
          "flatPath": "userprofiles/{profileId}/videoFormats",
          "httpMethod": "GET"
        }
      }
    },
    "sizes": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/sizes/{id}",
          "path": "userprofiles/{profileId}/sizes/{id}",
          "description": "Gets one size by ID.",
          "id": "dfareporting.sizes.get"
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/sizes",
          "description": "Retrieves a list of sizes, possibly filtered. Retrieved sizes are globally unique and may include values not currently in use by your account. Due to this, the list of sizes returned by this method may differ from the list seen in the Trafficking UI.",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/sizes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.sizes.list"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/sizes",
          "httpMethod": "POST",
          "description": "Inserts a new size.",
          "flatPath": "userprofiles/{profileId}/sizes",
          "id": "dfareporting.sizes.insert"
        }
      }
    },
    "advertiserGroups": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserGroups.list",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/advertiserGroups",
          "description": "Retrieves a list of advertiser groups, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{profileId}/advertiserGroups"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{profileId}/advertiserGroups",
          "path": "userprofiles/{profileId}/advertiserGroups",
          "description": "Updates an existing advertiser group. This method supports patch semantics.",
          "id": "dfareporting.advertiserGroups.patch"
        },
        "insert": {
          "path": "userprofiles/{profileId}/advertiserGroups",
          "id": "dfareporting.advertiserGroups.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/advertiserGroups",
          "description": "Inserts a new advertiser group.",
          "httpMethod": "POST"
        },
        "delete": {
          "path": "userprofiles/{profileId}/advertiserGroups/{id}",
          "id": "dfareporting.advertiserGroups.delete",
          "description": "Deletes an existing advertiser group.",
          "flatPath": "userprofiles/{profileId}/advertiserGroups/{id}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "id": "dfareporting.advertiserGroups.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/advertiserGroups",
          "path": "userprofiles/{profileId}/advertiserGroups",
          "description": "Updates an existing advertiser group.",
          "httpMethod": "PUT"
        },
        "get": {
          "id": "dfareporting.advertiserGroups.get",
          "description": "Gets one advertiser group by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/advertiserGroups/{id}",
          "path": "userprofiles/{profileId}/advertiserGroups/{id}"
        }
      }
    },
    "floodlightActivities": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivities.get",
          "path": "userprofiles/{profileId}/floodlightActivities/{id}",
          "flatPath": "userprofiles/{profileId}/floodlightActivities/{id}",
          "httpMethod": "GET",
          "description": "Gets one floodlight activity by ID."
        },
        "generatetag": {
          "flatPath": "userprofiles/{profileId}/floodlightActivities/generatetag",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Generates a tag for a floodlight activity.",
          "id": "dfareporting.floodlightActivities.generatetag",
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/floodlightActivities/generatetag"
        },
        "update": {
          "path": "userprofiles/{profileId}/floodlightActivities",
          "id": "dfareporting.floodlightActivities.update",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{profileId}/floodlightActivities",
          "description": "Updates an existing floodlight activity.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "id": "dfareporting.floodlightActivities.patch",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/floodlightActivities",
          "description": "Updates an existing floodlight activity. This method supports patch semantics.",
          "flatPath": "userprofiles/{profileId}/floodlightActivities"
        },
        "list": {
          "description": "Retrieves a list of floodlight activities, possibly filtered. This method supports paging.",
          "id": "dfareporting.floodlightActivities.list",
          "path": "userprofiles/{profileId}/floodlightActivities",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/floodlightActivities"
        },
        "delete": {
          "httpMethod": "DELETE",
          "description": "Deletes an existing floodlight activity.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivities.delete",
          "path": "userprofiles/{profileId}/floodlightActivities/{id}",
          "flatPath": "userprofiles/{profileId}/floodlightActivities/{id}"
        },
        "insert": {
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/floodlightActivities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivities.insert",
          "path": "userprofiles/{profileId}/floodlightActivities",
          "description": "Inserts a new floodlight activity."
        }
      }
    },
    "campaignCreativeAssociations": {
      "methods": {
        "insert": {
          "id": "dfareporting.campaignCreativeAssociations.insert",
          "httpMethod": "POST",
          "description": "Associates a creative with the specified campaign. This method creates a default ad with dimensions matching the creative in the campaign if such a default ad does not exist already.",
          "path": "userprofiles/{profileId}/campaigns/{campaignId}/campaignCreativeAssociations",
          "flatPath": "userprofiles/{profileId}/campaigns/{campaignId}/campaignCreativeAssociations",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/campaigns/{campaignId}/campaignCreativeAssociations",
          "path": "userprofiles/{profileId}/campaigns/{campaignId}/campaignCreativeAssociations",
          "id": "dfareporting.campaignCreativeAssociations.list",
          "description": "Retrieves the list of creative IDs associated with the specified campaign. This method supports paging.",
          "httpMethod": "GET"
        }
      }
    },
    "contentCategories": {
      "methods": {
        "insert": {
          "path": "userprofiles/{profileId}/contentCategories",
          "flatPath": "userprofiles/{profileId}/contentCategories",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new content category.",
          "id": "dfareporting.contentCategories.insert",
          "httpMethod": "POST"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.contentCategories.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/contentCategories/{id}",
          "description": "Gets one content category by ID.",
          "path": "userprofiles/{profileId}/contentCategories/{id}"
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/contentCategories",
          "id": "dfareporting.contentCategories.list",
          "description": "Retrieves a list of content categories, possibly filtered. This method supports paging.",
          "path": "userprofiles/{profileId}/contentCategories",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "delete": {
          "flatPath": "userprofiles/{profileId}/contentCategories/{id}",
          "description": "Deletes an existing content category.",
          "id": "dfareporting.contentCategories.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "DELETE",
          "path": "userprofiles/{profileId}/contentCategories/{id}"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/contentCategories",
          "id": "dfareporting.contentCategories.patch",
          "path": "userprofiles/{profileId}/contentCategories",
          "httpMethod": "PATCH",
          "description": "Updates an existing content category. This method supports patch semantics."
        },
        "update": {
          "path": "userprofiles/{profileId}/contentCategories",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{profileId}/contentCategories",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing content category.",
          "id": "dfareporting.contentCategories.update"
        }
      }
    },
    "operatingSystems": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.operatingSystems.get",
          "description": "Gets one operating system by DART ID.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/operatingSystems/{dartId}",
          "path": "userprofiles/{profileId}/operatingSystems/{dartId}"
        },
        "list": {
          "description": "Retrieves a list of operating systems.",
          "flatPath": "userprofiles/{profileId}/operatingSystems",
          "id": "dfareporting.operatingSystems.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/operatingSystems"
        }
      }
    },
    "languages": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{profileId}/languages",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/languages",
          "httpMethod": "GET",
          "id": "dfareporting.languages.list",
          "description": "Retrieves a list of languages."
        }
      }
    },
    "files": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "flatPath": "userprofiles/{profileId}/files",
          "path": "userprofiles/{profileId}/files",
          "id": "dfareporting.files.list",
          "httpMethod": "GET",
          "description": "Lists files for a user profile."
        },
        "get": {
          "path": "reports/{reportId}/files/{fileId}",
          "supportsMediaDownload": true,
          "flatPath": "reports/{reportId}/files/{fileId}",
          "id": "dfareporting.files.get",
          "httpMethod": "GET",
          "description": "Retrieves a report file by its report ID and file ID. This method supports media download.",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ]
        }
      }
    },
    "userProfiles": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "id": "dfareporting.userProfiles.get",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one user profile by ID.",
          "flatPath": "userprofiles/{profileId}",
          "path": "userprofiles/{profileId}"
        },
        "list": {
          "path": "userprofiles",
          "id": "dfareporting.userProfiles.list",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles",
          "description": "Retrieves list of user profiles for a user."
        }
      }
    },
    "dimensionValues": {
      "methods": {
        "query": {
          "httpMethod": "POST",
          "description": "Retrieves list of report dimension values for a list of filters.",
          "path": "userprofiles/{profileId}/dimensionvalues/query",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.dimensionValues.query",
          "flatPath": "userprofiles/{profileId}/dimensionvalues/query"
        }
      }
    },
    "targetingTemplates": {
      "methods": {
        "patch": {
          "description": "Updates an existing targeting template. This method supports patch semantics.",
          "path": "userprofiles/{profileId}/targetingTemplates",
          "id": "dfareporting.targetingTemplates.patch",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{profileId}/targetingTemplates",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/targetingTemplates",
          "description": "Retrieves a list of targeting templates, optionally filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/targetingTemplates",
          "id": "dfareporting.targetingTemplates.list",
          "httpMethod": "GET"
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/targetingTemplates/{id}",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/targetingTemplates/{id}",
          "description": "Gets one targeting template by ID.",
          "id": "dfareporting.targetingTemplates.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "flatPath": "userprofiles/{profileId}/targetingTemplates",
          "httpMethod": "POST",
          "id": "dfareporting.targetingTemplates.insert",
          "path": "userprofiles/{profileId}/targetingTemplates",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new targeting template."
        },
        "update": {
          "description": "Updates an existing targeting template.",
          "httpMethod": "PUT",
          "path": "userprofiles/{profileId}/targetingTemplates",
          "flatPath": "userprofiles/{profileId}/targetingTemplates",
          "id": "dfareporting.targetingTemplates.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "placementGroups": {
      "methods": {
        "patch": {
          "path": "userprofiles/{profileId}/placementGroups",
          "id": "dfareporting.placementGroups.patch",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{profileId}/placementGroups",
          "description": "Updates an existing placement group. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "flatPath": "userprofiles/{profileId}/placementGroups",
          "description": "Updates an existing placement group.",
          "path": "userprofiles/{profileId}/placementGroups",
          "httpMethod": "PUT",
          "id": "dfareporting.placementGroups.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/placementGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.placementGroups.list",
          "description": "Retrieves a list of placement groups, possibly filtered. This method supports paging.",
          "path": "userprofiles/{profileId}/placementGroups"
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/placementGroups/{id}",
          "path": "userprofiles/{profileId}/placementGroups/{id}",
          "id": "dfareporting.placementGroups.get",
          "description": "Gets one placement group by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/placementGroups",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/placementGroups",
          "description": "Inserts a new placement group.",
          "id": "dfareporting.placementGroups.insert"
        }
      }
    },
    "floodlightConfigurations": {
      "methods": {
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing floodlight configuration.",
          "id": "dfareporting.floodlightConfigurations.update",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{profileId}/floodlightConfigurations",
          "path": "userprofiles/{profileId}/floodlightConfigurations"
        },
        "patch": {
          "flatPath": "userprofiles/{profileId}/floodlightConfigurations",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing floodlight configuration. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "id": "dfareporting.floodlightConfigurations.patch",
          "path": "userprofiles/{profileId}/floodlightConfigurations"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightConfigurations.list",
          "path": "userprofiles/{profileId}/floodlightConfigurations",
          "description": "Retrieves a list of floodlight configurations, possibly filtered.",
          "flatPath": "userprofiles/{profileId}/floodlightConfigurations",
          "httpMethod": "GET"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightConfigurations.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/floodlightConfigurations/{id}",
          "path": "userprofiles/{profileId}/floodlightConfigurations/{id}",
          "description": "Gets one floodlight configuration by ID."
        }
      }
    },
    "placements": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "id": "dfareporting.placements.get",
          "path": "userprofiles/{profileId}/placements/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one placement by ID.",
          "flatPath": "userprofiles/{profileId}/placements/{id}"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placements.update",
          "path": "userprofiles/{profileId}/placements",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{profileId}/placements",
          "description": "Updates an existing placement."
        },
        "generatetags": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placements.generatetags",
          "path": "userprofiles/{profileId}/placements/generatetags",
          "description": "Generates tags for a placement.",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/placements/generatetags"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/placements",
          "description": "Inserts a new placement.",
          "id": "dfareporting.placements.insert",
          "path": "userprofiles/{profileId}/placements",
          "httpMethod": "POST"
        },
        "patch": {
          "id": "dfareporting.placements.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing placement. This method supports patch semantics.",
          "path": "userprofiles/{profileId}/placements",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{profileId}/placements"
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/placements",
          "path": "userprofiles/{profileId}/placements",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of placements, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "id": "dfareporting.placements.list"
        }
      }
    },
    "creativeFields": {
      "methods": {
        "patch": {
          "httpMethod": "PATCH",
          "id": "dfareporting.creativeFields.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/creativeFields",
          "description": "Updates an existing creative field. This method supports patch semantics.",
          "path": "userprofiles/{profileId}/creativeFields"
        },
        "insert": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new creative field.",
          "path": "userprofiles/{profileId}/creativeFields",
          "flatPath": "userprofiles/{profileId}/creativeFields",
          "id": "dfareporting.creativeFields.insert"
        },
        "delete": {
          "id": "dfareporting.creativeFields.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "DELETE",
          "path": "userprofiles/{profileId}/creativeFields/{id}",
          "description": "Deletes an existing creative field.",
          "flatPath": "userprofiles/{profileId}/creativeFields/{id}"
        },
        "get": {
          "description": "Gets one creative field by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/creativeFields/{id}",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/creativeFields/{id}",
          "id": "dfareporting.creativeFields.get"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/creativeFields",
          "httpMethod": "GET",
          "id": "dfareporting.creativeFields.list",
          "flatPath": "userprofiles/{profileId}/creativeFields",
          "description": "Retrieves a list of creative fields, possibly filtered. This method supports paging."
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFields.update",
          "path": "userprofiles/{profileId}/creativeFields",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{profileId}/creativeFields",
          "description": "Updates an existing creative field."
        }
      }
    },
    "placementStrategies": {
      "methods": {
        "patch": {
          "path": "userprofiles/{profileId}/placementStrategies",
          "httpMethod": "PATCH",
          "description": "Updates an existing placement strategy. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementStrategies.patch",
          "flatPath": "userprofiles/{profileId}/placementStrategies"
        },
        "list": {
          "id": "dfareporting.placementStrategies.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/placementStrategies",
          "flatPath": "userprofiles/{profileId}/placementStrategies",
          "description": "Retrieves a list of placement strategies, possibly filtered. This method supports paging."
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one placement strategy by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/placementStrategies/{id}",
          "flatPath": "userprofiles/{profileId}/placementStrategies/{id}",
          "id": "dfareporting.placementStrategies.get"
        },
        "insert": {
          "httpMethod": "POST",
          "description": "Inserts a new placement strategy.",
          "path": "userprofiles/{profileId}/placementStrategies",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/placementStrategies",
          "id": "dfareporting.placementStrategies.insert"
        },
        "update": {
          "httpMethod": "PUT",
          "path": "userprofiles/{profileId}/placementStrategies",
          "description": "Updates an existing placement strategy.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/placementStrategies",
          "id": "dfareporting.placementStrategies.update"
        },
        "delete": {
          "description": "Deletes an existing placement strategy.",
          "httpMethod": "DELETE",
          "flatPath": "userprofiles/{profileId}/placementStrategies/{id}",
          "path": "userprofiles/{profileId}/placementStrategies/{id}",
          "id": "dfareporting.placementStrategies.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "operatingSystemVersions": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{profileId}/operatingSystemVersions",
          "id": "dfareporting.operatingSystemVersions.list",
          "description": "Retrieves a list of operating system versions.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/operatingSystemVersions"
        },
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/operatingSystemVersions/{id}",
          "flatPath": "userprofiles/{profileId}/operatingSystemVersions/{id}",
          "id": "dfareporting.operatingSystemVersions.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one operating system version by ID."
        }
      }
    },
    "accounts": {
      "methods": {
        "patch": {
          "path": "userprofiles/{profileId}/accounts",
          "flatPath": "userprofiles/{profileId}/accounts",
          "httpMethod": "PATCH",
          "id": "dfareporting.accounts.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing account. This method supports patch semantics."
        },
        "list": {
          "path": "userprofiles/{profileId}/accounts",
          "description": "Retrieves the list of accounts, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/accounts",
          "id": "dfareporting.accounts.list"
        },
        "get": {
          "description": "Gets one account by ID.",
          "id": "dfareporting.accounts.get",
          "flatPath": "userprofiles/{profileId}/accounts/{id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/accounts/{id}"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/accounts",
          "httpMethod": "PUT",
          "description": "Updates an existing account.",
          "flatPath": "userprofiles/{profileId}/accounts",
          "id": "dfareporting.accounts.update"
        }
      }
    },
    "subaccounts": {
      "methods": {
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/subaccounts",
          "httpMethod": "PUT",
          "id": "dfareporting.subaccounts.update",
          "flatPath": "userprofiles/{profileId}/subaccounts",
          "description": "Updates an existing subaccount."
        },
        "patch": {
          "flatPath": "userprofiles/{profileId}/subaccounts",
          "id": "dfareporting.subaccounts.patch",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/subaccounts",
          "description": "Updates an existing subaccount. This method supports patch semantics."
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/subaccounts",
          "description": "Inserts a new subaccount.",
          "httpMethod": "POST",
          "id": "dfareporting.subaccounts.insert",
          "flatPath": "userprofiles/{profileId}/subaccounts"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets a list of subaccounts, possibly filtered. This method supports paging.",
          "id": "dfareporting.subaccounts.list",
          "flatPath": "userprofiles/{profileId}/subaccounts",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/subaccounts"
        },
        "get": {
          "id": "dfareporting.subaccounts.get",
          "flatPath": "userprofiles/{profileId}/subaccounts/{id}",
          "description": "Gets one subaccount by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/subaccounts/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "cities": {
      "methods": {
        "list": {
          "path": "userprofiles/{profileId}/cities",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of cities, possibly filtered.",
          "id": "dfareporting.cities.list",
          "flatPath": "userprofiles/{profileId}/cities"
        }
      }
    },
    "remarketingLists": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "description": "Gets one remarketing list by ID.",
          "id": "dfareporting.remarketingLists.get",
          "flatPath": "userprofiles/{profileId}/remarketingLists/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/remarketingLists/{id}"
        },
        "insert": {
          "flatPath": "userprofiles/{profileId}/remarketingLists",
          "id": "dfareporting.remarketingLists.insert",
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/remarketingLists",
          "description": "Inserts a new remarketing list.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "id": "dfareporting.remarketingLists.patch",
          "description": "Updates an existing remarketing list. This method supports patch semantics.",
          "flatPath": "userprofiles/{profileId}/remarketingLists",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/remarketingLists",
          "httpMethod": "PATCH"
        },
        "list": {
          "description": "Retrieves a list of remarketing lists, possibly filtered. This method supports paging.",
          "path": "userprofiles/{profileId}/remarketingLists",
          "id": "dfareporting.remarketingLists.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/remarketingLists"
        },
        "update": {
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.remarketingLists.update",
          "flatPath": "userprofiles/{profileId}/remarketingLists",
          "path": "userprofiles/{profileId}/remarketingLists",
          "description": "Updates an existing remarketing list."
        }
      }
    },
    "targetableRemarketingLists": {
      "methods": {
        "list": {
          "description": "Retrieves a list of targetable remarketing lists, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{profileId}/targetableRemarketingLists",
          "httpMethod": "GET",
          "id": "dfareporting.targetableRemarketingLists.list",
          "path": "userprofiles/{profileId}/targetableRemarketingLists",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "path": "userprofiles/{profileId}/targetableRemarketingLists/{id}",
          "flatPath": "userprofiles/{profileId}/targetableRemarketingLists/{id}",
          "description": "Gets one remarketing list by ID.",
          "id": "dfareporting.targetableRemarketingLists.get",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "creativeAssets": {
      "methods": {
        "insert": {
          "httpMethod": "POST",
          "id": "dfareporting.creativeAssets.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/creativeAssets/{advertiserId}/creativeAssets",
          "flatPath": "userprofiles/{profileId}/creativeAssets/{advertiserId}/creativeAssets",
          "supportsMediaUpload": true,
          "description": "Inserts a new creative asset."
        }
      }
    },
    "userRoles": {
      "methods": {
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/userRoles",
          "id": "dfareporting.userRoles.update",
          "path": "userprofiles/{profileId}/userRoles",
          "httpMethod": "PUT",
          "description": "Updates an existing user role."
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/userRoles/{id}",
          "httpMethod": "DELETE",
          "id": "dfareporting.userRoles.delete",
          "path": "userprofiles/{profileId}/userRoles/{id}",
          "description": "Deletes an existing user role."
        },
        "insert": {
          "id": "dfareporting.userRoles.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/userRoles",
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/userRoles",
          "description": "Inserts a new user role."
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of user roles, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/userRoles",
          "flatPath": "userprofiles/{profileId}/userRoles",
          "id": "dfareporting.userRoles.list"
        },
        "patch": {
          "path": "userprofiles/{profileId}/userRoles",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{profileId}/userRoles",
          "description": "Updates an existing user role. This method supports patch semantics.",
          "id": "dfareporting.userRoles.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "description": "Gets one user role by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/userRoles/{id}",
          "id": "dfareporting.userRoles.get",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/userRoles/{id}"
        }
      }
    },
    "projects": {
      "methods": {
        "get": {
          "description": "Gets one project by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/projects/{id}",
          "id": "dfareporting.projects.get",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/projects/{id}"
        },
        "list": {
          "id": "dfareporting.projects.list",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/projects",
          "description": "Retrieves a list of projects, possibly filtered. This method supports paging .",
          "flatPath": "userprofiles/{profileId}/projects"
        }
      }
    },
    "orderDocuments": {
      "methods": {
        "list": {
          "id": "dfareporting.orderDocuments.list",
          "flatPath": "userprofiles/{profileId}/projects/{projectId}/orderDocuments",
          "path": "userprofiles/{profileId}/projects/{projectId}/orderDocuments",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of order documents, possibly filtered. This method supports paging.",
          "httpMethod": "GET"
        },
        "get": {
          "description": "Gets one order document by ID.",
          "path": "userprofiles/{profileId}/projects/{projectId}/orderDocuments/{id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.orderDocuments.get",
          "flatPath": "userprofiles/{profileId}/projects/{projectId}/orderDocuments/{id}"
        }
      }
    },
    "regions": {
      "methods": {
        "list": {
          "id": "dfareporting.regions.list",
          "description": "Retrieves a list of regions.",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/regions",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/regions"
        }
      }
    },
    "advertisers": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new advertiser.",
          "flatPath": "userprofiles/{profileId}/advertisers",
          "path": "userprofiles/{profileId}/advertisers",
          "httpMethod": "POST",
          "id": "dfareporting.advertisers.insert"
        },
        "patch": {
          "description": "Updates an existing advertiser. This method supports patch semantics.",
          "flatPath": "userprofiles/{profileId}/advertisers",
          "path": "userprofiles/{profileId}/advertisers",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertisers.patch"
        },
        "get": {
          "httpMethod": "GET",
          "description": "Gets one advertiser by ID.",
          "flatPath": "userprofiles/{profileId}/advertisers/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/advertisers/{id}",
          "id": "dfareporting.advertisers.get"
        },
        "list": {
          "id": "dfareporting.advertisers.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/advertisers",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/advertisers",
          "description": "Retrieves a list of advertisers, possibly filtered. This method supports paging."
        },
        "update": {
          "path": "userprofiles/{profileId}/advertisers",
          "id": "dfareporting.advertisers.update",
          "description": "Updates an existing advertiser.",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{profileId}/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "orders": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/projects/{projectId}/orders/{id}",
          "description": "Gets one order by ID.",
          "flatPath": "userprofiles/{profileId}/projects/{projectId}/orders/{id}",
          "id": "dfareporting.orders.get"
        },
        "list": {
          "id": "dfareporting.orders.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of orders, possibly filtered. This method supports paging.",
          "path": "userprofiles/{profileId}/projects/{projectId}/orders",
          "flatPath": "userprofiles/{profileId}/projects/{projectId}/orders"
        }
      }
    },
    "conversions": {
      "methods": {
        "batchupdate": {
          "id": "dfareporting.conversions.batchupdate",
          "path": "userprofiles/{profileId}/conversions/batchupdate",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "description": "Updates existing conversions.",
          "flatPath": "userprofiles/{profileId}/conversions/batchupdate"
        },
        "batchinsert": {
          "id": "dfareporting.conversions.batchinsert",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "flatPath": "userprofiles/{profileId}/conversions/batchinsert",
          "httpMethod": "POST",
          "description": "Inserts conversions.",
          "path": "userprofiles/{profileId}/conversions/batchinsert"
        }
      }
    },
    "mobileApps": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/mobileApps/{id}",
          "flatPath": "userprofiles/{profileId}/mobileApps/{id}",
          "id": "dfareporting.mobileApps.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one mobile app by ID."
        },
        "list": {
          "id": "dfareporting.mobileApps.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/mobileApps",
          "description": "Retrieves list of available mobile apps.",
          "path": "userprofiles/{profileId}/mobileApps"
        }
      }
    },
    "sites": {
      "methods": {
        "insert": {
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/sites",
          "path": "userprofiles/{profileId}/sites",
          "description": "Inserts a new site.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.sites.insert"
        },
        "update": {
          "flatPath": "userprofiles/{profileId}/sites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/sites",
          "id": "dfareporting.sites.update",
          "description": "Updates an existing site.",
          "httpMethod": "PUT"
        },
        "list": {
          "id": "dfareporting.sites.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/sites",
          "description": "Retrieves a list of sites, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/sites"
        },
        "patch": {
          "id": "dfareporting.sites.patch",
          "flatPath": "userprofiles/{profileId}/sites",
          "httpMethod": "PATCH",
          "description": "Updates an existing site. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/sites"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.sites.get",
          "description": "Gets one site by ID.",
          "path": "userprofiles/{profileId}/sites/{id}",
          "flatPath": "userprofiles/{profileId}/sites/{id}"
        }
      }
    },
    "remarketingListShares": {
      "methods": {
        "get": {
          "path": "userprofiles/{profileId}/remarketingListShares/{remarketingListId}",
          "flatPath": "userprofiles/{profileId}/remarketingListShares/{remarketingListId}",
          "id": "dfareporting.remarketingListShares.get",
          "description": "Gets one remarketing list share by remarketing list ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        },
        "update": {
          "description": "Updates an existing remarketing list share.",
          "path": "userprofiles/{profileId}/remarketingListShares",
          "id": "dfareporting.remarketingListShares.update",
          "flatPath": "userprofiles/{profileId}/remarketingListShares",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT"
        },
        "patch": {
          "path": "userprofiles/{profileId}/remarketingListShares",
          "description": "Updates an existing remarketing list share. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.remarketingListShares.patch",
          "flatPath": "userprofiles/{profileId}/remarketingListShares"
        }
      }
    },
    "browsers": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{profileId}/browsers",
          "description": "Retrieves a list of browsers.",
          "path": "userprofiles/{profileId}/browsers",
          "httpMethod": "GET",
          "id": "dfareporting.browsers.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "accountUserProfiles": {
      "methods": {
        "get": {
          "path": "userprofiles/{profileId}/accountUserProfiles/{id}",
          "flatPath": "userprofiles/{profileId}/accountUserProfiles/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one account user profile by ID.",
          "id": "dfareporting.accountUserProfiles.get"
        },
        "patch": {
          "description": "Updates an existing account user profile. This method supports patch semantics.",
          "flatPath": "userprofiles/{profileId}/accountUserProfiles",
          "path": "userprofiles/{profileId}/accountUserProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "id": "dfareporting.accountUserProfiles.patch"
        },
        "insert": {
          "flatPath": "userprofiles/{profileId}/accountUserProfiles",
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/accountUserProfiles",
          "id": "dfareporting.accountUserProfiles.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new account user profile."
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/accountUserProfiles",
          "description": "Retrieves a list of account user profiles, possibly filtered. This method supports paging.",
          "id": "dfareporting.accountUserProfiles.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/accountUserProfiles"
        },
        "update": {
          "path": "userprofiles/{profileId}/accountUserProfiles",
          "description": "Updates an existing account user profile.",
          "httpMethod": "PUT",
          "id": "dfareporting.accountUserProfiles.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/accountUserProfiles"
        }
      }
    },
    "creativeFieldValues": {
      "methods": {
        "patch": {
          "id": "dfareporting.creativeFieldValues.patch",
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "description": "Updates an existing creative field value. This method supports patch semantics.",
          "flatPath": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new creative field value.",
          "flatPath": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "id": "dfareporting.creativeFieldValues.insert"
        },
        "update": {
          "flatPath": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "description": "Updates an existing creative field value.",
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "httpMethod": "PUT",
          "id": "dfareporting.creativeFieldValues.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues/{id}",
          "httpMethod": "GET",
          "description": "Gets one creative field value by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues/{id}",
          "id": "dfareporting.creativeFieldValues.get"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing creative field value.",
          "id": "dfareporting.creativeFieldValues.delete",
          "flatPath": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues/{id}",
          "httpMethod": "DELETE",
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues/{id}"
        },
        "list": {
          "description": "Retrieves a list of creative field values, possibly filtered. This method supports paging.",
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFieldValues.list",
          "flatPath": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "httpMethod": "GET"
        }
      }
    },
    "reports": {
      "resources": {
        "compatibleFields": {
          "methods": {
            "query": {
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "path": "userprofiles/{profileId}/reports/compatiblefields/query",
              "id": "dfareporting.reports.compatibleFields.query",
              "description": "Returns the fields that are compatible to be selected in the respective sections of a report criteria, given the fields already selected in the input report and user permissions.",
              "httpMethod": "POST",
              "flatPath": "userprofiles/{profileId}/reports/compatiblefields/query"
            }
          }
        },
        "files": {
          "methods": {
            "get": {
              "supportsMediaDownload": true,
              "httpMethod": "GET",
              "id": "dfareporting.reports.files.get",
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "path": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}",
              "description": "Retrieves a report file by its report ID and file ID. This method supports media download."
            },
            "list": {
              "path": "userprofiles/{profileId}/reports/{reportId}/files",
              "description": "Lists files for a report.",
              "id": "dfareporting.reports.files.list",
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "httpMethod": "GET"
            }
          }
        }
      },
      "methods": {
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves list of reports.",
          "path": "userprofiles/{profileId}/reports",
          "id": "dfareporting.reports.list",
          "flatPath": "userprofiles/{profileId}/reports",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ]
        },
        "insert": {
          "description": "Creates a report.",
          "httpMethod": "POST",
          "id": "dfareporting.reports.insert",
          "path": "userprofiles/{profileId}/reports",
          "flatPath": "userprofiles/{profileId}/reports",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ]
        },
        "run": {
          "flatPath": "userprofiles/{profileId}/reports/{reportId}/run",
          "description": "Runs a report.",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "httpMethod": "POST",
          "id": "dfareporting.reports.run",
          "path": "userprofiles/{profileId}/reports/{reportId}/run"
        },
        "delete": {
          "description": "Deletes a report by its ID.",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "httpMethod": "DELETE",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "id": "dfareporting.reports.delete"
        },
        "get": {
          "id": "dfareporting.reports.get",
          "httpMethod": "GET",
          "description": "Retrieves a report by its ID.",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "flatPath": "userprofiles/{profileId}/reports/{reportId}"
        },
        "patch": {
          "description": "Updates an existing report. This method supports patch semantics.",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.reports.patch",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "PATCH"
        },
        "update": {
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "httpMethod": "PUT",
          "id": "dfareporting.reports.update",
          "description": "Updates a report.",
          "path": "userprofiles/{profileId}/reports/{reportId}"
        }
      }
    },
    "directorySites": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "id": "dfareporting.directorySites.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one directory site by ID.",
          "flatPath": "userprofiles/{profileId}/directorySites/{id}",
          "path": "userprofiles/{profileId}/directorySites/{id}"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/directorySites",
          "path": "userprofiles/{profileId}/directorySites",
          "httpMethod": "POST",
          "description": "Inserts a new directory site.",
          "id": "dfareporting.directorySites.insert"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.directorySites.list",
          "description": "Retrieves a list of directory sites, possibly filtered. This method supports paging.",
          "path": "userprofiles/{profileId}/directorySites",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/directorySites"
        }
      }
    },
    "ads": {
      "methods": {
        "get": {
          "id": "dfareporting.ads.get",
          "description": "Gets one ad by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/ads/{id}",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/ads/{id}"
        },
        "insert": {
          "httpMethod": "POST",
          "id": "dfareporting.ads.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/ads",
          "description": "Inserts a new ad.",
          "path": "userprofiles/{profileId}/ads"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/ads",
          "flatPath": "userprofiles/{profileId}/ads",
          "httpMethod": "PUT",
          "id": "dfareporting.ads.update",
          "description": "Updates an existing ad."
        },
        "patch": {
          "path": "userprofiles/{profileId}/ads",
          "httpMethod": "PATCH",
          "id": "dfareporting.ads.patch",
          "description": "Updates an existing ad. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/ads"
        },
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/ads",
          "flatPath": "userprofiles/{profileId}/ads",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of ads, possibly filtered. This method supports paging.",
          "id": "dfareporting.ads.list"
        }
      }
    },
    "creatives": {
      "methods": {
        "patch": {
          "description": "Updates an existing creative. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "id": "dfareporting.creatives.patch",
          "flatPath": "userprofiles/{profileId}/creatives",
          "path": "userprofiles/{profileId}/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "path": "userprofiles/{profileId}/creatives/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creatives.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/creatives/{id}",
          "description": "Gets one creative by ID."
        },
        "list": {
          "id": "dfareporting.creatives.list",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/creatives",
          "flatPath": "userprofiles/{profileId}/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of creatives, possibly filtered. This method supports paging."
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/creatives",
          "description": "Updates an existing creative.",
          "httpMethod": "PUT",
          "path": "userprofiles/{profileId}/creatives",
          "id": "dfareporting.creatives.update"
        },
        "insert": {
          "path": "userprofiles/{profileId}/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/creatives",
          "id": "dfareporting.creatives.insert",
          "httpMethod": "POST",
          "description": "Inserts a new creative."
        }
      }
    },
    "campaigns": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/campaigns/{id}",
          "description": "Gets one campaign by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.campaigns.get",
          "path": "userprofiles/{profileId}/campaigns/{id}"
        },
        "patch": {
          "path": "userprofiles/{profileId}/campaigns",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing campaign. This method supports patch semantics.",
          "id": "dfareporting.campaigns.patch",
          "flatPath": "userprofiles/{profileId}/campaigns"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/campaigns",
          "description": "Retrieves a list of campaigns, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{profileId}/campaigns",
          "id": "dfareporting.campaigns.list"
        },
        "insert": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/campaigns",
          "id": "dfareporting.campaigns.insert",
          "path": "userprofiles/{profileId}/campaigns",
          "description": "Inserts a new campaign."
        },
        "update": {
          "path": "userprofiles/{profileId}/campaigns",
          "httpMethod": "PUT",
          "description": "Updates an existing campaign.",
          "flatPath": "userprofiles/{profileId}/campaigns",
          "id": "dfareporting.campaigns.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "eventTags": {
      "methods": {
        "list": {
          "id": "dfareporting.eventTags.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/eventTags",
          "description": "Retrieves a list of event tags, possibly filtered.",
          "path": "userprofiles/{profileId}/eventTags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing event tag.",
          "id": "dfareporting.eventTags.update",
          "flatPath": "userprofiles/{profileId}/eventTags",
          "httpMethod": "PUT",
          "path": "userprofiles/{profileId}/eventTags"
        },
        "get": {
          "description": "Gets one event tag by ID.",
          "id": "dfareporting.eventTags.get",
          "flatPath": "userprofiles/{profileId}/eventTags/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/eventTags/{id}"
        },
        "delete": {
          "path": "userprofiles/{profileId}/eventTags/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing event tag.",
          "id": "dfareporting.eventTags.delete",
          "httpMethod": "DELETE",
          "flatPath": "userprofiles/{profileId}/eventTags/{id}"
        },
        "patch": {
          "flatPath": "userprofiles/{profileId}/eventTags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.eventTags.patch",
          "path": "userprofiles/{profileId}/eventTags",
          "description": "Updates an existing event tag. This method supports patch semantics.",
          "httpMethod": "PATCH"
        },
        "insert": {
          "path": "userprofiles/{profileId}/eventTags",
          "description": "Inserts a new event tag.",
          "id": "dfareporting.eventTags.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/eventTags"
        }
      }
    },
    "connectionTypes": {
      "methods": {
        "list": {
          "id": "dfareporting.connectionTypes.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of connection types.",
          "path": "userprofiles/{profileId}/connectionTypes",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/connectionTypes"
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/connectionTypes/{id}",
          "path": "userprofiles/{profileId}/connectionTypes/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one connection type by ID.",
          "id": "dfareporting.connectionTypes.get",
          "httpMethod": "GET"
        }
      }
    },
    "accountActiveAdSummaries": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/accountActiveAdSummaries/{summaryAccountId}",
          "path": "userprofiles/{profileId}/accountActiveAdSummaries/{summaryAccountId}",
          "id": "dfareporting.accountActiveAdSummaries.get",
          "httpMethod": "GET",
          "description": "Gets the account's active ad summary by account ID."
        }
      }
    },
    "inventoryItems": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{profileId}/projects/{projectId}/inventoryItems",
          "id": "dfareporting.inventoryItems.list",
          "description": "Retrieves a list of inventory items, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/projects/{projectId}/inventoryItems"
        },
        "get": {
          "id": "dfareporting.inventoryItems.get",
          "flatPath": "userprofiles/{profileId}/projects/{projectId}/inventoryItems/{id}",
          "path": "userprofiles/{profileId}/projects/{projectId}/inventoryItems/{id}",
          "httpMethod": "GET",
          "description": "Gets one inventory item by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "postalCodes": {
      "methods": {
        "get": {
          "path": "userprofiles/{profileId}/postalCodes/{code}",
          "flatPath": "userprofiles/{profileId}/postalCodes/{code}",
          "description": "Gets one postal code by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.postalCodes.get",
          "httpMethod": "GET"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.postalCodes.list",
          "description": "Retrieves a list of postal codes.",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/postalCodes",
          "flatPath": "userprofiles/{profileId}/postalCodes"
        }
      }
    },
    "userRolePermissionGroups": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{profileId}/userRolePermissionGroups/{id}",
          "id": "dfareporting.userRolePermissionGroups.get",
          "path": "userprofiles/{profileId}/userRolePermissionGroups/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one user role permission group by ID."
        },
        "list": {
          "path": "userprofiles/{profileId}/userRolePermissionGroups",
          "flatPath": "userprofiles/{profileId}/userRolePermissionGroups",
          "id": "dfareporting.userRolePermissionGroups.list",
          "description": "Gets a list of all supported user role permission groups.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        }
      }
    },
    "advertiserLandingPages": {
      "methods": {
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/advertiserLandingPages",
          "flatPath": "userprofiles/{profileId}/advertiserLandingPages",
          "id": "dfareporting.advertiserLandingPages.patch",
          "httpMethod": "PATCH",
          "description": "Updates an existing advertiser landing page. This method supports patch semantics."
        },
        "list": {
          "description": "Retrieves a list of landing pages.",
          "httpMethod": "GET",
          "id": "dfareporting.advertiserLandingPages.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/advertiserLandingPages",
          "flatPath": "userprofiles/{profileId}/advertiserLandingPages"
        },
        "update": {
          "path": "userprofiles/{profileId}/advertiserLandingPages",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserLandingPages.update",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{profileId}/advertiserLandingPages",
          "description": "Updates an existing landing page."
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/advertiserLandingPages/{id}",
          "id": "dfareporting.advertiserLandingPages.get",
          "flatPath": "userprofiles/{profileId}/advertiserLandingPages/{id}",
          "httpMethod": "GET",
          "description": "Gets one landing page by ID."
        },
        "insert": {
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/advertiserLandingPages",
          "id": "dfareporting.advertiserLandingPages.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new landing page.",
          "flatPath": "userprofiles/{profileId}/advertiserLandingPages"
        }
      }
    },
    "floodlightActivityGroups": {
      "methods": {
        "insert": {
          "id": "dfareporting.floodlightActivityGroups.insert",
          "path": "userprofiles/{profileId}/floodlightActivityGroups",
          "description": "Inserts a new floodlight activity group.",
          "flatPath": "userprofiles/{profileId}/floodlightActivityGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing floodlight activity group. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "path": "userprofiles/{profileId}/floodlightActivityGroups",
          "flatPath": "userprofiles/{profileId}/floodlightActivityGroups",
          "id": "dfareporting.floodlightActivityGroups.patch"
        },
        "get": {
          "description": "Gets one floodlight activity group by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/floodlightActivityGroups/{id}",
          "flatPath": "userprofiles/{profileId}/floodlightActivityGroups/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivityGroups.get"
        },
        "list": {
          "path": "userprofiles/{profileId}/floodlightActivityGroups",
          "description": "Retrieves a list of floodlight activity groups, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{profileId}/floodlightActivityGroups",
          "id": "dfareporting.floodlightActivityGroups.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        },
        "update": {
          "path": "userprofiles/{profileId}/floodlightActivityGroups",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing floodlight activity group.",
          "id": "dfareporting.floodlightActivityGroups.update",
          "flatPath": "userprofiles/{profileId}/floodlightActivityGroups"
        }
      }
    },
    "userRolePermissions": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets a list of user role permissions, possibly filtered.",
          "path": "userprofiles/{profileId}/userRolePermissions",
          "flatPath": "userprofiles/{profileId}/userRolePermissions",
          "id": "dfareporting.userRolePermissions.list"
        },
        "get": {
          "description": "Gets one user role permission by ID.",
          "flatPath": "userprofiles/{profileId}/userRolePermissions/{id}",
          "id": "dfareporting.userRolePermissions.get",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/userRolePermissions/{id}"
        }
      }
    },
    "metros": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/metros",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.metros.list",
          "path": "userprofiles/{profileId}/metros",
          "description": "Retrieves a list of metros."
        }
      }
    },
    "countries": {
      "methods": {
        "get": {
          "id": "dfareporting.countries.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/countries/{dartId}",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/countries/{dartId}",
          "description": "Gets one country by ID."
        },
        "list": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/countries",
          "flatPath": "userprofiles/{profileId}/countries",
          "description": "Retrieves a list of countries.",
          "id": "dfareporting.countries.list"
        }
      }
    },
    "accountPermissionGroups": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{profileId}/accountPermissionGroups/{id}",
          "id": "dfareporting.accountPermissionGroups.get",
          "description": "Gets one account permission group by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/accountPermissionGroups/{id}",
          "httpMethod": "GET"
        },
        "list": {
          "id": "dfareporting.accountPermissionGroups.list",
          "flatPath": "userprofiles/{profileId}/accountPermissionGroups",
          "httpMethod": "GET",
          "description": "Retrieves the list of account permission groups.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/accountPermissionGroups"
        }
      }
    },
    "changeLogs": {
      "methods": {
        "list": {
          "id": "dfareporting.changeLogs.list",
          "httpMethod": "GET",
          "description": "Retrieves a list of change logs. This method supports paging.",
          "flatPath": "userprofiles/{profileId}/changeLogs",
          "path": "userprofiles/{profileId}/changeLogs",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "id": "dfareporting.changeLogs.get",
          "httpMethod": "GET",
          "description": "Gets one change log by ID.",
          "flatPath": "userprofiles/{profileId}/changeLogs/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/changeLogs/{id}"
        }
      }
    },
    "accountPermissions": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{profileId}/accountPermissions",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountPermissions.list",
          "path": "userprofiles/{profileId}/accountPermissions",
          "description": "Retrieves the list of account permissions."
        },
        "get": {
          "id": "dfareporting.accountPermissions.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one account permission by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/accountPermissions/{id}",
          "flatPath": "userprofiles/{profileId}/accountPermissions/{id}"
        }
      }
    },
    "dynamicTargetingKeys": {
      "methods": {
        "delete": {
          "id": "dfareporting.dynamicTargetingKeys.delete",
          "httpMethod": "DELETE",
          "path": "userprofiles/{profileId}/dynamicTargetingKeys/{objectId}",
          "flatPath": "userprofiles/{profileId}/dynamicTargetingKeys/{objectId}",
          "description": "Deletes an existing dynamic targeting key.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "description": "Inserts a new dynamic targeting key. Keys must be created at the advertiser level before being assigned to the advertiser's ads, creatives, or placements. There is a maximum of 1000 keys per advertiser, out of which a maximum of 20 keys can be assigned per ad, creative, or placement.",
          "id": "dfareporting.dynamicTargetingKeys.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/dynamicTargetingKeys",
          "flatPath": "userprofiles/{profileId}/dynamicTargetingKeys"
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/dynamicTargetingKeys",
          "description": "Retrieves a list of dynamic targeting keys.",
          "id": "dfareporting.dynamicTargetingKeys.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/dynamicTargetingKeys",
          "httpMethod": "GET"
        }
      }
    },
    "platformTypes": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{profileId}/platformTypes",
          "id": "dfareporting.platformTypes.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/platformTypes",
          "httpMethod": "GET",
          "description": "Retrieves a list of platform types."
        },
        "get": {
          "description": "Gets one platform type by ID.",
          "path": "userprofiles/{profileId}/platformTypes/{id}",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/platformTypes/{id}",
          "id": "dfareporting.platformTypes.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "mobileCarriers": {
      "methods": {
        "get": {
          "path": "userprofiles/{profileId}/mobileCarriers/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/mobileCarriers/{id}",
          "httpMethod": "GET",
          "id": "dfareporting.mobileCarriers.get",
          "description": "Gets one mobile carrier by ID."
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/mobileCarriers",
          "id": "dfareporting.mobileCarriers.list",
          "description": "Retrieves a list of mobile carriers.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/mobileCarriers"
        }
      }
    },
    "creativeGroups": {
      "methods": {
        "update": {
          "httpMethod": "PUT",
          "path": "userprofiles/{profileId}/creativeGroups",
          "flatPath": "userprofiles/{profileId}/creativeGroups",
          "description": "Updates an existing creative group.",
          "id": "dfareporting.creativeGroups.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "id": "dfareporting.creativeGroups.list",
          "path": "userprofiles/{profileId}/creativeGroups",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/creativeGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of creative groups, possibly filtered. This method supports paging."
        },
        "get": {
          "path": "userprofiles/{profileId}/creativeGroups/{id}",
          "id": "dfareporting.creativeGroups.get",
          "description": "Gets one creative group by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/creativeGroups/{id}"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeGroups.patch",
          "path": "userprofiles/{profileId}/creativeGroups",
          "httpMethod": "PATCH",
          "description": "Updates an existing creative group. This method supports patch semantics.",
          "flatPath": "userprofiles/{profileId}/creativeGroups"
        },
        "insert": {
          "flatPath": "userprofiles/{profileId}/creativeGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/creativeGroups",
          "description": "Inserts a new creative group.",
          "httpMethod": "POST",
          "id": "dfareporting.creativeGroups.insert"
        }
      }
    }
  },
  "basePath": "/dfareporting/v3.3/",
  "description": "Build applications to efficiently manage large or complex trafficking, reporting, and attribution workflows for Campaign Manager 360.",
  "name": "dfareporting",
  "title": "Campaign Manager 360 API",
  "kind": "discovery#restDescription",
  "id": "dfareporting:v3.3",
  "servicePath": "dfareporting/v3.3/"
}
