{
  "revision": "20201102",
  "name": "dfareporting",
  "batchPath": "batch",
  "protocol": "rest",
  "discoveryVersion": "v1",
  "version": "v3.4",
  "rootUrl": "https://dfareporting.googleapis.com/",
  "ownerDomain": "google.com",
  "description": "Manage your DoubleClick Campaign Manager ad campaigns and reports.",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/dfatrafficking": {
          "description": "View and manage your DoubleClick Campaign Manager's (DCM) display ad campaigns"
        },
        "https://www.googleapis.com/auth/ddmconversions": {
          "description": "Manage DoubleClick Digital Marketing conversions"
        },
        "https://www.googleapis.com/auth/dfareporting": {
          "description": "View and manage DoubleClick for Advertisers reports"
        }
      }
    }
  },
  "baseUrl": "https://dfareporting.googleapis.com/dfareporting/v3.4/",
  "canonicalName": "Dfareporting",
  "documentationLink": "https://developers.google.com/doubleclick-advertisers/",
  "ownerName": "Google",
  "title": "Campaign Manager 360 API",
  "kind": "discovery#restDescription",
  "mtlsRootUrl": "https://dfareporting.mtls.googleapis.com/",
  "servicePath": "dfareporting/v3.4/",
  "id": "dfareporting:v3.4",
  "basePath": "/dfareporting/v3.4/",
  "resources": {
    "campaigns": {
      "methods": {
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "description": "Updates an existing campaign. This method supports patch semantics.",
          "id": "dfareporting.campaigns.patch",
          "flatPath": "userprofiles/{profileId}/campaigns",
          "path": "userprofiles/{profileId}/campaigns"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/campaigns",
          "description": "Updates an existing campaign.",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{profileId}/campaigns",
          "id": "dfareporting.campaigns.update"
        },
        "get": {
          "path": "userprofiles/{profileId}/campaigns/{id}",
          "flatPath": "userprofiles/{profileId}/campaigns/{id}",
          "httpMethod": "GET",
          "description": "Gets one campaign by ID.",
          "id": "dfareporting.campaigns.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "flatPath": "userprofiles/{profileId}/campaigns",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new campaign.",
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/campaigns",
          "id": "dfareporting.campaigns.insert"
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/campaigns",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of campaigns, possibly filtered. This method supports paging.",
          "path": "userprofiles/{profileId}/campaigns",
          "id": "dfareporting.campaigns.list"
        }
      }
    },
    "orders": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one order by ID.",
          "flatPath": "userprofiles/{profileId}/projects/{projectId}/orders/{id}",
          "id": "dfareporting.orders.get",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/projects/{projectId}/orders/{id}"
        },
        "list": {
          "description": "Retrieves a list of orders, possibly filtered. This method supports paging.",
          "id": "dfareporting.orders.list",
          "path": "userprofiles/{profileId}/projects/{projectId}/orders",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/projects/{projectId}/orders",
          "httpMethod": "GET"
        }
      }
    },
    "floodlightActivityGroups": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/floodlightActivityGroups",
          "flatPath": "userprofiles/{profileId}/floodlightActivityGroups",
          "description": "Inserts a new floodlight activity group.",
          "id": "dfareporting.floodlightActivityGroups.insert",
          "httpMethod": "POST"
        },
        "update": {
          "id": "dfareporting.floodlightActivityGroups.update",
          "flatPath": "userprofiles/{profileId}/floodlightActivityGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/floodlightActivityGroups",
          "description": "Updates an existing floodlight activity group.",
          "httpMethod": "PUT"
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/floodlightActivityGroups",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/floodlightActivityGroups",
          "description": "Retrieves a list of floodlight activity groups, possibly filtered. This method supports paging.",
          "id": "dfareporting.floodlightActivityGroups.list"
        },
        "patch": {
          "flatPath": "userprofiles/{profileId}/floodlightActivityGroups",
          "description": "Updates an existing floodlight activity group. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "id": "dfareporting.floodlightActivityGroups.patch",
          "path": "userprofiles/{profileId}/floodlightActivityGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "description": "Gets one floodlight activity group by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/floodlightActivityGroups/{id}",
          "path": "userprofiles/{profileId}/floodlightActivityGroups/{id}",
          "id": "dfareporting.floodlightActivityGroups.get"
        }
      }
    },
    "targetableRemarketingLists": {
      "methods": {
        "get": {
          "description": "Gets one remarketing list by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/targetableRemarketingLists/{id}",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/targetableRemarketingLists/{id}",
          "id": "dfareporting.targetableRemarketingLists.get"
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/targetableRemarketingLists",
          "path": "userprofiles/{profileId}/targetableRemarketingLists",
          "httpMethod": "GET",
          "id": "dfareporting.targetableRemarketingLists.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of targetable remarketing lists, possibly filtered. This method supports paging."
        }
      }
    },
    "conversions": {
      "methods": {
        "batchupdate": {
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "description": "Updates existing conversions.",
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/conversions/batchupdate",
          "flatPath": "userprofiles/{profileId}/conversions/batchupdate",
          "id": "dfareporting.conversions.batchupdate"
        },
        "batchinsert": {
          "description": "Inserts conversions.",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "flatPath": "userprofiles/{profileId}/conversions/batchinsert",
          "id": "dfareporting.conversions.batchinsert",
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/conversions/batchinsert"
        }
      }
    },
    "subaccounts": {
      "methods": {
        "patch": {
          "description": "Updates an existing subaccount. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.subaccounts.patch",
          "path": "userprofiles/{profileId}/subaccounts",
          "flatPath": "userprofiles/{profileId}/subaccounts",
          "httpMethod": "PATCH"
        },
        "update": {
          "description": "Updates an existing subaccount.",
          "id": "dfareporting.subaccounts.update",
          "flatPath": "userprofiles/{profileId}/subaccounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/subaccounts",
          "httpMethod": "PUT"
        },
        "list": {
          "path": "userprofiles/{profileId}/subaccounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/subaccounts",
          "httpMethod": "GET",
          "id": "dfareporting.subaccounts.list",
          "description": "Gets a list of subaccounts, possibly filtered. This method supports paging."
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/subaccounts/{id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one subaccount by ID.",
          "path": "userprofiles/{profileId}/subaccounts/{id}",
          "id": "dfareporting.subaccounts.get"
        },
        "insert": {
          "path": "userprofiles/{profileId}/subaccounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.subaccounts.insert",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/subaccounts",
          "description": "Inserts a new subaccount."
        }
      }
    },
    "countries": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{profileId}/countries",
          "id": "dfareporting.countries.list",
          "httpMethod": "GET",
          "description": "Retrieves a list of countries.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/countries"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one country by ID.",
          "path": "userprofiles/{profileId}/countries/{dartId}",
          "httpMethod": "GET",
          "id": "dfareporting.countries.get",
          "flatPath": "userprofiles/{profileId}/countries/{dartId}"
        }
      }
    },
    "remarketingListShares": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{profileId}/remarketingListShares/{remarketingListId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/remarketingListShares/{remarketingListId}",
          "description": "Gets one remarketing list share by remarketing list ID.",
          "id": "dfareporting.remarketingListShares.get"
        },
        "patch": {
          "description": "Updates an existing remarketing list share. This method supports patch semantics.",
          "id": "dfareporting.remarketingListShares.patch",
          "flatPath": "userprofiles/{profileId}/remarketingListShares",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "path": "userprofiles/{profileId}/remarketingListShares"
        },
        "update": {
          "flatPath": "userprofiles/{profileId}/remarketingListShares",
          "path": "userprofiles/{profileId}/remarketingListShares",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.remarketingListShares.update",
          "httpMethod": "PUT",
          "description": "Updates an existing remarketing list share."
        }
      }
    },
    "floodlightConfigurations": {
      "methods": {
        "update": {
          "description": "Updates an existing floodlight configuration.",
          "id": "dfareporting.floodlightConfigurations.update",
          "path": "userprofiles/{profileId}/floodlightConfigurations",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/floodlightConfigurations"
        },
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightConfigurations.get",
          "description": "Gets one floodlight configuration by ID.",
          "flatPath": "userprofiles/{profileId}/floodlightConfigurations/{id}",
          "path": "userprofiles/{profileId}/floodlightConfigurations/{id}"
        },
        "patch": {
          "httpMethod": "PATCH",
          "path": "userprofiles/{profileId}/floodlightConfigurations",
          "id": "dfareporting.floodlightConfigurations.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/floodlightConfigurations",
          "description": "Updates an existing floodlight configuration. This method supports patch semantics."
        },
        "list": {
          "description": "Retrieves a list of floodlight configurations, possibly filtered.",
          "path": "userprofiles/{profileId}/floodlightConfigurations",
          "httpMethod": "GET",
          "id": "dfareporting.floodlightConfigurations.list",
          "flatPath": "userprofiles/{profileId}/floodlightConfigurations",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "userRolePermissions": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/userRolePermissions/{id}",
          "description": "Gets one user role permission by ID.",
          "path": "userprofiles/{profileId}/userRolePermissions/{id}",
          "id": "dfareporting.userRolePermissions.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/userRolePermissions",
          "id": "dfareporting.userRolePermissions.list",
          "flatPath": "userprofiles/{profileId}/userRolePermissions",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets a list of user role permissions, possibly filtered."
        }
      }
    },
    "placements": {
      "methods": {
        "insert": {
          "description": "Inserts a new placement.",
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/placements",
          "flatPath": "userprofiles/{profileId}/placements",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placements.insert"
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/placements",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/placements",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of placements, possibly filtered. This method supports paging.",
          "id": "dfareporting.placements.list"
        },
        "update": {
          "httpMethod": "PUT",
          "id": "dfareporting.placements.update",
          "flatPath": "userprofiles/{profileId}/placements",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/placements",
          "description": "Updates an existing placement."
        },
        "get": {
          "id": "dfareporting.placements.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one placement by ID.",
          "flatPath": "userprofiles/{profileId}/placements/{id}",
          "path": "userprofiles/{profileId}/placements/{id}",
          "httpMethod": "GET"
        },
        "generatetags": {
          "flatPath": "userprofiles/{profileId}/placements/generatetags",
          "id": "dfareporting.placements.generatetags",
          "httpMethod": "POST",
          "description": "Generates tags for a placement.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/placements/generatetags"
        },
        "patch": {
          "description": "Updates an existing placement. This method supports patch semantics.",
          "flatPath": "userprofiles/{profileId}/placements",
          "path": "userprofiles/{profileId}/placements",
          "httpMethod": "PATCH",
          "id": "dfareporting.placements.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "sizes": {
      "methods": {
        "insert": {
          "path": "userprofiles/{profileId}/sizes",
          "flatPath": "userprofiles/{profileId}/sizes",
          "id": "dfareporting.sizes.insert",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new size."
        },
        "list": {
          "description": "Retrieves a list of sizes, possibly filtered. Retrieved sizes are globally unique and may include values not currently in use by your account. Due to this, the list of sizes returned by this method may differ from the list seen in the Trafficking UI.",
          "path": "userprofiles/{profileId}/sizes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.sizes.list",
          "flatPath": "userprofiles/{profileId}/sizes"
        },
        "get": {
          "description": "Gets one size by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/sizes/{id}",
          "path": "userprofiles/{profileId}/sizes/{id}",
          "httpMethod": "GET",
          "id": "dfareporting.sizes.get"
        }
      }
    },
    "metros": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "id": "dfareporting.metros.list",
          "path": "userprofiles/{profileId}/metros",
          "description": "Retrieves a list of metros.",
          "flatPath": "userprofiles/{profileId}/metros",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "cities": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/cities",
          "flatPath": "userprofiles/{profileId}/cities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.cities.list",
          "description": "Retrieves a list of cities, possibly filtered."
        }
      }
    },
    "platformTypes": {
      "methods": {
        "list": {
          "path": "userprofiles/{profileId}/platformTypes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/platformTypes",
          "id": "dfareporting.platformTypes.list",
          "description": "Retrieves a list of platform types."
        },
        "get": {
          "id": "dfareporting.platformTypes.get",
          "flatPath": "userprofiles/{profileId}/platformTypes/{id}",
          "path": "userprofiles/{profileId}/platformTypes/{id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one platform type by ID."
        }
      }
    },
    "accountPermissions": {
      "methods": {
        "get": {
          "description": "Gets one account permission by ID.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/accountPermissions/{id}",
          "path": "userprofiles/{profileId}/accountPermissions/{id}",
          "id": "dfareporting.accountPermissions.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "description": "Retrieves the list of account permissions.",
          "path": "userprofiles/{profileId}/accountPermissions",
          "id": "dfareporting.accountPermissions.list",
          "flatPath": "userprofiles/{profileId}/accountPermissions",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        }
      }
    },
    "languages": {
      "methods": {
        "list": {
          "description": "Retrieves a list of languages.",
          "id": "dfareporting.languages.list",
          "flatPath": "userprofiles/{profileId}/languages",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/languages",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "postalCodes": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{profileId}/postalCodes/{code}",
          "path": "userprofiles/{profileId}/postalCodes/{code}",
          "id": "dfareporting.postalCodes.get",
          "description": "Gets one postal code by ID.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "description": "Retrieves a list of postal codes.",
          "path": "userprofiles/{profileId}/postalCodes",
          "id": "dfareporting.postalCodes.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/postalCodes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "mobileApps": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/mobileApps/{id}",
          "flatPath": "userprofiles/{profileId}/mobileApps/{id}",
          "id": "dfareporting.mobileApps.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one mobile app by ID."
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves list of available mobile apps.",
          "path": "userprofiles/{profileId}/mobileApps",
          "flatPath": "userprofiles/{profileId}/mobileApps",
          "httpMethod": "GET",
          "id": "dfareporting.mobileApps.list"
        }
      }
    },
    "userRolePermissionGroups": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/userRolePermissionGroups/{id}",
          "id": "dfareporting.userRolePermissionGroups.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one user role permission group by ID.",
          "path": "userprofiles/{profileId}/userRolePermissionGroups/{id}"
        },
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/userRolePermissionGroups",
          "id": "dfareporting.userRolePermissionGroups.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets a list of all supported user role permission groups.",
          "flatPath": "userprofiles/{profileId}/userRolePermissionGroups"
        }
      }
    },
    "mobileCarriers": {
      "methods": {
        "list": {
          "id": "dfareporting.mobileCarriers.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/mobileCarriers",
          "description": "Retrieves a list of mobile carriers.",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/mobileCarriers"
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/mobileCarriers/{id}",
          "path": "userprofiles/{profileId}/mobileCarriers/{id}",
          "description": "Gets one mobile carrier by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.mobileCarriers.get"
        }
      }
    },
    "advertisers": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertisers.get",
          "flatPath": "userprofiles/{profileId}/advertisers/{id}",
          "httpMethod": "GET",
          "description": "Gets one advertiser by ID.",
          "path": "userprofiles/{profileId}/advertisers/{id}"
        },
        "patch": {
          "flatPath": "userprofiles/{profileId}/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertisers.patch",
          "path": "userprofiles/{profileId}/advertisers",
          "description": "Updates an existing advertiser. This method supports patch semantics.",
          "httpMethod": "PATCH"
        },
        "update": {
          "description": "Updates an existing advertiser.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertisers.update",
          "path": "userprofiles/{profileId}/advertisers",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{profileId}/advertisers"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/advertisers",
          "flatPath": "userprofiles/{profileId}/advertisers",
          "id": "dfareporting.advertisers.insert",
          "httpMethod": "POST",
          "description": "Inserts a new advertiser."
        },
        "list": {
          "httpMethod": "GET",
          "id": "dfareporting.advertisers.list",
          "description": "Retrieves a list of advertisers, possibly filtered. This method supports paging.",
          "path": "userprofiles/{profileId}/advertisers",
          "flatPath": "userprofiles/{profileId}/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "regions": {
      "methods": {
        "list": {
          "description": "Retrieves a list of regions.",
          "httpMethod": "GET",
          "id": "dfareporting.regions.list",
          "path": "userprofiles/{profileId}/regions",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/regions"
        }
      }
    },
    "accountActiveAdSummaries": {
      "methods": {
        "get": {
          "description": "Gets the account's active ad summary by account ID.",
          "flatPath": "userprofiles/{profileId}/accountActiveAdSummaries/{summaryAccountId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/accountActiveAdSummaries/{summaryAccountId}",
          "id": "dfareporting.accountActiveAdSummaries.get"
        }
      }
    },
    "operatingSystemVersions": {
      "methods": {
        "list": {
          "path": "userprofiles/{profileId}/operatingSystemVersions",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of operating system versions.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/operatingSystemVersions",
          "id": "dfareporting.operatingSystemVersions.list"
        },
        "get": {
          "description": "Gets one operating system version by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/operatingSystemVersions/{id}",
          "id": "dfareporting.operatingSystemVersions.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/operatingSystemVersions/{id}"
        }
      }
    },
    "customEvents": {
      "methods": {
        "batchinsert": {
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "description": "Inserts custom events.",
          "id": "dfareporting.customEvents.batchinsert",
          "flatPath": "userprofiles/{profileId}/customEvents/batchinsert",
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/customEvents/batchinsert"
        }
      }
    },
    "userProfiles": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userProfiles.get",
          "path": "userprofiles/{profileId}",
          "description": "Gets one user profile by ID.",
          "flatPath": "userprofiles/{profileId}"
        },
        "list": {
          "id": "dfareporting.userProfiles.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles",
          "description": "Retrieves list of user profiles for a user."
        }
      }
    },
    "placementGroups": {
      "methods": {
        "list": {
          "path": "userprofiles/{profileId}/placementGroups",
          "flatPath": "userprofiles/{profileId}/placementGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.placementGroups.list",
          "description": "Retrieves a list of placement groups, possibly filtered. This method supports paging."
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/placementGroups",
          "flatPath": "userprofiles/{profileId}/placementGroups",
          "id": "dfareporting.placementGroups.update",
          "httpMethod": "PUT",
          "description": "Updates an existing placement group."
        },
        "get": {
          "path": "userprofiles/{profileId}/placementGroups/{id}",
          "description": "Gets one placement group by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.placementGroups.get",
          "flatPath": "userprofiles/{profileId}/placementGroups/{id}"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/placementGroups",
          "id": "dfareporting.placementGroups.patch",
          "flatPath": "userprofiles/{profileId}/placementGroups",
          "description": "Updates an existing placement group. This method supports patch semantics.",
          "httpMethod": "PATCH"
        },
        "insert": {
          "id": "dfareporting.placementGroups.insert",
          "path": "userprofiles/{profileId}/placementGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/placementGroups",
          "description": "Inserts a new placement group.",
          "httpMethod": "POST"
        }
      }
    },
    "videoFormats": {
      "methods": {
        "get": {
          "id": "dfareporting.videoFormats.get",
          "path": "userprofiles/{profileId}/videoFormats/{id}",
          "description": "Gets one video format by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/videoFormats/{id}"
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/videoFormats",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/videoFormats",
          "httpMethod": "GET",
          "description": "Lists available video formats.",
          "id": "dfareporting.videoFormats.list"
        }
      }
    },
    "accountUserProfiles": {
      "methods": {
        "insert": {
          "path": "userprofiles/{profileId}/accountUserProfiles",
          "id": "dfareporting.accountUserProfiles.insert",
          "flatPath": "userprofiles/{profileId}/accountUserProfiles",
          "description": "Inserts a new account user profile.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST"
        },
        "get": {
          "httpMethod": "GET",
          "id": "dfareporting.accountUserProfiles.get",
          "description": "Gets one account user profile by ID.",
          "flatPath": "userprofiles/{profileId}/accountUserProfiles/{id}",
          "path": "userprofiles/{profileId}/accountUserProfiles/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "description": "Updates an existing account user profile. This method supports patch semantics.",
          "path": "userprofiles/{profileId}/accountUserProfiles",
          "id": "dfareporting.accountUserProfiles.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/accountUserProfiles",
          "httpMethod": "PATCH"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountUserProfiles.update",
          "description": "Updates an existing account user profile.",
          "flatPath": "userprofiles/{profileId}/accountUserProfiles",
          "httpMethod": "PUT",
          "path": "userprofiles/{profileId}/accountUserProfiles"
        },
        "list": {
          "path": "userprofiles/{profileId}/accountUserProfiles",
          "description": "Retrieves a list of account user profiles, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountUserProfiles.list",
          "flatPath": "userprofiles/{profileId}/accountUserProfiles"
        }
      }
    },
    "browsers": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/browsers",
          "description": "Retrieves a list of browsers.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/browsers",
          "id": "dfareporting.browsers.list"
        }
      }
    },
    "inventoryItems": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{profileId}/projects/{projectId}/inventoryItems",
          "id": "dfareporting.inventoryItems.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/projects/{projectId}/inventoryItems",
          "description": "Retrieves a list of inventory items, possibly filtered. This method supports paging.",
          "httpMethod": "GET"
        },
        "get": {
          "id": "dfareporting.inventoryItems.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/projects/{projectId}/inventoryItems/{id}",
          "description": "Gets one inventory item by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/projects/{projectId}/inventoryItems/{id}"
        }
      }
    },
    "files": {
      "methods": {
        "get": {
          "path": "reports/{reportId}/files/{fileId}",
          "description": "Retrieves a report file by its report ID and file ID. This method supports media download.",
          "id": "dfareporting.files.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "supportsMediaDownload": true,
          "flatPath": "reports/{reportId}/files/{fileId}",
          "httpMethod": "GET"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "flatPath": "userprofiles/{profileId}/files",
          "id": "dfareporting.files.list",
          "description": "Lists files for a user profile.",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/files"
        }
      }
    },
    "eventTags": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/eventTags",
          "id": "dfareporting.eventTags.list",
          "description": "Retrieves a list of event tags, possibly filtered.",
          "flatPath": "userprofiles/{profileId}/eventTags"
        },
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/eventTags/{id}",
          "id": "dfareporting.eventTags.get",
          "path": "userprofiles/{profileId}/eventTags/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one event tag by ID."
        },
        "patch": {
          "id": "dfareporting.eventTags.patch",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/eventTags",
          "description": "Updates an existing event tag. This method supports patch semantics.",
          "path": "userprofiles/{profileId}/eventTags"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/eventTags/{id}",
          "description": "Deletes an existing event tag.",
          "httpMethod": "DELETE",
          "id": "dfareporting.eventTags.delete",
          "flatPath": "userprofiles/{profileId}/eventTags/{id}"
        },
        "update": {
          "flatPath": "userprofiles/{profileId}/eventTags",
          "httpMethod": "PUT",
          "id": "dfareporting.eventTags.update",
          "description": "Updates an existing event tag.",
          "path": "userprofiles/{profileId}/eventTags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "id": "dfareporting.eventTags.insert",
          "description": "Inserts a new event tag.",
          "flatPath": "userprofiles/{profileId}/eventTags",
          "path": "userprofiles/{profileId}/eventTags"
        }
      }
    },
    "orderDocuments": {
      "methods": {
        "get": {
          "id": "dfareporting.orderDocuments.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one order document by ID.",
          "flatPath": "userprofiles/{profileId}/projects/{projectId}/orderDocuments/{id}",
          "path": "userprofiles/{profileId}/projects/{projectId}/orderDocuments/{id}",
          "httpMethod": "GET"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/projects/{projectId}/orderDocuments",
          "id": "dfareporting.orderDocuments.list",
          "description": "Retrieves a list of order documents, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/projects/{projectId}/orderDocuments"
        }
      }
    },
    "dynamicTargetingKeys": {
      "methods": {
        "insert": {
          "description": "Inserts a new dynamic targeting key. Keys must be created at the advertiser level before being assigned to the advertiser's ads, creatives, or placements. There is a maximum of 1000 keys per advertiser, out of which a maximum of 20 keys can be assigned per ad, creative, or placement.",
          "flatPath": "userprofiles/{profileId}/dynamicTargetingKeys",
          "path": "userprofiles/{profileId}/dynamicTargetingKeys",
          "id": "dfareporting.dynamicTargetingKeys.insert",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "description": "Retrieves a list of dynamic targeting keys.",
          "path": "userprofiles/{profileId}/dynamicTargetingKeys",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/dynamicTargetingKeys",
          "id": "dfareporting.dynamicTargetingKeys.list",
          "httpMethod": "GET"
        },
        "delete": {
          "id": "dfareporting.dynamicTargetingKeys.delete",
          "description": "Deletes an existing dynamic targeting key.",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/dynamicTargetingKeys/{objectId}",
          "path": "userprofiles/{profileId}/dynamicTargetingKeys/{objectId}"
        }
      }
    },
    "userRoles": {
      "methods": {
        "get": {
          "id": "dfareporting.userRoles.get",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/userRoles/{id}",
          "flatPath": "userprofiles/{profileId}/userRoles/{id}",
          "description": "Gets one user role by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{profileId}/userRoles",
          "description": "Updates an existing user role. This method supports patch semantics.",
          "path": "userprofiles/{profileId}/userRoles",
          "id": "dfareporting.userRoles.patch"
        },
        "insert": {
          "id": "dfareporting.userRoles.insert",
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/userRoles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new user role.",
          "flatPath": "userprofiles/{profileId}/userRoles"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/userRoles",
          "flatPath": "userprofiles/{profileId}/userRoles",
          "id": "dfareporting.userRoles.list",
          "description": "Retrieves a list of user roles, possibly filtered. This method supports paging."
        },
        "delete": {
          "flatPath": "userprofiles/{profileId}/userRoles/{id}",
          "id": "dfareporting.userRoles.delete",
          "httpMethod": "DELETE",
          "path": "userprofiles/{profileId}/userRoles/{id}",
          "description": "Deletes an existing user role.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "path": "userprofiles/{profileId}/userRoles",
          "description": "Updates an existing user role.",
          "id": "dfareporting.userRoles.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{profileId}/userRoles"
        }
      }
    },
    "ads": {
      "methods": {
        "patch": {
          "id": "dfareporting.ads.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{profileId}/ads",
          "path": "userprofiles/{profileId}/ads",
          "description": "Updates an existing ad. This method supports patch semantics."
        },
        "update": {
          "path": "userprofiles/{profileId}/ads",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{profileId}/ads",
          "description": "Updates an existing ad.",
          "id": "dfareporting.ads.update"
        },
        "list": {
          "description": "Retrieves a list of ads, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.ads.list",
          "path": "userprofiles/{profileId}/ads",
          "flatPath": "userprofiles/{profileId}/ads"
        },
        "insert": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new ad.",
          "id": "dfareporting.ads.insert",
          "path": "userprofiles/{profileId}/ads",
          "flatPath": "userprofiles/{profileId}/ads"
        },
        "get": {
          "httpMethod": "GET",
          "id": "dfareporting.ads.get",
          "description": "Gets one ad by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/ads/{id}",
          "path": "userprofiles/{profileId}/ads/{id}"
        }
      }
    },
    "creativeFieldValues": {
      "methods": {
        "update": {
          "httpMethod": "PUT",
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "flatPath": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing creative field value.",
          "id": "dfareporting.creativeFieldValues.update"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing creative field value. This method supports patch semantics.",
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "id": "dfareporting.creativeFieldValues.patch"
        },
        "insert": {
          "id": "dfareporting.creativeFieldValues.insert",
          "httpMethod": "POST",
          "description": "Inserts a new creative field value.",
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "flatPath": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "id": "dfareporting.creativeFieldValues.get",
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues/{id}",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one creative field value by ID."
        },
        "delete": {
          "flatPath": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues/{id}",
          "description": "Deletes an existing creative field value.",
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues/{id}",
          "id": "dfareporting.creativeFieldValues.delete",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "id": "dfareporting.creativeFieldValues.list",
          "description": "Retrieves a list of creative field values, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "creativeFields": {
      "methods": {
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFields.patch",
          "path": "userprofiles/{profileId}/creativeFields",
          "httpMethod": "PATCH",
          "description": "Updates an existing creative field. This method supports patch semantics.",
          "flatPath": "userprofiles/{profileId}/creativeFields"
        },
        "get": {
          "id": "dfareporting.creativeFields.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/creativeFields/{id}",
          "description": "Gets one creative field by ID.",
          "flatPath": "userprofiles/{profileId}/creativeFields/{id}",
          "httpMethod": "GET"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/creativeFields",
          "description": "Inserts a new creative field.",
          "id": "dfareporting.creativeFields.insert",
          "path": "userprofiles/{profileId}/creativeFields"
        },
        "list": {
          "id": "dfareporting.creativeFields.list",
          "flatPath": "userprofiles/{profileId}/creativeFields",
          "path": "userprofiles/{profileId}/creativeFields",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of creative fields, possibly filtered. This method supports paging.",
          "httpMethod": "GET"
        },
        "update": {
          "description": "Updates an existing creative field.",
          "path": "userprofiles/{profileId}/creativeFields",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFields.update",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{profileId}/creativeFields"
        },
        "delete": {
          "id": "dfareporting.creativeFields.delete",
          "description": "Deletes an existing creative field.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/creativeFields/{id}",
          "path": "userprofiles/{profileId}/creativeFields/{id}",
          "httpMethod": "DELETE"
        }
      }
    },
    "advertiserGroups": {
      "methods": {
        "delete": {
          "path": "userprofiles/{profileId}/advertiserGroups/{id}",
          "description": "Deletes an existing advertiser group.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserGroups.delete",
          "httpMethod": "DELETE",
          "flatPath": "userprofiles/{profileId}/advertiserGroups/{id}"
        },
        "update": {
          "httpMethod": "PUT",
          "description": "Updates an existing advertiser group.",
          "path": "userprofiles/{profileId}/advertiserGroups",
          "flatPath": "userprofiles/{profileId}/advertiserGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserGroups.update"
        },
        "patch": {
          "description": "Updates an existing advertiser group. This method supports patch semantics.",
          "flatPath": "userprofiles/{profileId}/advertiserGroups",
          "httpMethod": "PATCH",
          "id": "dfareporting.advertiserGroups.patch",
          "path": "userprofiles/{profileId}/advertiserGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserGroups.list",
          "flatPath": "userprofiles/{profileId}/advertiserGroups",
          "httpMethod": "GET",
          "description": "Retrieves a list of advertiser groups, possibly filtered. This method supports paging.",
          "path": "userprofiles/{profileId}/advertiserGroups"
        },
        "insert": {
          "path": "userprofiles/{profileId}/advertiserGroups",
          "flatPath": "userprofiles/{profileId}/advertiserGroups",
          "httpMethod": "POST",
          "description": "Inserts a new advertiser group.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserGroups.insert"
        },
        "get": {
          "httpMethod": "GET",
          "description": "Gets one advertiser group by ID.",
          "id": "dfareporting.advertiserGroups.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/advertiserGroups/{id}",
          "flatPath": "userprofiles/{profileId}/advertiserGroups/{id}"
        }
      }
    },
    "creatives": {
      "methods": {
        "update": {
          "description": "Updates an existing creative.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "path": "userprofiles/{profileId}/creatives",
          "flatPath": "userprofiles/{profileId}/creatives",
          "id": "dfareporting.creatives.update"
        },
        "insert": {
          "path": "userprofiles/{profileId}/creatives",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creatives.insert",
          "description": "Inserts a new creative.",
          "flatPath": "userprofiles/{profileId}/creatives"
        },
        "list": {
          "path": "userprofiles/{profileId}/creatives",
          "description": "Retrieves a list of creatives, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{profileId}/creatives",
          "id": "dfareporting.creatives.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        },
        "patch": {
          "httpMethod": "PATCH",
          "description": "Updates an existing creative. This method supports patch semantics.",
          "path": "userprofiles/{profileId}/creatives",
          "flatPath": "userprofiles/{profileId}/creatives",
          "id": "dfareporting.creatives.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "description": "Gets one creative by ID.",
          "path": "userprofiles/{profileId}/creatives/{id}",
          "id": "dfareporting.creatives.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/creatives/{id}",
          "httpMethod": "GET"
        }
      }
    },
    "remarketingLists": {
      "methods": {
        "update": {
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{profileId}/remarketingLists",
          "path": "userprofiles/{profileId}/remarketingLists",
          "description": "Updates an existing remarketing list.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.remarketingLists.update"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of remarketing lists, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{profileId}/remarketingLists",
          "httpMethod": "GET",
          "id": "dfareporting.remarketingLists.list",
          "path": "userprofiles/{profileId}/remarketingLists"
        },
        "insert": {
          "id": "dfareporting.remarketingLists.insert",
          "description": "Inserts a new remarketing list.",
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/remarketingLists",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/remarketingLists"
        },
        "patch": {
          "flatPath": "userprofiles/{profileId}/remarketingLists",
          "httpMethod": "PATCH",
          "description": "Updates an existing remarketing list. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.remarketingLists.patch",
          "path": "userprofiles/{profileId}/remarketingLists"
        },
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/remarketingLists/{id}",
          "id": "dfareporting.remarketingLists.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/remarketingLists/{id}",
          "description": "Gets one remarketing list by ID."
        }
      }
    },
    "floodlightActivities": {
      "methods": {
        "generatetag": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Generates a tag for a floodlight activity.",
          "path": "userprofiles/{profileId}/floodlightActivities/generatetag",
          "httpMethod": "POST",
          "id": "dfareporting.floodlightActivities.generatetag",
          "flatPath": "userprofiles/{profileId}/floodlightActivities/generatetag"
        },
        "list": {
          "path": "userprofiles/{profileId}/floodlightActivities",
          "httpMethod": "GET",
          "description": "Retrieves a list of floodlight activities, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{profileId}/floodlightActivities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivities.list"
        },
        "update": {
          "description": "Updates an existing floodlight activity.",
          "path": "userprofiles/{profileId}/floodlightActivities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "id": "dfareporting.floodlightActivities.update",
          "flatPath": "userprofiles/{profileId}/floodlightActivities"
        },
        "delete": {
          "flatPath": "userprofiles/{profileId}/floodlightActivities/{id}",
          "description": "Deletes an existing floodlight activity.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/floodlightActivities/{id}",
          "httpMethod": "DELETE",
          "id": "dfareporting.floodlightActivities.delete"
        },
        "insert": {
          "path": "userprofiles/{profileId}/floodlightActivities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivities.insert",
          "description": "Inserts a new floodlight activity.",
          "flatPath": "userprofiles/{profileId}/floodlightActivities",
          "httpMethod": "POST"
        },
        "get": {
          "id": "dfareporting.floodlightActivities.get",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/floodlightActivities/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one floodlight activity by ID.",
          "flatPath": "userprofiles/{profileId}/floodlightActivities/{id}"
        },
        "patch": {
          "id": "dfareporting.floodlightActivities.patch",
          "path": "userprofiles/{profileId}/floodlightActivities",
          "flatPath": "userprofiles/{profileId}/floodlightActivities",
          "description": "Updates an existing floodlight activity. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "accountPermissionGroups": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "description": "Gets one account permission group by ID.",
          "id": "dfareporting.accountPermissionGroups.get",
          "flatPath": "userprofiles/{profileId}/accountPermissionGroups/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/accountPermissionGroups/{id}"
        },
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/accountPermissionGroups",
          "flatPath": "userprofiles/{profileId}/accountPermissionGroups",
          "id": "dfareporting.accountPermissionGroups.list",
          "description": "Retrieves the list of account permission groups.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "sites": {
      "methods": {
        "patch": {
          "flatPath": "userprofiles/{profileId}/sites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "description": "Updates an existing site. This method supports patch semantics.",
          "path": "userprofiles/{profileId}/sites",
          "id": "dfareporting.sites.patch"
        },
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves a list of sites, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/sites",
          "path": "userprofiles/{profileId}/sites",
          "id": "dfareporting.sites.list"
        },
        "update": {
          "path": "userprofiles/{profileId}/sites",
          "flatPath": "userprofiles/{profileId}/sites",
          "description": "Updates an existing site.",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.sites.update"
        },
        "get": {
          "id": "dfareporting.sites.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/sites/{id}",
          "description": "Gets one site by ID.",
          "flatPath": "userprofiles/{profileId}/sites/{id}"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/sites",
          "description": "Inserts a new site.",
          "flatPath": "userprofiles/{profileId}/sites",
          "id": "dfareporting.sites.insert"
        }
      }
    },
    "targetingTemplates": {
      "methods": {
        "update": {
          "description": "Updates an existing targeting template.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/targetingTemplates",
          "path": "userprofiles/{profileId}/targetingTemplates",
          "httpMethod": "PUT",
          "id": "dfareporting.targetingTemplates.update"
        },
        "insert": {
          "path": "userprofiles/{profileId}/targetingTemplates",
          "id": "dfareporting.targetingTemplates.insert",
          "description": "Inserts a new targeting template.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/targetingTemplates",
          "httpMethod": "POST"
        },
        "patch": {
          "description": "Updates an existing targeting template. This method supports patch semantics.",
          "flatPath": "userprofiles/{profileId}/targetingTemplates",
          "id": "dfareporting.targetingTemplates.patch",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/targetingTemplates"
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/targetingTemplates",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/targetingTemplates",
          "httpMethod": "GET",
          "description": "Retrieves a list of targeting templates, optionally filtered. This method supports paging.",
          "id": "dfareporting.targetingTemplates.list"
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/targetingTemplates/{id}",
          "httpMethod": "GET",
          "id": "dfareporting.targetingTemplates.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/targetingTemplates/{id}",
          "description": "Gets one targeting template by ID."
        }
      }
    },
    "creativeAssets": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "supportsMediaUpload": true,
          "id": "dfareporting.creativeAssets.insert",
          "description": "Inserts a new creative asset.",
          "path": "userprofiles/{profileId}/creativeAssets/{advertiserId}/creativeAssets",
          "flatPath": "userprofiles/{profileId}/creativeAssets/{advertiserId}/creativeAssets"
        }
      }
    },
    "accounts": {
      "methods": {
        "get": {
          "id": "dfareporting.accounts.get",
          "description": "Gets one account by ID.",
          "path": "userprofiles/{profileId}/accounts/{id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/accounts/{id}"
        },
        "list": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves the list of accounts, possibly filtered. This method supports paging.",
          "path": "userprofiles/{profileId}/accounts",
          "id": "dfareporting.accounts.list",
          "flatPath": "userprofiles/{profileId}/accounts"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/accounts",
          "path": "userprofiles/{profileId}/accounts",
          "description": "Updates an existing account. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "id": "dfareporting.accounts.patch"
        },
        "update": {
          "path": "userprofiles/{profileId}/accounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/accounts",
          "description": "Updates an existing account.",
          "httpMethod": "PUT",
          "id": "dfareporting.accounts.update"
        }
      }
    },
    "connectionTypes": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.connectionTypes.get",
          "description": "Gets one connection type by ID.",
          "flatPath": "userprofiles/{profileId}/connectionTypes/{id}",
          "path": "userprofiles/{profileId}/connectionTypes/{id}",
          "httpMethod": "GET"
        },
        "list": {
          "path": "userprofiles/{profileId}/connectionTypes",
          "id": "dfareporting.connectionTypes.list",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/connectionTypes",
          "description": "Retrieves a list of connection types."
        }
      }
    },
    "reports": {
      "resources": {
        "compatibleFields": {
          "methods": {
            "query": {
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "httpMethod": "POST",
              "flatPath": "userprofiles/{profileId}/reports/compatiblefields/query",
              "description": "Returns the fields that are compatible to be selected in the respective sections of a report criteria, given the fields already selected in the input report and user permissions.",
              "path": "userprofiles/{profileId}/reports/compatiblefields/query",
              "id": "dfareporting.reports.compatibleFields.query"
            }
          }
        },
        "files": {
          "methods": {
            "list": {
              "id": "dfareporting.reports.files.list",
              "description": "Lists files for a report.",
              "httpMethod": "GET",
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "path": "userprofiles/{profileId}/reports/{reportId}/files"
            },
            "get": {
              "supportsMediaDownload": true,
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "id": "dfareporting.reports.files.get",
              "description": "Retrieves a report file by its report ID and file ID. This method supports media download.",
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}",
              "httpMethod": "GET",
              "path": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}"
            }
          }
        }
      },
      "methods": {
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves list of reports.",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "flatPath": "userprofiles/{profileId}/reports",
          "path": "userprofiles/{profileId}/reports",
          "id": "dfareporting.reports.list"
        },
        "run": {
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "description": "Runs a report.",
          "path": "userprofiles/{profileId}/reports/{reportId}/run",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}/run",
          "httpMethod": "POST",
          "id": "dfareporting.reports.run"
        },
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "id": "dfareporting.reports.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "description": "Retrieves a report by its ID."
        },
        "insert": {
          "flatPath": "userprofiles/{profileId}/reports",
          "httpMethod": "POST",
          "id": "dfareporting.reports.insert",
          "description": "Creates a report.",
          "path": "userprofiles/{profileId}/reports",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ]
        },
        "update": {
          "id": "dfareporting.reports.update",
          "description": "Updates a report.",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "PUT",
          "path": "userprofiles/{profileId}/reports/{reportId}"
        },
        "patch": {
          "id": "dfareporting.reports.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "PATCH",
          "description": "Updates an existing report. This method supports patch semantics."
        },
        "delete": {
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "DELETE",
          "description": "Deletes a report by its ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.reports.delete"
        }
      }
    },
    "directorySites": {
      "methods": {
        "insert": {
          "flatPath": "userprofiles/{profileId}/directorySites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.directorySites.insert",
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/directorySites",
          "description": "Inserts a new directory site."
        },
        "get": {
          "id": "dfareporting.directorySites.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one directory site by ID.",
          "flatPath": "userprofiles/{profileId}/directorySites/{id}",
          "path": "userprofiles/{profileId}/directorySites/{id}"
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/directorySites",
          "description": "Retrieves a list of directory sites, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/directorySites",
          "id": "dfareporting.directorySites.list"
        }
      }
    },
    "advertiserLandingPages": {
      "methods": {
        "list": {
          "id": "dfareporting.advertiserLandingPages.list",
          "httpMethod": "GET",
          "description": "Retrieves a list of landing pages.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/advertiserLandingPages",
          "path": "userprofiles/{profileId}/advertiserLandingPages"
        },
        "update": {
          "description": "Updates an existing landing page.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/advertiserLandingPages",
          "flatPath": "userprofiles/{profileId}/advertiserLandingPages",
          "id": "dfareporting.advertiserLandingPages.update",
          "httpMethod": "PUT"
        },
        "insert": {
          "description": "Inserts a new landing page.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserLandingPages.insert",
          "path": "userprofiles/{profileId}/advertiserLandingPages",
          "flatPath": "userprofiles/{profileId}/advertiserLandingPages"
        },
        "patch": {
          "description": "Updates an existing advertiser landing page. This method supports patch semantics.",
          "flatPath": "userprofiles/{profileId}/advertiserLandingPages",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/advertiserLandingPages",
          "id": "dfareporting.advertiserLandingPages.patch"
        },
        "get": {
          "path": "userprofiles/{profileId}/advertiserLandingPages/{id}",
          "httpMethod": "GET",
          "id": "dfareporting.advertiserLandingPages.get",
          "description": "Gets one landing page by ID.",
          "flatPath": "userprofiles/{profileId}/advertiserLandingPages/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "contentCategories": {
      "methods": {
        "list": {
          "id": "dfareporting.contentCategories.list",
          "flatPath": "userprofiles/{profileId}/contentCategories",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of content categories, possibly filtered. This method supports paging.",
          "path": "userprofiles/{profileId}/contentCategories"
        },
        "delete": {
          "id": "dfareporting.contentCategories.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/contentCategories/{id}",
          "httpMethod": "DELETE",
          "description": "Deletes an existing content category.",
          "path": "userprofiles/{profileId}/contentCategories/{id}"
        },
        "update": {
          "httpMethod": "PUT",
          "id": "dfareporting.contentCategories.update",
          "path": "userprofiles/{profileId}/contentCategories",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/contentCategories",
          "description": "Updates an existing content category."
        },
        "insert": {
          "flatPath": "userprofiles/{profileId}/contentCategories",
          "description": "Inserts a new content category.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/contentCategories",
          "id": "dfareporting.contentCategories.insert"
        },
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/contentCategories/{id}",
          "description": "Gets one content category by ID.",
          "id": "dfareporting.contentCategories.get",
          "path": "userprofiles/{profileId}/contentCategories/{id}"
        },
        "patch": {
          "id": "dfareporting.contentCategories.patch",
          "path": "userprofiles/{profileId}/contentCategories",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{profileId}/contentCategories",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing content category. This method supports patch semantics."
        }
      }
    },
    "placementStrategies": {
      "methods": {
        "list": {
          "description": "Retrieves a list of placement strategies, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementStrategies.list",
          "path": "userprofiles/{profileId}/placementStrategies",
          "flatPath": "userprofiles/{profileId}/placementStrategies"
        },
        "delete": {
          "path": "userprofiles/{profileId}/placementStrategies/{id}",
          "flatPath": "userprofiles/{profileId}/placementStrategies/{id}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing placement strategy.",
          "id": "dfareporting.placementStrategies.delete"
        },
        "patch": {
          "description": "Updates an existing placement strategy. This method supports patch semantics.",
          "path": "userprofiles/{profileId}/placementStrategies",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/placementStrategies",
          "id": "dfareporting.placementStrategies.patch"
        },
        "get": {
          "path": "userprofiles/{profileId}/placementStrategies/{id}",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/placementStrategies/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementStrategies.get",
          "description": "Gets one placement strategy by ID."
        },
        "update": {
          "id": "dfareporting.placementStrategies.update",
          "httpMethod": "PUT",
          "path": "userprofiles/{profileId}/placementStrategies",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/placementStrategies",
          "description": "Updates an existing placement strategy."
        },
        "insert": {
          "description": "Inserts a new placement strategy.",
          "path": "userprofiles/{profileId}/placementStrategies",
          "flatPath": "userprofiles/{profileId}/placementStrategies",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementStrategies.insert",
          "httpMethod": "POST"
        }
      }
    },
    "projects": {
      "methods": {
        "get": {
          "id": "dfareporting.projects.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/projects/{id}",
          "description": "Gets one project by ID.",
          "path": "userprofiles/{profileId}/projects/{id}",
          "httpMethod": "GET"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/projects",
          "path": "userprofiles/{profileId}/projects",
          "httpMethod": "GET",
          "description": "Retrieves a list of projects, possibly filtered. This method supports paging .",
          "id": "dfareporting.projects.list"
        }
      }
    },
    "creativeGroups": {
      "methods": {
        "patch": {
          "description": "Updates an existing creative group. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/creativeGroups",
          "id": "dfareporting.creativeGroups.patch",
          "flatPath": "userprofiles/{profileId}/creativeGroups",
          "httpMethod": "PATCH"
        },
        "update": {
          "id": "dfareporting.creativeGroups.update",
          "httpMethod": "PUT",
          "path": "userprofiles/{profileId}/creativeGroups",
          "flatPath": "userprofiles/{profileId}/creativeGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing creative group."
        },
        "insert": {
          "flatPath": "userprofiles/{profileId}/creativeGroups",
          "path": "userprofiles/{profileId}/creativeGroups",
          "id": "dfareporting.creativeGroups.insert",
          "description": "Inserts a new creative group.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST"
        },
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/creativeGroups/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeGroups.get",
          "path": "userprofiles/{profileId}/creativeGroups/{id}",
          "description": "Gets one creative group by ID."
        },
        "list": {
          "path": "userprofiles/{profileId}/creativeGroups",
          "httpMethod": "GET",
          "description": "Retrieves a list of creative groups, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/creativeGroups",
          "id": "dfareporting.creativeGroups.list"
        }
      }
    },
    "changeLogs": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.changeLogs.get",
          "flatPath": "userprofiles/{profileId}/changeLogs/{id}",
          "description": "Gets one change log by ID.",
          "path": "userprofiles/{profileId}/changeLogs/{id}"
        },
        "list": {
          "id": "dfareporting.changeLogs.list",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/changeLogs",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/changeLogs",
          "description": "Retrieves a list of change logs. This method supports paging."
        }
      }
    },
    "campaignCreativeAssociations": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/campaigns/{campaignId}/campaignCreativeAssociations",
          "id": "dfareporting.campaignCreativeAssociations.list",
          "description": "Retrieves the list of creative IDs associated with the specified campaign. This method supports paging.",
          "path": "userprofiles/{profileId}/campaigns/{campaignId}/campaignCreativeAssociations",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "flatPath": "userprofiles/{profileId}/campaigns/{campaignId}/campaignCreativeAssociations",
          "id": "dfareporting.campaignCreativeAssociations.insert",
          "description": "Associates a creative with the specified campaign. This method creates a default ad with dimensions matching the creative in the campaign if such a default ad does not exist already.",
          "path": "userprofiles/{profileId}/campaigns/{campaignId}/campaignCreativeAssociations",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "operatingSystems": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.operatingSystems.list",
          "description": "Retrieves a list of operating systems.",
          "path": "userprofiles/{profileId}/operatingSystems",
          "flatPath": "userprofiles/{profileId}/operatingSystems"
        },
        "get": {
          "description": "Gets one operating system by DART ID.",
          "path": "userprofiles/{profileId}/operatingSystems/{dartId}",
          "id": "dfareporting.operatingSystems.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/operatingSystems/{dartId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "dimensionValues": {
      "methods": {
        "query": {
          "description": "Retrieves list of report dimension values for a list of filters.",
          "flatPath": "userprofiles/{profileId}/dimensionvalues/query",
          "id": "dfareporting.dimensionValues.query",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "path": "userprofiles/{profileId}/dimensionvalues/query"
        }
      }
    }
  }
}
