{
  "rootUrl": "https://displayvideo.googleapis.com/",
  "ownerDomain": "google.com",
  "version_module": true,
  "name": "displayvideo",
  "batchPath": "batch",
  "mtlsRootUrl": "https://displayvideo.mtls.googleapis.com/",
  "baseUrl": "https://displayvideo.googleapis.com/",
  "documentationLink": "https://developers.google.com/display-video/",
  "revision": "20210218",
  "description": "Display & Video 360 API allows users to manage and create campaigns and reports.",
  "kind": "discovery#restDescription",
  "protocol": "rest",
  "servicePath": "",
  "discoveryVersion": "v1",
  "basePath": "",
  "version": "v1",
  "resources": {
    "inventorySourceGroups": {
      "methods": {
        "list": {
          "path": "v1/inventorySourceGroups",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Lists inventory source groups that are accessible to the current user. The order is defined by the order_by parameter.",
          "id": "displayvideo.inventorySourceGroups.list",
          "flatPath": "v1/inventorySourceGroups"
        },
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.inventorySourceGroups.get",
          "path": "v1/inventorySourceGroups/{+inventorySourceGroupId}",
          "flatPath": "v1/inventorySourceGroups/{inventorySourceGroupsId}",
          "description": "Gets an inventory source group."
        },
        "create": {
          "id": "displayvideo.inventorySourceGroups.create",
          "path": "v1/inventorySourceGroups",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v1/inventorySourceGroups",
          "description": "Creates a new inventory source group. Returns the newly created inventory source group if successful.",
          "httpMethod": "POST"
        },
        "patch": {
          "id": "displayvideo.inventorySourceGroups.patch",
          "httpMethod": "PATCH",
          "flatPath": "v1/inventorySourceGroups/{inventorySourceGroupId}",
          "description": "Updates an inventory source group. Returns the updated inventory source group if successful.",
          "path": "v1/inventorySourceGroups/{inventorySourceGroupId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "delete": {
          "flatPath": "v1/inventorySourceGroups/{inventorySourceGroupsId}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.inventorySourceGroups.delete",
          "path": "v1/inventorySourceGroups/{+inventorySourceGroupId}",
          "description": "Deletes an inventory source group."
        }
      },
      "resources": {
        "assignedInventorySources": {
          "methods": {
            "bulkEdit": {
              "flatPath": "v1/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources:bulkEdit",
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.bulkEdit",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "POST",
              "description": "Bulk edits multiple assignments between inventory sources and a single inventory source group. The operation will delete the assigned inventory sources provided in BulkEditAssignedInventorySourcesRequest.deleted_assigned_inventory_sources and then create the assigned inventory sources provided in BulkEditAssignedInventorySourcesRequest.created_assigned_inventory_sources.",
              "path": "v1/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources:bulkEdit"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "path": "v1/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources",
              "flatPath": "v1/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources",
              "description": "Lists inventory sources assigned to an inventory source group.",
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.list"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.create",
              "flatPath": "v1/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources",
              "description": "Creates an assignment between an inventory source and an inventory source group.",
              "path": "v1/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources",
              "httpMethod": "POST"
            },
            "delete": {
              "flatPath": "v1/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources/{assignedInventorySourcesId}",
              "httpMethod": "DELETE",
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.delete",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v1/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources/{+assignedInventorySourceId}",
              "description": "Deletes the assignment between an inventory source and an inventory source group."
            }
          }
        }
      }
    },
    "firstAndThirdPartyAudiences": {
      "methods": {
        "get": {
          "id": "displayvideo.firstAndThirdPartyAudiences.get",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v1/firstAndThirdPartyAudiences/{+firstAndThirdPartyAudienceId}",
          "httpMethod": "GET",
          "description": "Gets a first and third party audience.",
          "flatPath": "v1/firstAndThirdPartyAudiences/{firstAndThirdPartyAudiencesId}"
        },
        "list": {
          "description": "Lists first and third party audiences. The order is defined by the order_by parameter.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.firstAndThirdPartyAudiences.list",
          "path": "v1/firstAndThirdPartyAudiences",
          "httpMethod": "GET",
          "flatPath": "v1/firstAndThirdPartyAudiences"
        }
      }
    },
    "sdfdownloadtasks": {
      "methods": {
        "create": {
          "path": "v1/sdfdownloadtasks",
          "flatPath": "v1/sdfdownloadtasks",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.sdfdownloadtasks.create",
          "description": "Creates an SDF Download Task. Returns an Operation. An SDF Download Task is a long-running, asynchronous operation. The metadata type of this operation is SdfDownloadTaskMetadata. If the request is successful, the response type of the operation is SdfDownloadTask. The response will not include the download files, which must be retrieved with media.download. The state of operation can be retrieved with sdfdownloadtask.operations.get. Any errors can be found in the error.[...]"
        }
      },
      "resources": {
        "operations": {
          "methods": {
            "get": {
              "path": "v1/{+name}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/doubleclickbidmanager"
              ],
              "description": "Gets the latest state of an asynchronous SDF download task operation. Clients should poll this method at intervals of 30 seconds.",
              "flatPath": "v1/sdfdownloadtasks/operations/{operationsId}",
              "id": "displayvideo.sdfdownloadtasks.operations.get"
            }
          }
        }
      }
    },
    "advertisers": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.advertisers.get",
          "flatPath": "v1/advertisers/{advertisersId}",
          "description": "Gets an advertiser.",
          "path": "v1/advertisers/{+advertiserId}",
          "httpMethod": "GET"
        },
        "bulkEditAdvertiserAssignedTargetingOptions": {
          "description": "Bulk edits targeting options under a single advertiser. The operation will delete the assigned targeting options provided in BulkEditAdvertiserAssignedTargetingOptionsRequest.delete_requests and then create the assigned targeting options provided in BulkEditAdvertiserAssignedTargetingOptionsRequest.create_requests .",
          "flatPath": "v1/advertisers/{advertisersId}:bulkEditAdvertiserAssignedTargetingOptions",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.advertisers.bulkEditAdvertiserAssignedTargetingOptions",
          "httpMethod": "POST",
          "path": "v1/advertisers/{+advertiserId}:bulkEditAdvertiserAssignedTargetingOptions"
        },
        "bulkListAdvertiserAssignedTargetingOptions": {
          "path": "v1/advertisers/{+advertiserId}:bulkListAdvertiserAssignedTargetingOptions",
          "flatPath": "v1/advertisers/{advertisersId}:bulkListAdvertiserAssignedTargetingOptions",
          "httpMethod": "GET",
          "id": "displayvideo.advertisers.bulkListAdvertiserAssignedTargetingOptions",
          "description": "Lists assigned targeting options of an advertiser across targeting types.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "audit": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Audits an advertiser. Returns the counts of used entities per resource type under the advertiser provided. Used entities count towards their respective resource limit. See https://support.google.com/displayvideo/answer/6071450.",
          "flatPath": "v1/advertisers/{advertisersId}:audit",
          "path": "v1/advertisers/{+advertiserId}:audit",
          "id": "displayvideo.advertisers.audit"
        },
        "list": {
          "description": "Lists advertisers that are accessible to the current user. The order is defined by the order_by parameter. A single partner_id is required. Cross-partner listing is not supported.",
          "path": "v1/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v1/advertisers",
          "httpMethod": "GET",
          "id": "displayvideo.advertisers.list"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v1/advertisers/{+advertiserId}",
          "description": "Updates an existing advertiser. Returns the updated advertiser if successful.",
          "flatPath": "v1/advertisers/{advertisersId}",
          "httpMethod": "PATCH",
          "id": "displayvideo.advertisers.patch"
        },
        "create": {
          "flatPath": "v1/advertisers",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v1/advertisers",
          "id": "displayvideo.advertisers.create",
          "description": "Creates a new advertiser. Returns the newly created advertiser if successful. This method can take up to 180 seconds to complete."
        },
        "delete": {
          "flatPath": "v1/advertisers/{advertisersId}",
          "path": "v1/advertisers/{+advertiserId}",
          "description": "Deletes an advertiser. Deleting an advertiser will delete all of its child resources, for example, campaigns, insertion orders and line items. A deleted advertiser cannot be recovered.",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.advertisers.delete"
        }
      },
      "resources": {
        "manualTriggers": {
          "methods": {
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Updates a manual trigger. Returns the updated manual trigger if successful.",
              "id": "displayvideo.advertisers.manualTriggers.patch",
              "path": "v1/advertisers/{+advertiserId}/manualTriggers/{+triggerId}",
              "httpMethod": "PATCH",
              "flatPath": "v1/advertisers/{advertisersId}/manualTriggers/{manualTriggersId}"
            },
            "activate": {
              "path": "v1/advertisers/{+advertiserId}/manualTriggers/{+triggerId}:activate",
              "httpMethod": "POST",
              "flatPath": "v1/advertisers/{advertisersId}/manualTriggers/{manualTriggersId}:activate",
              "description": "Activates a manual trigger. Each activation of the manual trigger must be at least 5 minutes apart, otherwise an error will be returned.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.manualTriggers.activate"
            },
            "create": {
              "httpMethod": "POST",
              "description": "Creates a new manual trigger. Returns the newly created manual trigger if successful.",
              "path": "v1/advertisers/{+advertiserId}/manualTriggers",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.manualTriggers.create",
              "flatPath": "v1/advertisers/{advertisersId}/manualTriggers"
            },
            "deactivate": {
              "httpMethod": "POST",
              "description": "Deactivates a manual trigger.",
              "path": "v1/advertisers/{+advertiserId}/manualTriggers/{+triggerId}:deactivate",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.manualTriggers.deactivate",
              "flatPath": "v1/advertisers/{advertisersId}/manualTriggers/{manualTriggersId}:deactivate"
            },
            "get": {
              "id": "displayvideo.advertisers.manualTriggers.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "path": "v1/advertisers/{+advertiserId}/manualTriggers/{+triggerId}",
              "description": "Gets a manual trigger.",
              "flatPath": "v1/advertisers/{advertisersId}/manualTriggers/{manualTriggersId}"
            },
            "list": {
              "flatPath": "v1/advertisers/{advertisersId}/manualTriggers",
              "httpMethod": "GET",
              "description": "Lists manual triggers that are accessible to the current user for a given advertiser ID. The order is defined by the order_by parameter. A single advertiser_id is required.",
              "path": "v1/advertisers/{+advertiserId}/manualTriggers",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.manualTriggers.list"
            }
          }
        },
        "creatives": {
          "methods": {
            "patch": {
              "path": "v1/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "id": "displayvideo.advertisers.creatives.patch",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Updates an existing creative. Returns the updated creative if successful.",
              "flatPath": "v1/advertisers/{advertisersId}/creatives/{creativesId}"
            },
            "get": {
              "httpMethod": "GET",
              "description": "Gets a creative.",
              "id": "displayvideo.advertisers.creatives.get",
              "flatPath": "v1/advertisers/{advertisersId}/creatives/{creativesId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v1/advertisers/{+advertiserId}/creatives/{+creativeId}"
            },
            "list": {
              "flatPath": "v1/advertisers/{advertisersId}/creatives",
              "description": "Lists creatives in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, creatives with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "path": "v1/advertisers/{+advertiserId}/creatives",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.creatives.list"
            },
            "create": {
              "path": "v1/advertisers/{+advertiserId}/creatives",
              "httpMethod": "POST",
              "flatPath": "v1/advertisers/{advertisersId}/creatives",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.creatives.create",
              "description": "Creates a new creative. Returns the newly created creative if successful."
            },
            "delete": {
              "httpMethod": "DELETE",
              "path": "v1/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "description": "Deletes a creative. Returns error code `NOT_FOUND` if the creative does not exist. The creative should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, before it can be deleted.",
              "id": "displayvideo.advertisers.creatives.delete",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v1/advertisers/{advertisersId}/creatives/{creativesId}"
            }
          }
        },
        "channels": {
          "resources": {
            "sites": {
              "methods": {
                "list": {
                  "path": "v1/advertisers/{+advertiserId}/channels/{+channelId}/sites",
                  "flatPath": "v1/advertisers/{advertisersId}/channels/{channelsId}/sites",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Lists sites in a channel.",
                  "httpMethod": "GET",
                  "id": "displayvideo.advertisers.channels.sites.list"
                },
                "delete": {
                  "flatPath": "v1/advertisers/{advertiserId}/channels/{channelsId}/sites/{sitesId}",
                  "httpMethod": "DELETE",
                  "description": "Deletes a site from a channel.",
                  "path": "v1/advertisers/{advertiserId}/channels/{+channelId}/sites/{+urlOrAppId}",
                  "id": "displayvideo.advertisers.channels.sites.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "create": {
                  "description": "Creates a site in a channel.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v1/advertisers/{advertiserId}/channels/{+channelId}/sites",
                  "flatPath": "v1/advertisers/{advertiserId}/channels/{channelsId}/sites",
                  "httpMethod": "POST",
                  "id": "displayvideo.advertisers.channels.sites.create"
                },
                "bulkEdit": {
                  "description": "Bulk edits sites under a single channel. The operation will delete the sites provided in BulkEditSitesRequest.deleted_sites and then create the sites provided in BulkEditSitesRequest.created_sites.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "POST",
                  "id": "displayvideo.advertisers.channels.sites.bulkEdit",
                  "flatPath": "v1/advertisers/{advertiserId}/channels/{channelsId}/sites:bulkEdit",
                  "path": "v1/advertisers/{advertiserId}/channels/{+channelId}/sites:bulkEdit"
                }
              }
            }
          },
          "methods": {
            "list": {
              "description": "Lists channels for a partner or advertiser.",
              "flatPath": "v1/advertisers/{advertisersId}/channels",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v1/advertisers/{+advertiserId}/channels",
              "id": "displayvideo.advertisers.channels.list",
              "httpMethod": "GET"
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Updates a channel. Returns the updated channel if successful.",
              "httpMethod": "PATCH",
              "path": "v1/advertisers/{+advertiserId}/channels/{channelId}",
              "id": "displayvideo.advertisers.channels.patch",
              "flatPath": "v1/advertisers/{advertisersId}/channels/{channelId}"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v1/advertisers/{+advertiserId}/channels/{+channelId}",
              "httpMethod": "GET",
              "description": "Gets a channel for a partner or advertiser.",
              "id": "displayvideo.advertisers.channels.get",
              "flatPath": "v1/advertisers/{advertisersId}/channels/{channelsId}"
            },
            "create": {
              "id": "displayvideo.advertisers.channels.create",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v1/advertisers/{+advertiserId}/channels",
              "httpMethod": "POST",
              "flatPath": "v1/advertisers/{advertisersId}/channels",
              "description": "Creates a new channel. Returns the newly created channel if successful."
            }
          }
        },
        "negativeKeywordLists": {
          "methods": {
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v1/advertisers/{advertisersId}/negativeKeywordLists",
              "path": "v1/advertisers/{+advertiserId}/negativeKeywordLists",
              "httpMethod": "POST",
              "description": "Creates a new negative keyword list. Returns the newly created negative keyword list if successful.",
              "id": "displayvideo.advertisers.negativeKeywordLists.create"
            },
            "patch": {
              "path": "v1/advertisers/{+advertiserId}/negativeKeywordLists/{negativeKeywordListId}",
              "description": "Updates a negative keyword list. Returns the updated negative keyword list if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v1/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListId}",
              "id": "displayvideo.advertisers.negativeKeywordLists.patch",
              "httpMethod": "PATCH"
            },
            "delete": {
              "httpMethod": "DELETE",
              "id": "displayvideo.advertisers.negativeKeywordLists.delete",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Deletes a negative keyword list given an advertiser ID and a negative keyword list ID.",
              "flatPath": "v1/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}",
              "path": "v1/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}"
            },
            "get": {
              "id": "displayvideo.advertisers.negativeKeywordLists.get",
              "httpMethod": "GET",
              "path": "v1/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Gets a negative keyword list given an advertiser ID and a negative keyword list ID.",
              "flatPath": "v1/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.negativeKeywordLists.list",
              "path": "v1/advertisers/{+advertiserId}/negativeKeywordLists",
              "flatPath": "v1/advertisers/{advertisersId}/negativeKeywordLists",
              "description": "Lists negative keyword lists based on a given advertiser id.",
              "httpMethod": "GET"
            }
          },
          "resources": {
            "negativeKeywords": {
              "methods": {
                "list": {
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.list",
                  "description": "Lists negative keywords in a negative keyword list.",
                  "httpMethod": "GET",
                  "path": "v1/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v1/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords"
                },
                "bulkEdit": {
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.bulkEdit",
                  "path": "v1/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords:bulkEdit",
                  "httpMethod": "POST",
                  "flatPath": "v1/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords:bulkEdit",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Bulk edits negative keywords in a single negative keyword list. The operation will delete the negative keywords provided in BulkEditNegativeKeywordsRequest.deleted_negative_keywords and then create the negative keywords provided in BulkEditNegativeKeywordsRequest.created_negative_keywords. This operation is guaranteed to be atomic and will never result in a partial success or partial failure."
                },
                "delete": {
                  "flatPath": "v1/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords/{negativeKeywordsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v1/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords/{+keywordValue}",
                  "description": "Deletes a negative keyword from a negative keyword list.",
                  "httpMethod": "DELETE",
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.delete"
                },
                "create": {
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.create",
                  "flatPath": "v1/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords",
                  "description": "Creates a negative keyword in a negative keyword list.",
                  "path": "v1/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "POST"
                }
              }
            }
          }
        },
        "lineItems": {
          "methods": {
            "bulkListLineItemAssignedTargetingOptions": {
              "httpMethod": "GET",
              "description": "Lists assigned targeting options of a line item across targeting types.",
              "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}:bulkListLineItemAssignedTargetingOptions",
              "id": "displayvideo.advertisers.lineItems.bulkListLineItemAssignedTargetingOptions",
              "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}:bulkListLineItemAssignedTargetingOptions",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "get": {
              "description": "Gets a line item.",
              "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.lineItems.get",
              "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "DELETE",
              "id": "displayvideo.advertisers.lineItems.delete",
              "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "description": "Deletes a line item. Returns error code `NOT_FOUND` if the line item does not exist. The line item should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it.",
              "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}"
            },
            "patch": {
              "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Updates an existing line item. Returns the updated line item if successful.",
              "id": "displayvideo.advertisers.lineItems.patch",
              "httpMethod": "PATCH",
              "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}"
            },
            "list": {
              "description": "Lists line items in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, line items with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.lineItems.list",
              "path": "v1/advertisers/{+advertiserId}/lineItems",
              "flatPath": "v1/advertisers/{advertisersId}/lineItems",
              "httpMethod": "GET"
            },
            "bulkEditLineItemAssignedTargetingOptions": {
              "id": "displayvideo.advertisers.lineItems.bulkEditLineItemAssignedTargetingOptions",
              "description": "Bulk edits targeting options under a single line item. The operation will delete the assigned targeting options provided in BulkEditLineItemAssignedTargetingOptionsRequest.delete_requests and then create the assigned targeting options provided in BulkEditLineItemAssignedTargetingOptionsRequest.create_requests .",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}:bulkEditLineItemAssignedTargetingOptions",
              "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}:bulkEditLineItemAssignedTargetingOptions"
            },
            "create": {
              "path": "v1/advertisers/{+advertiserId}/lineItems",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.lineItems.create",
              "description": "Creates a new line item. Returns the newly created line item if successful.",
              "httpMethod": "POST",
              "flatPath": "v1/advertisers/{advertisersId}/lineItems"
            }
          },
          "resources": {
            "targetingTypes": {
              "resources": {
                "assignedTargetingOptions": {
                  "methods": {
                    "create": {
                      "description": "Assigns a targeting option to a line item. Returns the assigned targeting option if successful.",
                      "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "httpMethod": "POST",
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.create"
                    },
                    "get": {
                      "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "description": "Gets a single targeting option assigned to a line item.",
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.get",
                      "httpMethod": "GET",
                      "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}"
                    },
                    "list": {
                      "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.list",
                      "description": "Lists the targeting options assigned to a line item.",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "httpMethod": "GET"
                    },
                    "delete": {
                      "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "description": "Deletes an assigned targeting option from a line item.",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.delete",
                      "httpMethod": "DELETE"
                    }
                  }
                }
              }
            }
          }
        },
        "locationLists": {
          "resources": {
            "assignedLocations": {
              "methods": {
                "create": {
                  "flatPath": "v1/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "path": "v1/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "httpMethod": "POST",
                  "description": "Creates an assignment between a location and a location list.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.create"
                },
                "bulkEdit": {
                  "httpMethod": "POST",
                  "flatPath": "v1/advertisers/{advertiserId}/locationLists/{locationListsId}/assignedLocations:bulkEdit",
                  "description": "Bulk edits multiple assignments between locations and a single location list. The operation will delete the assigned locations provided in BulkEditAssignedLocationsRequest.deleted_assigned_locations and then create the assigned locations provided in BulkEditAssignedLocationsRequest.created_assigned_locations.",
                  "path": "v1/advertisers/{advertiserId}/locationLists/{+locationListId}/assignedLocations:bulkEdit",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.bulkEdit",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v1/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "description": "Lists locations assigned to a location list.",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.list",
                  "path": "v1/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "httpMethod": "GET"
                },
                "delete": {
                  "flatPath": "v1/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations/{assignedLocationsId}",
                  "httpMethod": "DELETE",
                  "description": "Deletes the assignment between a location and a location list.",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.delete",
                  "path": "v1/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations/{+assignedLocationId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                }
              }
            }
          },
          "methods": {
            "create": {
              "flatPath": "v1/advertisers/{advertisersId}/locationLists",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.locationLists.create",
              "httpMethod": "POST",
              "description": "Creates a new location list. Returns the newly created location list if successful.",
              "path": "v1/advertisers/{+advertiserId}/locationLists"
            },
            "list": {
              "description": "Lists location lists based on a given advertiser id.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v1/advertisers/{+advertiserId}/locationLists",
              "httpMethod": "GET",
              "flatPath": "v1/advertisers/{advertisersId}/locationLists",
              "id": "displayvideo.advertisers.locationLists.list"
            },
            "get": {
              "description": "Gets a location list.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.locationLists.get",
              "flatPath": "v1/advertisers/{advertisersId}/locationLists/{locationListsId}",
              "httpMethod": "GET",
              "path": "v1/advertisers/{+advertiserId}/locationLists/{+locationListId}"
            },
            "patch": {
              "path": "v1/advertisers/{+advertiserId}/locationLists/{locationListId}",
              "description": "Updates a location list. Returns the updated location list if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v1/advertisers/{advertisersId}/locationLists/{locationListId}",
              "httpMethod": "PATCH",
              "id": "displayvideo.advertisers.locationLists.patch"
            }
          }
        },
        "campaigns": {
          "methods": {
            "create": {
              "description": "Creates a new campaign. Returns the newly created campaign if successful.",
              "flatPath": "v1/advertisers/{advertisersId}/campaigns",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "id": "displayvideo.advertisers.campaigns.create",
              "path": "v1/advertisers/{+advertiserId}/campaigns",
              "httpMethod": "POST"
            },
            "get": {
              "path": "v1/advertisers/{+advertiserId}/campaigns/{+campaignId}",
              "flatPath": "v1/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "httpMethod": "GET",
              "description": "Gets a campaign.",
              "id": "displayvideo.advertisers.campaigns.get"
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "id": "displayvideo.advertisers.campaigns.patch",
              "httpMethod": "PATCH",
              "flatPath": "v1/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "path": "v1/advertisers/{+advertiserId}/campaigns/{+campaignId}",
              "description": "Updates an existing campaign. Returns the updated campaign if successful."
            },
            "list": {
              "flatPath": "v1/advertisers/{advertisersId}/campaigns",
              "description": "Lists campaigns in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, campaigns with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "httpMethod": "GET",
              "path": "v1/advertisers/{+advertiserId}/campaigns",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "id": "displayvideo.advertisers.campaigns.list"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "httpMethod": "DELETE",
              "description": "Permanently deletes a campaign. A deleted campaign cannot be recovered. The campaign should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it.",
              "path": "v1/advertisers/{+advertiserId}/campaigns/{+campaignId}",
              "flatPath": "v1/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "id": "displayvideo.advertisers.campaigns.delete"
            }
          }
        },
        "insertionOrders": {
          "resources": {
            "targetingTypes": {
              "resources": {
                "assignedTargetingOptions": {
                  "methods": {
                    "get": {
                      "httpMethod": "GET",
                      "path": "v1/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "id": "displayvideo.advertisers.insertionOrders.targetingTypes.assignedTargetingOptions.get",
                      "description": "Gets a single targeting option assigned to an insertion order.",
                      "flatPath": "v1/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}"
                    },
                    "list": {
                      "id": "displayvideo.advertisers.insertionOrders.targetingTypes.assignedTargetingOptions.list",
                      "description": "Lists the targeting options assigned to an insertion order.",
                      "path": "v1/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "httpMethod": "GET",
                      "flatPath": "v1/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions"
                    }
                  }
                }
              }
            }
          },
          "methods": {
            "patch": {
              "id": "displayvideo.advertisers.insertionOrders.patch",
              "flatPath": "v1/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "httpMethod": "PATCH",
              "path": "v1/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Updates an existing insertion order. Returns the updated insertion order if successful."
            },
            "create": {
              "path": "v1/advertisers/{+advertiserId}/insertionOrders",
              "id": "displayvideo.advertisers.insertionOrders.create",
              "description": "Creates a new insertion order. Returns the newly created insertion order if successful.",
              "httpMethod": "POST",
              "flatPath": "v1/advertisers/{advertisersId}/insertionOrders",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "description": "Gets an insertion order. Returns error code `NOT_FOUND` if the insertion order does not exist.",
              "path": "v1/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}",
              "id": "displayvideo.advertisers.insertionOrders.get",
              "flatPath": "v1/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}"
            },
            "bulkListInsertionOrderAssignedTargetingOptions": {
              "path": "v1/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}:bulkListInsertionOrderAssignedTargetingOptions",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists assigned targeting options of an insertion order across targeting types.",
              "flatPath": "v1/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}:bulkListInsertionOrderAssignedTargetingOptions",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.insertionOrders.bulkListInsertionOrderAssignedTargetingOptions"
            },
            "list": {
              "id": "displayvideo.advertisers.insertionOrders.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists insertion orders in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, insertion orders with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "flatPath": "v1/advertisers/{advertisersId}/insertionOrders",
              "path": "v1/advertisers/{+advertiserId}/insertionOrders",
              "httpMethod": "GET"
            },
            "delete": {
              "httpMethod": "DELETE",
              "id": "displayvideo.advertisers.insertionOrders.delete",
              "flatPath": "v1/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Deletes an insertion order. Returns error code `NOT_FOUND` if the insertion order does not exist. The insertion order should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it.",
              "path": "v1/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}"
            }
          }
        },
        "targetingTypes": {
          "resources": {
            "assignedTargetingOptions": {
              "methods": {
                "list": {
                  "description": "Lists the targeting options assigned to an advertiser.",
                  "path": "v1/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.list",
                  "flatPath": "v1/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions"
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v1/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.get",
                  "description": "Gets a single targeting option assigned to an advertiser.",
                  "path": "v1/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "httpMethod": "GET"
                },
                "create": {
                  "description": "Assigns a targeting option to an advertiser. Returns the assigned targeting option if successful.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v1/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "httpMethod": "POST",
                  "path": "v1/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.create"
                },
                "delete": {
                  "description": "Deletes an assigned targeting option from an advertiser.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v1/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "httpMethod": "DELETE",
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.delete",
                  "flatPath": "v1/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}"
                }
              }
            }
          }
        },
        "assets": {
          "methods": {
            "upload": {
              "httpMethod": "POST",
              "description": "Uploads an asset. Returns the ID of the newly uploaded asset if successful. The asset file size should be no more than 10 MB for images, 200 MB for ZIP files, and 1 GB for videos.",
              "id": "displayvideo.advertisers.assets.upload",
              "flatPath": "v1/advertisers/{advertisersId}/assets",
              "supportsMediaUpload": true,
              "path": "v1/advertisers/{+advertiserId}/assets",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          }
        }
      }
    },
    "partners": {
      "resources": {
        "targetingTypes": {
          "resources": {
            "assignedTargetingOptions": {
              "methods": {
                "create": {
                  "flatPath": "v1/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "description": "Assigns a targeting option to a partner. Returns the assigned targeting option if successful.",
                  "path": "v1/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "POST",
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.create"
                },
                "get": {
                  "description": "Gets a single targeting option assigned to a partner.",
                  "flatPath": "v1/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v1/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.get"
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "path": "v1/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.delete",
                  "description": "Deletes an assigned targeting option from a partner.",
                  "flatPath": "v1/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}"
                },
                "list": {
                  "flatPath": "v1/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.list",
                  "path": "v1/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "httpMethod": "GET",
                  "description": "Lists the targeting options assigned to a partner."
                }
              }
            }
          }
        },
        "channels": {
          "resources": {
            "sites": {
              "methods": {
                "list": {
                  "path": "v1/partners/{+partnerId}/channels/{+channelId}/sites",
                  "id": "displayvideo.partners.channels.sites.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "GET",
                  "flatPath": "v1/partners/{partnersId}/channels/{channelsId}/sites",
                  "description": "Lists sites in a channel."
                },
                "create": {
                  "id": "displayvideo.partners.channels.sites.create",
                  "description": "Creates a site in a channel.",
                  "path": "v1/partners/{partnerId}/channels/{+channelId}/sites",
                  "flatPath": "v1/partners/{partnerId}/channels/{channelsId}/sites",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "POST"
                },
                "delete": {
                  "id": "displayvideo.partners.channels.sites.delete",
                  "description": "Deletes a site from a channel.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v1/partners/{partnerId}/channels/{channelsId}/sites/{sitesId}",
                  "path": "v1/partners/{partnerId}/channels/{+channelId}/sites/{+urlOrAppId}",
                  "httpMethod": "DELETE"
                },
                "bulkEdit": {
                  "httpMethod": "POST",
                  "flatPath": "v1/partners/{partnerId}/channels/{channelsId}/sites:bulkEdit",
                  "path": "v1/partners/{partnerId}/channels/{+channelId}/sites:bulkEdit",
                  "description": "Bulk edits sites under a single channel. The operation will delete the sites provided in BulkEditSitesRequest.deleted_sites and then create the sites provided in BulkEditSitesRequest.created_sites.",
                  "id": "displayvideo.partners.channels.sites.bulkEdit",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                }
              }
            }
          },
          "methods": {
            "create": {
              "flatPath": "v1/partners/{partnersId}/channels",
              "path": "v1/partners/{+partnerId}/channels",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "POST",
              "id": "displayvideo.partners.channels.create",
              "description": "Creates a new channel. Returns the newly created channel if successful."
            },
            "list": {
              "path": "v1/partners/{+partnerId}/channels",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.partners.channels.list",
              "flatPath": "v1/partners/{partnersId}/channels",
              "description": "Lists channels for a partner or advertiser.",
              "httpMethod": "GET"
            },
            "get": {
              "description": "Gets a channel for a partner or advertiser.",
              "flatPath": "v1/partners/{partnersId}/channels/{channelsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.partners.channels.get",
              "path": "v1/partners/{+partnerId}/channels/{+channelId}",
              "httpMethod": "GET"
            },
            "patch": {
              "flatPath": "v1/partners/{partnersId}/channels/{channelId}",
              "description": "Updates a channel. Returns the updated channel if successful.",
              "httpMethod": "PATCH",
              "path": "v1/partners/{+partnerId}/channels/{channelId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.partners.channels.patch"
            }
          }
        }
      },
      "methods": {
        "get": {
          "flatPath": "v1/partners/{partnersId}",
          "id": "displayvideo.partners.get",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Gets a partner.",
          "path": "v1/partners/{+partnerId}"
        },
        "bulkEditPartnerAssignedTargetingOptions": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v1/partners/{+partnerId}:bulkEditPartnerAssignedTargetingOptions",
          "description": "Bulk edits targeting options under a single partner. The operation will delete the assigned targeting options provided in BulkEditPartnerAssignedTargetingOptionsRequest.deleteRequests and then create the assigned targeting options provided in BulkEditPartnerAssignedTargetingOptionsRequest.createRequests .",
          "flatPath": "v1/partners/{partnersId}:bulkEditPartnerAssignedTargetingOptions",
          "httpMethod": "POST",
          "id": "displayvideo.partners.bulkEditPartnerAssignedTargetingOptions"
        },
        "list": {
          "flatPath": "v1/partners",
          "id": "displayvideo.partners.list",
          "path": "v1/partners",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Lists partners that are accessible to the current user. The order is defined by the order_by parameter."
        }
      }
    },
    "inventorySources": {
      "methods": {
        "list": {
          "path": "v1/inventorySources",
          "flatPath": "v1/inventorySources",
          "id": "displayvideo.inventorySources.list",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET",
          "description": "Lists inventory sources that are accessible to the current user. The order is defined by the order_by parameter. If a filter by entity_status is not specified, inventory sources with entity status `ENTITY_STATUS_ARCHIVED` will not be included in the results."
        },
        "get": {
          "description": "Gets an inventory source.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET",
          "id": "displayvideo.inventorySources.get",
          "flatPath": "v1/inventorySources/{inventorySourcesId}",
          "path": "v1/inventorySources/{+inventorySourceId}"
        }
      }
    },
    "media": {
      "methods": {
        "download": {
          "httpMethod": "GET",
          "path": "download/{+resourceName}",
          "id": "displayvideo.media.download",
          "flatPath": "download/{downloadId}",
          "description": "Downloads media. Download is supported on the URI `/download/{resource_name=**}?alt=media.` **Note**: Download requests will not be successful without including `alt=media` query string.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video",
            "https://www.googleapis.com/auth/doubleclickbidmanager"
          ],
          "supportsMediaDownload": true
        }
      }
    },
    "floodlightGroups": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "flatPath": "v1/floodlightGroups/{floodlightGroupsId}",
          "id": "displayvideo.floodlightGroups.get",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Gets a Floodlight group.",
          "path": "v1/floodlightGroups/{+floodlightGroupId}"
        },
        "patch": {
          "httpMethod": "PATCH",
          "description": "Updates an existing Floodlight group. Returns the updated Floodlight group if successful.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.floodlightGroups.patch",
          "path": "v1/floodlightGroups/{floodlightGroupId}",
          "flatPath": "v1/floodlightGroups/{floodlightGroupId}"
        }
      }
    },
    "customBiddingAlgorithms": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "id": "displayvideo.customBiddingAlgorithms.list",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Lists custom bidding algorithms that are accessible to the current user and can be used in bidding stratgies. The order is defined by the order_by parameter.",
          "flatPath": "v1/customBiddingAlgorithms",
          "path": "v1/customBiddingAlgorithms"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v1/customBiddingAlgorithms/{+customBiddingAlgorithmId}",
          "flatPath": "v1/customBiddingAlgorithms/{customBiddingAlgorithmsId}",
          "description": "Gets a custom bidding algorithm.",
          "httpMethod": "GET",
          "id": "displayvideo.customBiddingAlgorithms.get"
        }
      }
    },
    "customLists": {
      "methods": {
        "get": {
          "flatPath": "v1/customLists/{customListsId}",
          "httpMethod": "GET",
          "description": "Gets a custom list.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v1/customLists/{+customListId}",
          "id": "displayvideo.customLists.get"
        },
        "list": {
          "flatPath": "v1/customLists",
          "httpMethod": "GET",
          "description": "Lists custom lists. The order is defined by the order_by parameter.",
          "path": "v1/customLists",
          "id": "displayvideo.customLists.list",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      }
    },
    "users": {
      "methods": {
        "patch": {
          "description": "Updates an existing user. Returns the updated user if successful.",
          "path": "v1/users/{+userId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "id": "displayvideo.users.patch",
          "flatPath": "v1/users/{usersId}",
          "httpMethod": "PATCH"
        },
        "get": {
          "path": "v1/users/{+userId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "flatPath": "v1/users/{usersId}",
          "description": "Gets a user.",
          "id": "displayvideo.users.get"
        },
        "delete": {
          "description": "Deletes a user.",
          "id": "displayvideo.users.delete",
          "flatPath": "v1/users/{usersId}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "path": "v1/users/{+userId}"
        },
        "create": {
          "httpMethod": "POST",
          "id": "displayvideo.users.create",
          "path": "v1/users",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "flatPath": "v1/users",
          "description": "Creates a new user. Returns the newly created user if successful."
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "flatPath": "v1/users",
          "path": "v1/users",
          "description": "Lists users that are accessible to the current user. If two users have user roles on the same partner or advertiser, they can access each other.",
          "id": "displayvideo.users.list",
          "httpMethod": "GET"
        },
        "bulkEditAssignedUserRoles": {
          "flatPath": "v1/users/{usersId}:bulkEditAssignedUserRoles",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "description": "Bulk edits user roles for a user. The operation will delete the assigned user roles provided in BulkEditAssignedUserRolesRequest.deletedAssignedUserRoles and then assign the user roles provided in BulkEditAssignedUserRolesRequest.createdAssignedUserRoles.",
          "httpMethod": "POST",
          "path": "v1/users/{+userId}:bulkEditAssignedUserRoles",
          "id": "displayvideo.users.bulkEditAssignedUserRoles"
        }
      }
    },
    "targetingTypes": {
      "resources": {
        "targetingOptions": {
          "methods": {
            "search": {
              "path": "v1/targetingTypes/{+targetingType}/targetingOptions:search",
              "id": "displayvideo.targetingTypes.targetingOptions.search",
              "description": "Searches for targeting options of a given type based on the given search terms.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "POST",
              "flatPath": "v1/targetingTypes/{targetingTypesId}/targetingOptions:search"
            },
            "get": {
              "description": "Gets a single targeting option.",
              "id": "displayvideo.targetingTypes.targetingOptions.get",
              "flatPath": "v1/targetingTypes/{targetingTypesId}/targetingOptions/{targetingOptionsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v1/targetingTypes/{+targetingType}/targetingOptions/{+targetingOptionId}",
              "httpMethod": "GET"
            },
            "list": {
              "path": "v1/targetingTypes/{+targetingType}/targetingOptions",
              "flatPath": "v1/targetingTypes/{targetingTypesId}/targetingOptions",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists targeting options of a given type.",
              "id": "displayvideo.targetingTypes.targetingOptions.list",
              "httpMethod": "GET"
            }
          }
        }
      }
    },
    "googleAudiences": {
      "methods": {
        "list": {
          "flatPath": "v1/googleAudiences",
          "id": "displayvideo.googleAudiences.list",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Lists Google audiences. The order is defined by the order_by parameter.",
          "path": "v1/googleAudiences"
        },
        "get": {
          "path": "v1/googleAudiences/{+googleAudienceId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v1/googleAudiences/{googleAudiencesId}",
          "id": "displayvideo.googleAudiences.get",
          "description": "Gets a Google audience.",
          "httpMethod": "GET"
        }
      }
    },
    "combinedAudiences": {
      "methods": {
        "get": {
          "path": "v1/combinedAudiences/{+combinedAudienceId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET",
          "id": "displayvideo.combinedAudiences.get",
          "description": "Gets a combined audience.",
          "flatPath": "v1/combinedAudiences/{combinedAudiencesId}"
        },
        "list": {
          "description": "Lists combined audiences. The order is defined by the order_by parameter.",
          "id": "displayvideo.combinedAudiences.list",
          "path": "v1/combinedAudiences",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET",
          "flatPath": "v1/combinedAudiences"
        }
      }
    }
  },
  "canonicalName": "Display Video",
  "id": "displayvideo:v1",
  "title": "Display & Video 360 API",
  "fullyEncodeReservedExpansion": true,
  "ownerName": "Google",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/display-video-mediaplanning": {
          "description": "Create, see, and edit Display & Video 360 Campaign entities and see billing invoices"
        },
        "https://www.googleapis.com/auth/display-video": {
          "description": "Create, see, edit, and permanently delete your Display & Video 360 entities and reports"
        },
        "https://www.googleapis.com/auth/display-video-user-management": {
          "description": "Private Service: https://www.googleapis.com/auth/display-video-user-management"
        },
        "https://www.googleapis.com/auth/doubleclickbidmanager": {
          "description": "View and manage your reports in DoubleClick Bid Manager"
        }
      }
    }
  }
}
