{
  "id": "displayvideo:v1",
  "kind": "discovery#restDescription",
  "revision": "20210202",
  "name": "displayvideo",
  "title": "Display & Video 360 API",
  "version": "v1",
  "documentationLink": "https://developers.google.com/display-video/",
  "protocol": "rest",
  "rootUrl": "https://displayvideo.googleapis.com/",
  "ownerDomain": "google.com",
  "batchPath": "batch",
  "mtlsRootUrl": "https://displayvideo.mtls.googleapis.com/",
  "discoveryVersion": "v1",
  "ownerName": "Google",
  "basePath": "",
  "resources": {
    "users": {
      "methods": {
        "get": {
          "flatPath": "v1/users/{usersId}",
          "httpMethod": "GET",
          "path": "v1/users/{+userId}",
          "description": "Gets a user.",
          "id": "displayvideo.users.get",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ]
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "flatPath": "v1/users/{usersId}",
          "description": "Updates an existing user. Returns the updated user if successful.",
          "path": "v1/users/{+userId}",
          "httpMethod": "PATCH",
          "id": "displayvideo.users.patch"
        },
        "list": {
          "flatPath": "v1/users",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "description": "Lists users that are accessible to the current user. If two users have user roles on the same partner or advertiser, they can access each other.",
          "id": "displayvideo.users.list",
          "path": "v1/users",
          "httpMethod": "GET"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "id": "displayvideo.users.delete",
          "httpMethod": "DELETE",
          "flatPath": "v1/users/{usersId}",
          "path": "v1/users/{+userId}",
          "description": "Deletes a user."
        },
        "create": {
          "path": "v1/users",
          "description": "Creates a new user. Returns the newly created user if successful.",
          "id": "displayvideo.users.create",
          "flatPath": "v1/users",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ]
        },
        "bulkEditAssignedUserRoles": {
          "path": "v1/users/{+userId}:bulkEditAssignedUserRoles",
          "flatPath": "v1/users/{usersId}:bulkEditAssignedUserRoles",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "id": "displayvideo.users.bulkEditAssignedUserRoles",
          "description": "Bulk edits user roles for a user. The operation will delete the assigned user roles provided in BulkEditAssignedUserRolesRequest.deletedAssignedUserRoles and then assign the user roles provided in BulkEditAssignedUserRolesRequest.createdAssignedUserRoles.",
          "httpMethod": "POST"
        }
      }
    },
    "googleAudiences": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "id": "displayvideo.googleAudiences.get",
          "description": "Gets a Google audience.",
          "path": "v1/googleAudiences/{+googleAudienceId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v1/googleAudiences/{googleAudiencesId}"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.googleAudiences.list",
          "path": "v1/googleAudiences",
          "description": "Lists Google audiences. The order is defined by the order_by parameter.",
          "httpMethod": "GET",
          "flatPath": "v1/googleAudiences"
        }
      }
    },
    "partners": {
      "resources": {
        "targetingTypes": {
          "resources": {
            "assignedTargetingOptions": {
              "methods": {
                "create": {
                  "httpMethod": "POST",
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.create",
                  "description": "Assigns a targeting option to a partner. Returns the assigned targeting option if successful.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v1/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "path": "v1/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions"
                },
                "list": {
                  "path": "v1/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "flatPath": "v1/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "GET",
                  "description": "Lists the targeting options assigned to a partner.",
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.list"
                },
                "delete": {
                  "flatPath": "v1/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "description": "Deletes an assigned targeting option from a partner.",
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.delete",
                  "path": "v1/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "get": {
                  "flatPath": "v1/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "path": "v1/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Gets a single targeting option assigned to a partner.",
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.get"
                }
              }
            }
          }
        },
        "channels": {
          "methods": {
            "patch": {
              "flatPath": "v1/partners/{partnersId}/channels/{channelId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Updates a channel. Returns the updated channel if successful.",
              "httpMethod": "PATCH",
              "path": "v1/partners/{+partnerId}/channels/{channelId}",
              "id": "displayvideo.partners.channels.patch"
            },
            "get": {
              "httpMethod": "GET",
              "description": "Gets a channel for a partner or advertiser.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.partners.channels.get",
              "flatPath": "v1/partners/{partnersId}/channels/{channelsId}",
              "path": "v1/partners/{+partnerId}/channels/{+channelId}"
            },
            "list": {
              "id": "displayvideo.partners.channels.list",
              "path": "v1/partners/{+partnerId}/channels",
              "description": "Lists channels for a partner or advertiser.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v1/partners/{partnersId}/channels",
              "httpMethod": "GET"
            },
            "create": {
              "path": "v1/partners/{+partnerId}/channels",
              "description": "Creates a new channel. Returns the newly created channel if successful.",
              "flatPath": "v1/partners/{partnersId}/channels",
              "id": "displayvideo.partners.channels.create",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "POST"
            }
          },
          "resources": {
            "sites": {
              "methods": {
                "bulkEdit": {
                  "id": "displayvideo.partners.channels.sites.bulkEdit",
                  "path": "v1/partners/{partnerId}/channels/{+channelId}/sites:bulkEdit",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Bulk edits sites under a single channel. The operation will delete the sites provided in BulkEditSitesRequest.deleted_sites and then create the sites provided in BulkEditSitesRequest.created_sites.",
                  "httpMethod": "POST",
                  "flatPath": "v1/partners/{partnerId}/channels/{channelsId}/sites:bulkEdit"
                },
                "create": {
                  "path": "v1/partners/{partnerId}/channels/{+channelId}/sites",
                  "id": "displayvideo.partners.channels.sites.create",
                  "description": "Creates a site in a channel.",
                  "flatPath": "v1/partners/{partnerId}/channels/{channelsId}/sites",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v1/partners/{partnerId}/channels/{+channelId}/sites/{+urlOrAppId}",
                  "description": "Deletes a site from a channel.",
                  "flatPath": "v1/partners/{partnerId}/channels/{channelsId}/sites/{sitesId}",
                  "id": "displayvideo.partners.channels.sites.delete"
                },
                "list": {
                  "description": "Lists sites in a channel.",
                  "path": "v1/partners/{+partnerId}/channels/{+channelId}/sites",
                  "id": "displayvideo.partners.channels.sites.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "GET",
                  "flatPath": "v1/partners/{partnersId}/channels/{channelsId}/sites"
                }
              }
            }
          }
        }
      },
      "methods": {
        "list": {
          "httpMethod": "GET",
          "description": "Lists partners that are accessible to the current user. The order is defined by the order_by parameter.",
          "path": "v1/partners",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v1/partners",
          "id": "displayvideo.partners.list"
        },
        "bulkEditPartnerAssignedTargetingOptions": {
          "path": "v1/partners/{+partnerId}:bulkEditPartnerAssignedTargetingOptions",
          "id": "displayvideo.partners.bulkEditPartnerAssignedTargetingOptions",
          "description": "Bulk edits targeting options under a single partner. The operation will delete the assigned targeting options provided in BulkEditPartnerAssignedTargetingOptionsRequest.deleteRequests and then create the assigned targeting options provided in BulkEditPartnerAssignedTargetingOptionsRequest.createRequests .",
          "httpMethod": "POST",
          "flatPath": "v1/partners/{partnersId}:bulkEditPartnerAssignedTargetingOptions",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "get": {
          "description": "Gets a partner.",
          "httpMethod": "GET",
          "flatPath": "v1/partners/{partnersId}",
          "id": "displayvideo.partners.get",
          "path": "v1/partners/{+partnerId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      }
    },
    "targetingTypes": {
      "resources": {
        "targetingOptions": {
          "methods": {
            "list": {
              "flatPath": "v1/targetingTypes/{targetingTypesId}/targetingOptions",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "description": "Lists targeting options of a given type.",
              "id": "displayvideo.targetingTypes.targetingOptions.list",
              "path": "v1/targetingTypes/{+targetingType}/targetingOptions"
            },
            "get": {
              "httpMethod": "GET",
              "path": "v1/targetingTypes/{+targetingType}/targetingOptions/{+targetingOptionId}",
              "flatPath": "v1/targetingTypes/{targetingTypesId}/targetingOptions/{targetingOptionsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Gets a single targeting option.",
              "id": "displayvideo.targetingTypes.targetingOptions.get"
            },
            "search": {
              "flatPath": "v1/targetingTypes/{targetingTypesId}/targetingOptions:search",
              "httpMethod": "POST",
              "description": "Searches for targeting options of a given type based on the given search terms.",
              "path": "v1/targetingTypes/{+targetingType}/targetingOptions:search",
              "id": "displayvideo.targetingTypes.targetingOptions.search",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          }
        }
      }
    },
    "media": {
      "methods": {
        "download": {
          "httpMethod": "GET",
          "flatPath": "download/{downloadId}",
          "path": "download/{+resourceName}",
          "id": "displayvideo.media.download",
          "supportsMediaDownload": true,
          "scopes": [
            "https://www.googleapis.com/auth/display-video",
            "https://www.googleapis.com/auth/doubleclickbidmanager"
          ],
          "description": "Downloads media. Download is supported on the URI `/download/{resource_name=**}?alt=media.` **Note**: Download requests will not be successful without including `alt=media` query string."
        }
      }
    },
    "customLists": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v1/customLists/{customListsId}",
          "httpMethod": "GET",
          "path": "v1/customLists/{+customListId}",
          "id": "displayvideo.customLists.get",
          "description": "Gets a custom list."
        },
        "list": {
          "httpMethod": "GET",
          "id": "displayvideo.customLists.list",
          "path": "v1/customLists",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Lists custom lists. The order is defined by the order_by parameter.",
          "flatPath": "v1/customLists"
        }
      }
    },
    "inventorySourceGroups": {
      "methods": {
        "create": {
          "httpMethod": "POST",
          "description": "Creates a new inventory source group. Returns the newly created inventory source group if successful.",
          "flatPath": "v1/inventorySourceGroups",
          "path": "v1/inventorySourceGroups",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.inventorySourceGroups.create"
        },
        "list": {
          "flatPath": "v1/inventorySourceGroups",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET",
          "description": "Lists inventory source groups that are accessible to the current user. The order is defined by the order_by parameter.",
          "path": "v1/inventorySourceGroups",
          "id": "displayvideo.inventorySourceGroups.list"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.inventorySourceGroups.get",
          "flatPath": "v1/inventorySourceGroups/{inventorySourceGroupsId}",
          "description": "Gets an inventory source group.",
          "httpMethod": "GET",
          "path": "v1/inventorySourceGroups/{+inventorySourceGroupId}"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.inventorySourceGroups.delete",
          "flatPath": "v1/inventorySourceGroups/{inventorySourceGroupsId}",
          "path": "v1/inventorySourceGroups/{+inventorySourceGroupId}",
          "description": "Deletes an inventory source group.",
          "httpMethod": "DELETE"
        },
        "patch": {
          "id": "displayvideo.inventorySourceGroups.patch",
          "description": "Updates an inventory source group. Returns the updated inventory source group if successful.",
          "path": "v1/inventorySourceGroups/{inventorySourceGroupId}",
          "flatPath": "v1/inventorySourceGroups/{inventorySourceGroupId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "PATCH"
        }
      },
      "resources": {
        "assignedInventorySources": {
          "methods": {
            "bulkEdit": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v1/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources:bulkEdit",
              "description": "Bulk edits multiple assignments between inventory sources and a single inventory source group. The operation will delete the assigned inventory sources provided in BulkEditAssignedInventorySourcesRequest.deleted_assigned_inventory_sources and then create the assigned inventory sources provided in BulkEditAssignedInventorySourcesRequest.created_assigned_inventory_sources.",
              "path": "v1/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources:bulkEdit",
              "httpMethod": "POST",
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.bulkEdit"
            },
            "list": {
              "description": "Lists inventory sources assigned to an inventory source group.",
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.list",
              "httpMethod": "GET",
              "flatPath": "v1/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v1/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources"
            },
            "create": {
              "path": "v1/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources",
              "httpMethod": "POST",
              "flatPath": "v1/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Creates an assignment between an inventory source and an inventory source group.",
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.create"
            },
            "delete": {
              "httpMethod": "DELETE",
              "flatPath": "v1/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources/{assignedInventorySourcesId}",
              "description": "Deletes the assignment between an inventory source and an inventory source group.",
              "path": "v1/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources/{+assignedInventorySourceId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.delete"
            }
          }
        }
      }
    },
    "combinedAudiences": {
      "methods": {
        "get": {
          "id": "displayvideo.combinedAudiences.get",
          "description": "Gets a combined audience.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET",
          "flatPath": "v1/combinedAudiences/{combinedAudiencesId}",
          "path": "v1/combinedAudiences/{+combinedAudienceId}"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v1/combinedAudiences",
          "description": "Lists combined audiences. The order is defined by the order_by parameter.",
          "httpMethod": "GET",
          "flatPath": "v1/combinedAudiences",
          "id": "displayvideo.combinedAudiences.list"
        }
      }
    },
    "customBiddingAlgorithms": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Gets a custom bidding algorithm.",
          "path": "v1/customBiddingAlgorithms/{+customBiddingAlgorithmId}",
          "id": "displayvideo.customBiddingAlgorithms.get",
          "httpMethod": "GET",
          "flatPath": "v1/customBiddingAlgorithms/{customBiddingAlgorithmsId}"
        },
        "list": {
          "description": "Lists custom bidding algorithms that are accessible to the current user and can be used in bidding stratgies. The order is defined by the order_by parameter.",
          "httpMethod": "GET",
          "flatPath": "v1/customBiddingAlgorithms",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.customBiddingAlgorithms.list",
          "path": "v1/customBiddingAlgorithms"
        }
      }
    },
    "sdfdownloadtasks": {
      "methods": {
        "create": {
          "path": "v1/sdfdownloadtasks",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "POST",
          "description": "Creates an SDF Download Task. Returns an Operation. An SDF Download Task is a long-running, asynchronous operation. The metadata type of this operation is SdfDownloadTaskMetadata. If the request is successful, the response type of the operation is SdfDownloadTask. The response will not include the download files, which must be retrieved with media.download. The state of operation can be retrieved with sdfdownloadtask.operations.get. Any errors can be found in the error.[...]",
          "id": "displayvideo.sdfdownloadtasks.create",
          "flatPath": "v1/sdfdownloadtasks"
        }
      },
      "resources": {
        "operations": {
          "methods": {
            "get": {
              "id": "displayvideo.sdfdownloadtasks.operations.get",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/doubleclickbidmanager"
              ],
              "flatPath": "v1/sdfdownloadtasks/operations/{operationsId}",
              "description": "Gets the latest state of an asynchronous SDF download task operation. Clients should poll this method at intervals of 30 seconds.",
              "path": "v1/{+name}"
            }
          }
        }
      }
    },
    "advertisers": {
      "methods": {
        "bulkListAdvertiserAssignedTargetingOptions": {
          "description": "Lists assigned targeting options of an advertiser across targeting types.",
          "flatPath": "v1/advertisers/{advertisersId}:bulkListAdvertiserAssignedTargetingOptions",
          "id": "displayvideo.advertisers.bulkListAdvertiserAssignedTargetingOptions",
          "path": "v1/advertisers/{+advertiserId}:bulkListAdvertiserAssignedTargetingOptions",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET"
        },
        "delete": {
          "description": "Deletes an advertiser. Deleting an advertiser will delete all of its child resources, for example, campaigns, insertion orders and line items. A deleted advertiser cannot be recovered.",
          "path": "v1/advertisers/{+advertiserId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.advertisers.delete",
          "httpMethod": "DELETE",
          "flatPath": "v1/advertisers/{advertisersId}"
        },
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v1/advertisers/{+advertiserId}",
          "id": "displayvideo.advertisers.get",
          "description": "Gets an advertiser.",
          "flatPath": "v1/advertisers/{advertisersId}"
        },
        "patch": {
          "httpMethod": "PATCH",
          "flatPath": "v1/advertisers/{advertisersId}",
          "path": "v1/advertisers/{+advertiserId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Updates an existing advertiser. Returns the updated advertiser if successful.",
          "id": "displayvideo.advertisers.patch"
        },
        "bulkEditAdvertiserAssignedTargetingOptions": {
          "id": "displayvideo.advertisers.bulkEditAdvertiserAssignedTargetingOptions",
          "description": "Bulk edits targeting options under a single advertiser. The operation will delete the assigned targeting options provided in BulkEditAdvertiserAssignedTargetingOptionsRequest.delete_requests and then create the assigned targeting options provided in BulkEditAdvertiserAssignedTargetingOptionsRequest.create_requests .",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v1/advertisers/{+advertiserId}:bulkEditAdvertiserAssignedTargetingOptions",
          "flatPath": "v1/advertisers/{advertisersId}:bulkEditAdvertiserAssignedTargetingOptions",
          "httpMethod": "POST"
        },
        "create": {
          "flatPath": "v1/advertisers",
          "id": "displayvideo.advertisers.create",
          "path": "v1/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Creates a new advertiser. Returns the newly created advertiser if successful. This method can take up to 180 seconds to complete.",
          "httpMethod": "POST"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v1/advertisers",
          "description": "Lists advertisers that are accessible to the current user. The order is defined by the order_by parameter. A single partner_id is required. Cross-partner listing is not supported.",
          "httpMethod": "GET",
          "id": "displayvideo.advertisers.list",
          "flatPath": "v1/advertisers"
        },
        "audit": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v1/advertisers/{advertisersId}:audit",
          "path": "v1/advertisers/{+advertiserId}:audit",
          "description": "Audits an advertiser. Returns the counts of used entities per resource type under the advertiser provided. Used entities count towards their respective resource limit. See https://support.google.com/displayvideo/answer/6071450.",
          "id": "displayvideo.advertisers.audit",
          "httpMethod": "GET"
        }
      },
      "resources": {
        "manualTriggers": {
          "methods": {
            "deactivate": {
              "description": "Deactivates a manual trigger.",
              "httpMethod": "POST",
              "flatPath": "v1/advertisers/{advertisersId}/manualTriggers/{manualTriggersId}:deactivate",
              "id": "displayvideo.advertisers.manualTriggers.deactivate",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v1/advertisers/{+advertiserId}/manualTriggers/{+triggerId}:deactivate"
            },
            "list": {
              "path": "v1/advertisers/{+advertiserId}/manualTriggers",
              "flatPath": "v1/advertisers/{advertisersId}/manualTriggers",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "description": "Lists manual triggers that are accessible to the current user for a given advertiser ID. The order is defined by the order_by parameter. A single advertiser_id is required.",
              "id": "displayvideo.advertisers.manualTriggers.list"
            },
            "get": {
              "description": "Gets a manual trigger.",
              "path": "v1/advertisers/{+advertiserId}/manualTriggers/{+triggerId}",
              "flatPath": "v1/advertisers/{advertisersId}/manualTriggers/{manualTriggersId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.manualTriggers.get",
              "httpMethod": "GET"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "POST",
              "id": "displayvideo.advertisers.manualTriggers.create",
              "description": "Creates a new manual trigger. Returns the newly created manual trigger if successful.",
              "flatPath": "v1/advertisers/{advertisersId}/manualTriggers",
              "path": "v1/advertisers/{+advertiserId}/manualTriggers"
            },
            "activate": {
              "flatPath": "v1/advertisers/{advertisersId}/manualTriggers/{manualTriggersId}:activate",
              "httpMethod": "POST",
              "path": "v1/advertisers/{+advertiserId}/manualTriggers/{+triggerId}:activate",
              "description": "Activates a manual trigger. Each activation of the manual trigger must be at least 5 minutes apart, otherwise an error will be returned.",
              "id": "displayvideo.advertisers.manualTriggers.activate",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "patch": {
              "description": "Updates a manual trigger. Returns the updated manual trigger if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v1/advertisers/{+advertiserId}/manualTriggers/{+triggerId}",
              "httpMethod": "PATCH",
              "id": "displayvideo.advertisers.manualTriggers.patch",
              "flatPath": "v1/advertisers/{advertisersId}/manualTriggers/{manualTriggersId}"
            }
          }
        },
        "assets": {
          "methods": {
            "upload": {
              "id": "displayvideo.advertisers.assets.upload",
              "path": "v1/advertisers/{+advertiserId}/assets",
              "httpMethod": "POST",
              "flatPath": "v1/advertisers/{advertisersId}/assets",
              "description": "Uploads an asset. Returns the ID of the newly uploaded asset if successful. The asset file size should be no more than 10 MB for images, 200 MB for ZIP files, and 1 GB for videos.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "supportsMediaUpload": true
            }
          }
        },
        "creatives": {
          "methods": {
            "create": {
              "description": "Creates a new creative. Returns the newly created creative if successful.",
              "id": "displayvideo.advertisers.creatives.create",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v1/advertisers/{advertisersId}/creatives",
              "httpMethod": "POST",
              "path": "v1/advertisers/{+advertiserId}/creatives"
            },
            "get": {
              "flatPath": "v1/advertisers/{advertisersId}/creatives/{creativesId}",
              "path": "v1/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "description": "Gets a creative.",
              "id": "displayvideo.advertisers.creatives.get"
            },
            "patch": {
              "httpMethod": "PATCH",
              "path": "v1/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "id": "displayvideo.advertisers.creatives.patch",
              "flatPath": "v1/advertisers/{advertisersId}/creatives/{creativesId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Updates an existing creative. Returns the updated creative if successful."
            },
            "delete": {
              "path": "v1/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "httpMethod": "DELETE",
              "description": "Deletes a creative. Returns error code `NOT_FOUND` if the creative does not exist. The creative should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, before it can be deleted.",
              "id": "displayvideo.advertisers.creatives.delete",
              "flatPath": "v1/advertisers/{advertisersId}/creatives/{creativesId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "httpMethod": "GET",
              "path": "v1/advertisers/{+advertiserId}/creatives",
              "id": "displayvideo.advertisers.creatives.list",
              "flatPath": "v1/advertisers/{advertisersId}/creatives",
              "description": "Lists creatives in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, creatives with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          }
        },
        "campaigns": {
          "methods": {
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "path": "v1/advertisers/{+advertiserId}/campaigns/{+campaignId}",
              "httpMethod": "GET",
              "flatPath": "v1/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "description": "Gets a campaign.",
              "id": "displayvideo.advertisers.campaigns.get"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "id": "displayvideo.advertisers.campaigns.list",
              "path": "v1/advertisers/{+advertiserId}/campaigns",
              "flatPath": "v1/advertisers/{advertisersId}/campaigns",
              "description": "Lists campaigns in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, campaigns with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "httpMethod": "GET"
            },
            "delete": {
              "id": "displayvideo.advertisers.campaigns.delete",
              "description": "Permanently deletes a campaign. A deleted campaign cannot be recovered. The campaign should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "httpMethod": "DELETE",
              "flatPath": "v1/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "path": "v1/advertisers/{+advertiserId}/campaigns/{+campaignId}"
            },
            "patch": {
              "id": "displayvideo.advertisers.campaigns.patch",
              "description": "Updates an existing campaign. Returns the updated campaign if successful.",
              "path": "v1/advertisers/{+advertiserId}/campaigns/{+campaignId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "flatPath": "v1/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "httpMethod": "PATCH"
            },
            "create": {
              "id": "displayvideo.advertisers.campaigns.create",
              "path": "v1/advertisers/{+advertiserId}/campaigns",
              "httpMethod": "POST",
              "flatPath": "v1/advertisers/{advertisersId}/campaigns",
              "description": "Creates a new campaign. Returns the newly created campaign if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ]
            }
          }
        },
        "negativeKeywordLists": {
          "resources": {
            "negativeKeywords": {
              "methods": {
                "delete": {
                  "flatPath": "v1/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords/{negativeKeywordsId}",
                  "description": "Deletes a negative keyword from a negative keyword list.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v1/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords/{+keywordValue}",
                  "httpMethod": "DELETE",
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.delete"
                },
                "bulkEdit": {
                  "flatPath": "v1/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords:bulkEdit",
                  "path": "v1/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords:bulkEdit",
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.bulkEdit",
                  "description": "Bulk edits negative keywords in a single negative keyword list. The operation will delete the negative keywords provided in BulkEditNegativeKeywordsRequest.deleted_negative_keywords and then create the negative keywords provided in BulkEditNegativeKeywordsRequest.created_negative_keywords. This operation is guaranteed to be atomic and will never result in a partial success or partial failure.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "POST"
                },
                "create": {
                  "httpMethod": "POST",
                  "path": "v1/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.create",
                  "flatPath": "v1/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords",
                  "description": "Creates a negative keyword in a negative keyword list."
                },
                "list": {
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.list",
                  "httpMethod": "GET",
                  "path": "v1/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords",
                  "description": "Lists negative keywords in a negative keyword list.",
                  "flatPath": "v1/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                }
              }
            }
          },
          "methods": {
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.negativeKeywordLists.list",
              "httpMethod": "GET",
              "description": "Lists negative keyword lists based on a given advertiser id.",
              "flatPath": "v1/advertisers/{advertisersId}/negativeKeywordLists",
              "path": "v1/advertisers/{+advertiserId}/negativeKeywordLists"
            },
            "delete": {
              "path": "v1/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Deletes a negative keyword list given an advertiser ID and a negative keyword list ID.",
              "flatPath": "v1/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}",
              "id": "displayvideo.advertisers.negativeKeywordLists.delete"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v1/advertisers/{advertisersId}/negativeKeywordLists",
              "httpMethod": "POST",
              "id": "displayvideo.advertisers.negativeKeywordLists.create",
              "path": "v1/advertisers/{+advertiserId}/negativeKeywordLists",
              "description": "Creates a new negative keyword list. Returns the newly created negative keyword list if successful."
            },
            "patch": {
              "flatPath": "v1/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListId}",
              "description": "Updates a negative keyword list. Returns the updated negative keyword list if successful.",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.negativeKeywordLists.patch",
              "path": "v1/advertisers/{+advertiserId}/negativeKeywordLists/{negativeKeywordListId}"
            },
            "get": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v1/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}",
              "id": "displayvideo.advertisers.negativeKeywordLists.get",
              "path": "v1/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}",
              "description": "Gets a negative keyword list given an advertiser ID and a negative keyword list ID."
            }
          }
        },
        "targetingTypes": {
          "resources": {
            "assignedTargetingOptions": {
              "methods": {
                "get": {
                  "description": "Gets a single targeting option assigned to an advertiser.",
                  "path": "v1/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v1/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "httpMethod": "GET",
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.get"
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v1/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "description": "Lists the targeting options assigned to an advertiser.",
                  "path": "v1/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "httpMethod": "GET",
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.list"
                },
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v1/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "description": "Deletes an assigned targeting option from an advertiser.",
                  "httpMethod": "DELETE",
                  "flatPath": "v1/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.delete"
                },
                "create": {
                  "flatPath": "v1/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "path": "v1/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "httpMethod": "POST",
                  "description": "Assigns a targeting option to an advertiser. Returns the assigned targeting option if successful.",
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                }
              }
            }
          }
        },
        "locationLists": {
          "resources": {
            "assignedLocations": {
              "methods": {
                "create": {
                  "description": "Creates an assignment between a location and a location list.",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.create",
                  "path": "v1/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "flatPath": "v1/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "bulkEdit": {
                  "httpMethod": "POST",
                  "description": "Bulk edits multiple assignments between locations and a single location list. The operation will delete the assigned locations provided in BulkEditAssignedLocationsRequest.deleted_assigned_locations and then create the assigned locations provided in BulkEditAssignedLocationsRequest.created_assigned_locations.",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.bulkEdit",
                  "path": "v1/advertisers/{advertiserId}/locationLists/{+locationListId}/assignedLocations:bulkEdit",
                  "flatPath": "v1/advertisers/{advertiserId}/locationLists/{locationListsId}/assignedLocations:bulkEdit",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "list": {
                  "flatPath": "v1/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v1/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.list",
                  "description": "Lists locations assigned to a location list."
                },
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v1/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations/{+assignedLocationId}",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.delete",
                  "flatPath": "v1/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations/{assignedLocationsId}",
                  "httpMethod": "DELETE",
                  "description": "Deletes the assignment between a location and a location list."
                }
              }
            }
          },
          "methods": {
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Updates a location list. Returns the updated location list if successful.",
              "httpMethod": "PATCH",
              "path": "v1/advertisers/{+advertiserId}/locationLists/{locationListId}",
              "flatPath": "v1/advertisers/{advertisersId}/locationLists/{locationListId}",
              "id": "displayvideo.advertisers.locationLists.patch"
            },
            "list": {
              "description": "Lists location lists based on a given advertiser id.",
              "path": "v1/advertisers/{+advertiserId}/locationLists",
              "httpMethod": "GET",
              "flatPath": "v1/advertisers/{advertisersId}/locationLists",
              "id": "displayvideo.advertisers.locationLists.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "get": {
              "flatPath": "v1/advertisers/{advertisersId}/locationLists/{locationListsId}",
              "description": "Gets a location list.",
              "path": "v1/advertisers/{+advertiserId}/locationLists/{+locationListId}",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.locationLists.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "create": {
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.locationLists.create",
              "flatPath": "v1/advertisers/{advertisersId}/locationLists",
              "path": "v1/advertisers/{+advertiserId}/locationLists",
              "description": "Creates a new location list. Returns the newly created location list if successful."
            }
          }
        },
        "channels": {
          "resources": {
            "sites": {
              "methods": {
                "bulkEdit": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v1/advertisers/{advertiserId}/channels/{+channelId}/sites:bulkEdit",
                  "description": "Bulk edits sites under a single channel. The operation will delete the sites provided in BulkEditSitesRequest.deleted_sites and then create the sites provided in BulkEditSitesRequest.created_sites.",
                  "flatPath": "v1/advertisers/{advertiserId}/channels/{channelsId}/sites:bulkEdit",
                  "id": "displayvideo.advertisers.channels.sites.bulkEdit",
                  "httpMethod": "POST"
                },
                "create": {
                  "id": "displayvideo.advertisers.channels.sites.create",
                  "flatPath": "v1/advertisers/{advertiserId}/channels/{channelsId}/sites",
                  "path": "v1/advertisers/{advertiserId}/channels/{+channelId}/sites",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Creates a site in a channel.",
                  "httpMethod": "POST"
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v1/advertisers/{advertisersId}/channels/{channelsId}/sites",
                  "id": "displayvideo.advertisers.channels.sites.list",
                  "path": "v1/advertisers/{+advertiserId}/channels/{+channelId}/sites",
                  "description": "Lists sites in a channel.",
                  "httpMethod": "GET"
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "id": "displayvideo.advertisers.channels.sites.delete",
                  "description": "Deletes a site from a channel.",
                  "path": "v1/advertisers/{advertiserId}/channels/{+channelId}/sites/{+urlOrAppId}",
                  "flatPath": "v1/advertisers/{advertiserId}/channels/{channelsId}/sites/{sitesId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                }
              }
            }
          },
          "methods": {
            "list": {
              "id": "displayvideo.advertisers.channels.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists channels for a partner or advertiser.",
              "path": "v1/advertisers/{+advertiserId}/channels",
              "httpMethod": "GET",
              "flatPath": "v1/advertisers/{advertisersId}/channels"
            },
            "create": {
              "description": "Creates a new channel. Returns the newly created channel if successful.",
              "id": "displayvideo.advertisers.channels.create",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "POST",
              "flatPath": "v1/advertisers/{advertisersId}/channels",
              "path": "v1/advertisers/{+advertiserId}/channels"
            },
            "patch": {
              "description": "Updates a channel. Returns the updated channel if successful.",
              "flatPath": "v1/advertisers/{advertisersId}/channels/{channelId}",
              "id": "displayvideo.advertisers.channels.patch",
              "httpMethod": "PATCH",
              "path": "v1/advertisers/{+advertiserId}/channels/{channelId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "get": {
              "path": "v1/advertisers/{+advertiserId}/channels/{+channelId}",
              "description": "Gets a channel for a partner or advertiser.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.channels.get",
              "flatPath": "v1/advertisers/{advertisersId}/channels/{channelsId}"
            }
          }
        },
        "lineItems": {
          "resources": {
            "targetingTypes": {
              "resources": {
                "assignedTargetingOptions": {
                  "methods": {
                    "delete": {
                      "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "description": "Deletes an assigned targeting option from a line item.",
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.delete",
                      "httpMethod": "DELETE",
                      "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}"
                    },
                    "get": {
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.get",
                      "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "description": "Gets a single targeting option assigned to a line item.",
                      "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "httpMethod": "GET"
                    },
                    "create": {
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "httpMethod": "POST",
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.create",
                      "description": "Assigns a targeting option to a line item. Returns the assigned targeting option if successful.",
                      "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions"
                    },
                    "list": {
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.list",
                      "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "description": "Lists the targeting options assigned to a line item."
                    }
                  }
                }
              }
            }
          },
          "methods": {
            "patch": {
              "id": "displayvideo.advertisers.lineItems.patch",
              "httpMethod": "PATCH",
              "description": "Updates an existing line item. Returns the updated line item if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}",
              "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}"
            },
            "get": {
              "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "description": "Gets a line item.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}",
              "id": "displayvideo.advertisers.lineItems.get"
            },
            "bulkEditLineItemAssignedTargetingOptions": {
              "id": "displayvideo.advertisers.lineItems.bulkEditLineItemAssignedTargetingOptions",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}:bulkEditLineItemAssignedTargetingOptions",
              "description": "Bulk edits targeting options under a single line item. The operation will delete the assigned targeting options provided in BulkEditLineItemAssignedTargetingOptionsRequest.delete_requests and then create the assigned targeting options provided in BulkEditLineItemAssignedTargetingOptionsRequest.create_requests .",
              "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}:bulkEditLineItemAssignedTargetingOptions"
            },
            "create": {
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v1/advertisers/{+advertiserId}/lineItems",
              "description": "Creates a new line item. Returns the newly created line item if successful.",
              "flatPath": "v1/advertisers/{advertisersId}/lineItems",
              "id": "displayvideo.advertisers.lineItems.create"
            },
            "bulkListLineItemAssignedTargetingOptions": {
              "id": "displayvideo.advertisers.lineItems.bulkListLineItemAssignedTargetingOptions",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}:bulkListLineItemAssignedTargetingOptions",
              "description": "Lists assigned targeting options of a line item across targeting types.",
              "httpMethod": "GET",
              "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}:bulkListLineItemAssignedTargetingOptions"
            },
            "list": {
              "path": "v1/advertisers/{+advertiserId}/lineItems",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists line items in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, line items with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "httpMethod": "GET",
              "flatPath": "v1/advertisers/{advertisersId}/lineItems",
              "id": "displayvideo.advertisers.lineItems.list"
            },
            "delete": {
              "id": "displayvideo.advertisers.lineItems.delete",
              "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}",
              "httpMethod": "DELETE",
              "description": "Deletes a line item. Returns error code `NOT_FOUND` if the line item does not exist. The line item should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}"
            }
          }
        },
        "insertionOrders": {
          "methods": {
            "create": {
              "id": "displayvideo.advertisers.insertionOrders.create",
              "description": "Creates a new insertion order. Returns the newly created insertion order if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v1/advertisers/{advertisersId}/insertionOrders",
              "httpMethod": "POST",
              "path": "v1/advertisers/{+advertiserId}/insertionOrders"
            },
            "list": {
              "path": "v1/advertisers/{+advertiserId}/insertionOrders",
              "id": "displayvideo.advertisers.insertionOrders.list",
              "flatPath": "v1/advertisers/{advertisersId}/insertionOrders",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists insertion orders in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, insertion orders with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "httpMethod": "GET"
            },
            "patch": {
              "description": "Updates an existing insertion order. Returns the updated insertion order if successful.",
              "id": "displayvideo.advertisers.insertionOrders.patch",
              "path": "v1/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}",
              "httpMethod": "PATCH",
              "flatPath": "v1/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "delete": {
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Deletes an insertion order. Returns error code `NOT_FOUND` if the insertion order does not exist. The insertion order should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it.",
              "flatPath": "v1/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "id": "displayvideo.advertisers.insertionOrders.delete",
              "path": "v1/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}"
            },
            "get": {
              "id": "displayvideo.advertisers.insertionOrders.get",
              "flatPath": "v1/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "description": "Gets an insertion order. Returns error code `NOT_FOUND` if the insertion order does not exist.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "path": "v1/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}"
            }
          }
        }
      }
    },
    "floodlightGroups": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET",
          "id": "displayvideo.floodlightGroups.get",
          "path": "v1/floodlightGroups/{+floodlightGroupId}",
          "description": "Gets a Floodlight group.",
          "flatPath": "v1/floodlightGroups/{floodlightGroupsId}"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "PATCH",
          "flatPath": "v1/floodlightGroups/{floodlightGroupId}",
          "description": "Updates an existing Floodlight group. Returns the updated Floodlight group if successful.",
          "id": "displayvideo.floodlightGroups.patch",
          "path": "v1/floodlightGroups/{floodlightGroupId}"
        }
      }
    },
    "inventorySources": {
      "methods": {
        "list": {
          "id": "displayvideo.inventorySources.list",
          "description": "Lists inventory sources that are accessible to the current user. The order is defined by the order_by parameter. If a filter by entity_status is not specified, inventory sources with entity status `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET",
          "flatPath": "v1/inventorySources",
          "path": "v1/inventorySources"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Gets an inventory source.",
          "httpMethod": "GET",
          "flatPath": "v1/inventorySources/{inventorySourcesId}",
          "id": "displayvideo.inventorySources.get",
          "path": "v1/inventorySources/{+inventorySourceId}"
        }
      }
    },
    "firstAndThirdPartyAudiences": {
      "methods": {
        "list": {
          "path": "v1/firstAndThirdPartyAudiences",
          "id": "displayvideo.firstAndThirdPartyAudiences.list",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v1/firstAndThirdPartyAudiences",
          "httpMethod": "GET",
          "description": "Lists first and third party audiences. The order is defined by the order_by parameter."
        },
        "get": {
          "path": "v1/firstAndThirdPartyAudiences/{+firstAndThirdPartyAudienceId}",
          "description": "Gets a first and third party audience.",
          "flatPath": "v1/firstAndThirdPartyAudiences/{firstAndThirdPartyAudiencesId}",
          "httpMethod": "GET",
          "id": "displayvideo.firstAndThirdPartyAudiences.get",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      }
    }
  },
  "description": "Display & Video 360 API allows users to manage and create campaigns and reports.",
  "canonicalName": "Display Video",
  "version_module": true,
  "fullyEncodeReservedExpansion": true,
  "baseUrl": "https://displayvideo.googleapis.com/",
  "servicePath": "",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/display-video-user-management": {
          "description": "New Service: https://www.googleapis.com/auth/display-video-user-management"
        },
        "https://www.googleapis.com/auth/doubleclickbidmanager": {
          "description": "View and manage your reports in DoubleClick Bid Manager"
        },
        "https://www.googleapis.com/auth/display-video": {
          "description": "Create, see, edit, and permanently delete your Display & Video 360 entities and reports"
        },
        "https://www.googleapis.com/auth/display-video-mediaplanning": {
          "description": "Create, see, and edit Display & Video 360 Campaign entities and see billing invoices"
        }
      }
    }
  }
}
