{
  "ownerDomain": "google.com",
  "description": "Reads and writes Google Docs documents.",
  "protocol": "rest",
  "servicePath": "",
  "mtlsRootUrl": "https://docs.mtls.googleapis.com/",
  "rootUrl": "https://docs.googleapis.com/",
  "resources": {
    "documents": {
      "methods": {
        "create": {
          "id": "docs.documents.create",
          "description": "Creates a blank document using the title given in the request. Other fields in the request, including any provided content, are ignored. Returns the created document.",
          "flatPath": "v1/documents",
          "scopes": [
            "https://www.googleapis.com/auth/documents",
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "httpMethod": "POST",
          "path": "v1/documents"
        },
        "batchUpdate": {
          "description": "Applies one or more updates to the document. Each request is validated before being applied. If any request is not valid, then the entire request will fail and nothing will be applied. Some requests have replies to give you some information about how they are applied. Other requests do not need to return information; these each return an empty reply. The order of replies matches that of the requests. For example, suppose you call batchUpdate with four updates, and only [...]",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/documents",
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "docs.documents.batchUpdate",
          "flatPath": "v1/documents/{documentId}:batchUpdate",
          "path": "v1/documents/{documentId}:batchUpdate"
        },
        "get": {
          "flatPath": "v1/documents/{documentId}",
          "id": "docs.documents.get",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/documents",
            "https://www.googleapis.com/auth/documents.readonly",
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "path": "v1/documents/{documentId}",
          "description": "Gets the latest version of the specified document."
        }
      }
    }
  },
  "name": "docs",
  "ownerName": "Google",
  "version_module": true,
  "canonicalName": "Docs",
  "kind": "discovery#restDescription",
  "baseUrl": "https://docs.googleapis.com/",
  "id": "docs:v1",
  "discoveryVersion": "v1",
  "basePath": "",
  "title": "Google Docs API",
  "batchPath": "batch",
  "documentationLink": "https://developers.google.com/docs/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/drive.readonly": {
          "description": "See and download all your Google Drive files"
        },
        "https://www.googleapis.com/auth/documents": {
          "description": "See, create, and edit all Google Docs documents you have access to"
        },
        "https://www.googleapis.com/auth/drive.file": {
          "description": "View and manage Google Drive files and folders that you have opened or created with this app"
        },
        "https://www.googleapis.com/auth/documents.readonly": {
          "description": "View your Google Docs documents"
        },
        "https://www.googleapis.com/auth/drive": {
          "description": "See, edit, create, and delete all of your Google Drive files"
        }
      }
    }
  },
  "revision": "20210211",
  "fullyEncodeReservedExpansion": true,
  "version": "v1"
}
