{
 "kind": "discovery#restDescription",
 "etag": "\"-2NioU2H8y8siEzrBOV_qzRI6kQ/PfnNs6540GtpSJ-y6RmFD__VKLE\"",
 "discoveryVersion": "v1",
 "id": "drive:v3",
 "name": "drive",
 "version": "v3",
 "revision": "20210207",
 "title": "Drive API",
 "description": "Manages files in Drive including uploading, downloading, searching, detecting changes, and updating sharing permissions.",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "documentationLink": "https://developers.google.com/drive/",
 "protocol": "rest",
 "baseUrl": "https://www.googleapis.com/drive/v3/",
 "basePath": "/drive/v3/",
 "rootUrl": "https://www.googleapis.com/",
 "servicePath": "drive/v3/",
 "batchPath": "batch/drive/v3",
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/drive": {
     "description": "See, edit, create, and delete all of your Google Drive files"
    },
    "https://www.googleapis.com/auth/drive.appdata": {
     "description": "See, create, and delete its own configuration data in your Google Drive"
    },
    "https://www.googleapis.com/auth/drive.file": {
     "description": "View and manage Google Drive files and folders that you have opened or created with this app"
    },
    "https://www.googleapis.com/auth/drive.metadata": {
     "description": "View and manage metadata of files in your Google Drive"
    },
    "https://www.googleapis.com/auth/drive.metadata.readonly": {
     "description": "See information about your Google Drive files"
    },
    "https://www.googleapis.com/auth/drive.photos.readonly": {
     "description": "View the photos, videos and albums in your Google Photos"
    },
    "https://www.googleapis.com/auth/drive.readonly": {
     "description": "See and download all your Google Drive files"
    },
    "https://www.googleapis.com/auth/drive.scripts": {
     "description": "Modify your Google Apps Script scripts' behavior"
    }
   }
  }
 },
 "resources": {
  "about": {
   "methods": {
    "get": {
     "id": "drive.about.get",
     "path": "about",
     "httpMethod": "GET",
     "description": "Gets information about the user, the user's Drive, and system capabilities.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.appdata",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/drive.metadata",
      "https://www.googleapis.com/auth/drive.metadata.readonly",
      "https://www.googleapis.com/auth/drive.photos.readonly",
      "https://www.googleapis.com/auth/drive.readonly"
     ]
    }
   }
  },
  "changes": {
   "methods": {
    "getStartPageToken": {
     "id": "drive.changes.getStartPageToken",
     "path": "changes/startPageToken",
     "httpMethod": "GET",
     "description": "Gets the starting pageToken for listing future changes.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.appdata",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/drive.metadata",
      "https://www.googleapis.com/auth/drive.metadata.readonly",
      "https://www.googleapis.com/auth/drive.photos.readonly",
      "https://www.googleapis.com/auth/drive.readonly"
     ]
    },
    "list": {
     "id": "drive.changes.list",
     "path": "changes",
     "httpMethod": "GET",
     "description": "Lists the changes for a user or shared drive.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.appdata",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/drive.metadata",
      "https://www.googleapis.com/auth/drive.metadata.readonly",
      "https://www.googleapis.com/auth/drive.photos.readonly",
      "https://www.googleapis.com/auth/drive.readonly"
     ],
     "supportsSubscription": true
    },
    "watch": {
     "id": "drive.changes.watch",
     "path": "changes/watch",
     "httpMethod": "POST",
     "description": "Subscribes to changes for a user.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.appdata",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/drive.metadata",
      "https://www.googleapis.com/auth/drive.metadata.readonly",
      "https://www.googleapis.com/auth/drive.photos.readonly",
      "https://www.googleapis.com/auth/drive.readonly"
     ],
     "supportsSubscription": true
    }
   }
  },
  "channels": {
   "methods": {
    "stop": {
     "id": "drive.channels.stop",
     "path": "channels/stop",
     "httpMethod": "POST",
     "description": "Stop watching resources through this channel",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.appdata",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/drive.metadata",
      "https://www.googleapis.com/auth/drive.metadata.readonly",
      "https://www.googleapis.com/auth/drive.photos.readonly",
      "https://www.googleapis.com/auth/drive.readonly"
     ]
    }
   }
  },
  "comments": {
   "methods": {
    "create": {
     "id": "drive.comments.create",
     "path": "files/{fileId}/comments",
     "httpMethod": "POST",
     "description": "Creates a new comment on a file.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file"
     ]
    },
    "delete": {
     "id": "drive.comments.delete",
     "path": "files/{fileId}/comments/{commentId}",
     "httpMethod": "DELETE",
     "description": "Deletes a comment.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file"
     ]
    },
    "get": {
     "id": "drive.comments.get",
     "path": "files/{fileId}/comments/{commentId}",
     "httpMethod": "GET",
     "description": "Gets a comment by ID.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/drive.readonly"
     ]
    },
    "list": {
     "id": "drive.comments.list",
     "path": "files/{fileId}/comments",
     "httpMethod": "GET",
     "description": "Lists a file's comments.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/drive.readonly"
     ]
    },
    "update": {
     "id": "drive.comments.update",
     "path": "files/{fileId}/comments/{commentId}",
     "httpMethod": "PATCH",
     "description": "Updates a comment with patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file"
     ]
    }
   }
  },
  "drives": {
   "methods": {
    "create": {
     "id": "drive.drives.create",
     "path": "drives",
     "httpMethod": "POST",
     "description": "Creates a new shared drive.",
     "scopes": [
      "https://www.googleapis.com/auth/drive"
     ]
    },
    "delete": {
     "id": "drive.drives.delete",
     "path": "drives/{driveId}",
     "httpMethod": "DELETE",
     "description": "Permanently deletes a shared drive for which the user is an organizer. The shared drive cannot contain any untrashed items.",
     "scopes": [
      "https://www.googleapis.com/auth/drive"
     ]
    },
    "get": {
     "id": "drive.drives.get",
     "path": "drives/{driveId}",
     "httpMethod": "GET",
     "description": "Gets a shared drive's metadata by ID.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.readonly"
     ]
    },
    "hide": {
     "id": "drive.drives.hide",
     "path": "drives/{driveId}/hide",
     "httpMethod": "POST",
     "description": "Hides a shared drive from the default view.",
     "scopes": [
      "https://www.googleapis.com/auth/drive"
     ]
    },
    "list": {
     "id": "drive.drives.list",
     "path": "drives",
     "httpMethod": "GET",
     "description": "Lists the user's shared drives.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.readonly"
     ]
    },
    "unhide": {
     "id": "drive.drives.unhide",
     "path": "drives/{driveId}/unhide",
     "httpMethod": "POST",
     "description": "Restores a shared drive to the default view.",
     "scopes": [
      "https://www.googleapis.com/auth/drive"
     ]
    },
    "update": {
     "id": "drive.drives.update",
     "path": "drives/{driveId}",
     "httpMethod": "PATCH",
     "description": "Updates the metadate for a shared drive.",
     "scopes": [
      "https://www.googleapis.com/auth/drive"
     ]
    }
   }
  },
  "files": {
   "methods": {
    "copy": {
     "id": "drive.files.copy",
     "path": "files/{fileId}/copy",
     "httpMethod": "POST",
     "description": "Creates a copy of a file and applies any requested updates with patch semantics. Folders cannot be copied.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.appdata",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/drive.photos.readonly"
     ]
    },
    "create": {
     "id": "drive.files.create",
     "path": "files",
     "httpMethod": "POST",
     "description": "Creates a new file.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.appdata",
      "https://www.googleapis.com/auth/drive.file"
     ],
     "supportsMediaUpload": true,
     "supportsSubscription": true
    },
    "delete": {
     "id": "drive.files.delete",
     "path": "files/{fileId}",
     "httpMethod": "DELETE",
     "description": "Permanently deletes a file owned by the user without moving it to the trash. If the file belongs to a shared drive the user must be an organizer on the parent. If the target is a folder, all descendants owned by the user are also deleted.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.appdata",
      "https://www.googleapis.com/auth/drive.file"
     ]
    },
    "emptyTrash": {
     "id": "drive.files.emptyTrash",
     "path": "files/trash",
     "httpMethod": "DELETE",
     "description": "Permanently deletes all of the user's trashed files.",
     "scopes": [
      "https://www.googleapis.com/auth/drive"
     ]
    },
    "export": {
     "id": "drive.files.export",
     "path": "files/{fileId}/export",
     "httpMethod": "GET",
     "description": "Exports a Google Doc to the requested MIME type and returns the exported content. Please note that the exported content is limited to 10MB.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/drive.readonly"
     ],
     "supportsMediaDownload": true
    },
    "generateIds": {
     "id": "drive.files.generateIds",
     "path": "files/generateIds",
     "httpMethod": "GET",
     "description": "Generates a set of file IDs which can be provided in create or copy requests.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.appdata",
      "https://www.googleapis.com/auth/drive.file"
     ]
    },
    "get": {
     "id": "drive.files.get",
     "path": "files/{fileId}",
     "httpMethod": "GET",
     "description": "Gets a file's metadata or content by ID.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.appdata",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/drive.metadata",
      "https://www.googleapis.com/auth/drive.metadata.readonly",
      "https://www.googleapis.com/auth/drive.photos.readonly",
      "https://www.googleapis.com/auth/drive.readonly"
     ],
     "supportsMediaDownload": true,
     "useMediaDownloadService": true,
     "supportsSubscription": true
    },
    "list": {
     "id": "drive.files.list",
     "path": "files",
     "httpMethod": "GET",
     "description": "Lists or searches files.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.appdata",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/drive.metadata",
      "https://www.googleapis.com/auth/drive.metadata.readonly",
      "https://www.googleapis.com/auth/drive.photos.readonly",
      "https://www.googleapis.com/auth/drive.readonly"
     ]
    },
    "update": {
     "id": "drive.files.update",
     "path": "files/{fileId}",
     "httpMethod": "PATCH",
     "description": "Updates a file's metadata and/or content. This method supports patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.appdata",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/drive.metadata",
      "https://www.googleapis.com/auth/drive.scripts"
     ],
     "supportsMediaUpload": true
    },
    "watch": {
     "id": "drive.files.watch",
     "path": "files/{fileId}/watch",
     "httpMethod": "POST",
     "description": "Subscribes to changes to a file",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.appdata",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/drive.metadata",
      "https://www.googleapis.com/auth/drive.metadata.readonly",
      "https://www.googleapis.com/auth/drive.photos.readonly",
      "https://www.googleapis.com/auth/drive.readonly"
     ],
     "supportsMediaDownload": true,
     "useMediaDownloadService": true,
     "supportsSubscription": true
    }
   }
  },
  "permissions": {
   "methods": {
    "create": {
     "id": "drive.permissions.create",
     "path": "files/{fileId}/permissions",
     "httpMethod": "POST",
     "description": "Creates a permission for a file or shared drive.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file"
     ]
    },
    "delete": {
     "id": "drive.permissions.delete",
     "path": "files/{fileId}/permissions/{permissionId}",
     "httpMethod": "DELETE",
     "description": "Deletes a permission.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file"
     ]
    },
    "get": {
     "id": "drive.permissions.get",
     "path": "files/{fileId}/permissions/{permissionId}",
     "httpMethod": "GET",
     "description": "Gets a permission by ID.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/drive.metadata",
      "https://www.googleapis.com/auth/drive.metadata.readonly",
      "https://www.googleapis.com/auth/drive.photos.readonly",
      "https://www.googleapis.com/auth/drive.readonly"
     ]
    },
    "list": {
     "id": "drive.permissions.list",
     "path": "files/{fileId}/permissions",
     "httpMethod": "GET",
     "description": "Lists a file's or shared drive's permissions.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/drive.metadata",
      "https://www.googleapis.com/auth/drive.metadata.readonly",
      "https://www.googleapis.com/auth/drive.photos.readonly",
      "https://www.googleapis.com/auth/drive.readonly"
     ]
    },
    "update": {
     "id": "drive.permissions.update",
     "path": "files/{fileId}/permissions/{permissionId}",
     "httpMethod": "PATCH",
     "description": "Updates a permission with patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file"
     ]
    }
   }
  },
  "replies": {
   "methods": {
    "create": {
     "id": "drive.replies.create",
     "path": "files/{fileId}/comments/{commentId}/replies",
     "httpMethod": "POST",
     "description": "Creates a new reply to a comment.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file"
     ]
    },
    "delete": {
     "id": "drive.replies.delete",
     "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
     "httpMethod": "DELETE",
     "description": "Deletes a reply.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file"
     ]
    },
    "get": {
     "id": "drive.replies.get",
     "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
     "httpMethod": "GET",
     "description": "Gets a reply by ID.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/drive.readonly"
     ]
    },
    "list": {
     "id": "drive.replies.list",
     "path": "files/{fileId}/comments/{commentId}/replies",
     "httpMethod": "GET",
     "description": "Lists a comment's replies.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/drive.readonly"
     ]
    },
    "update": {
     "id": "drive.replies.update",
     "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
     "httpMethod": "PATCH",
     "description": "Updates a reply with patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file"
     ]
    }
   }
  },
  "revisions": {
   "methods": {
    "delete": {
     "id": "drive.revisions.delete",
     "path": "files/{fileId}/revisions/{revisionId}",
     "httpMethod": "DELETE",
     "description": "Permanently deletes a file version. You can only delete revisions for files with binary content in Google Drive, like images or videos. Revisions for other files, like Google Docs or Sheets, and the last remaining file version can't be deleted.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.appdata",
      "https://www.googleapis.com/auth/drive.file"
     ]
    },
    "get": {
     "id": "drive.revisions.get",
     "path": "files/{fileId}/revisions/{revisionId}",
     "httpMethod": "GET",
     "description": "Gets a revision's metadata or content by ID.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.appdata",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/drive.metadata",
      "https://www.googleapis.com/auth/drive.metadata.readonly",
      "https://www.googleapis.com/auth/drive.photos.readonly",
      "https://www.googleapis.com/auth/drive.readonly"
     ],
     "supportsMediaDownload": true,
     "useMediaDownloadService": true
    },
    "list": {
     "id": "drive.revisions.list",
     "path": "files/{fileId}/revisions",
     "httpMethod": "GET",
     "description": "Lists a file's revisions.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.appdata",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/drive.metadata",
      "https://www.googleapis.com/auth/drive.metadata.readonly",
      "https://www.googleapis.com/auth/drive.photos.readonly",
      "https://www.googleapis.com/auth/drive.readonly"
     ]
    },
    "update": {
     "id": "drive.revisions.update",
     "path": "files/{fileId}/revisions/{revisionId}",
     "httpMethod": "PATCH",
     "description": "Updates a revision with patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.appdata",
      "https://www.googleapis.com/auth/drive.file"
     ]
    }
   }
  },
  "teamdrives": {
   "methods": {
    "create": {
     "id": "drive.teamdrives.create",
     "path": "teamdrives",
     "httpMethod": "POST",
     "description": "Deprecated use drives.create instead.",
     "scopes": [
      "https://www.googleapis.com/auth/drive"
     ]
    },
    "delete": {
     "id": "drive.teamdrives.delete",
     "path": "teamdrives/{teamDriveId}",
     "httpMethod": "DELETE",
     "description": "Deprecated use drives.delete instead.",
     "scopes": [
      "https://www.googleapis.com/auth/drive"
     ]
    },
    "get": {
     "id": "drive.teamdrives.get",
     "path": "teamdrives/{teamDriveId}",
     "httpMethod": "GET",
     "description": "Deprecated use drives.get instead.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.readonly"
     ]
    },
    "list": {
     "id": "drive.teamdrives.list",
     "path": "teamdrives",
     "httpMethod": "GET",
     "description": "Deprecated use drives.list instead.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.readonly"
     ]
    },
    "update": {
     "id": "drive.teamdrives.update",
     "path": "teamdrives/{teamDriveId}",
     "httpMethod": "PATCH",
     "description": "Deprecated use drives.update instead",
     "scopes": [
      "https://www.googleapis.com/auth/drive"
     ]
    }
   }
  }
 }
}
