{
  "kind": "discovery#restDescription",
  "id": "games:v1",
  "title": "Google Play Game Services",
  "batchPath": "batch",
  "servicePath": "",
  "rootUrl": "https://games.googleapis.com/",
  "description": "The Google Play games service allows developers to enhance games with social leaderboards, achievements, game state, sign-in with Google, and more.",
  "discoveryVersion": "v1",
  "revision": "20210121",
  "ownerDomain": "google.com",
  "baseUrl": "https://games.googleapis.com/",
  "name": "games",
  "ownerName": "Google",
  "canonicalName": "Games",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/games": {
          "description": "Create, edit, and delete your Google Play Games activity"
        },
        "https://www.googleapis.com/auth/drive.appdata": {
          "description": "View and manage its own configuration data in your Google Drive"
        }
      }
    }
  },
  "version": "v1",
  "mtlsRootUrl": "https://games.mtls.googleapis.com/",
  "resources": {
    "metagame": {
      "methods": {
        "getMetagameConfig": {
          "description": "Return the metagame configuration data for the calling application.",
          "path": "games/v1/metagameConfig",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.metagame.getMetagameConfig",
          "flatPath": "games/v1/metagameConfig"
        },
        "listCategoriesByPlayer": {
          "httpMethod": "GET",
          "id": "games.metagame.listCategoriesByPlayer",
          "flatPath": "games/v1/players/{playerId}/categories/{collection}",
          "description": "List play data aggregated per category for the player corresponding to `playerId`.",
          "path": "games/v1/players/{playerId}/categories/{collection}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    },
    "snapshotsExtended": {
      "methods": {
        "resolveSnapshotHead": {
          "scopes": [
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Resolves any potential conflicts according to the resolution policy specified in the request and returns the snapshot head after the resolution.",
          "path": "games/v1/snapshotsExtended/{snapshotName}:resolveHead",
          "flatPath": "games/v1/snapshotsExtended/{snapshotName}:resolveHead",
          "httpMethod": "POST",
          "id": "games.snapshotsExtended.resolveSnapshotHead"
        }
      }
    },
    "stats": {
      "methods": {
        "get": {
          "path": "games/v1/stats",
          "description": "Returns engagement and spend statistics in this application for the currently authenticated user.",
          "id": "games.stats.get",
          "httpMethod": "GET",
          "flatPath": "games/v1/stats",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    },
    "achievements": {
      "methods": {
        "setStepsAtLeast": {
          "flatPath": "games/v1/achievements/{achievementId}/setStepsAtLeast",
          "id": "games.achievements.setStepsAtLeast",
          "httpMethod": "POST",
          "description": "Sets the steps for the currently authenticated player towards unlocking an achievement. If the steps parameter is less than the current number of steps that the player already gained for the achievement, the achievement is not modified.",
          "path": "games/v1/achievements/{achievementId}/setStepsAtLeast",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "updateMultiple": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/achievements/updateMultiple",
          "id": "games.achievements.updateMultiple",
          "description": "Updates multiple achievements for the currently authenticated player.",
          "httpMethod": "POST",
          "path": "games/v1/achievements/updateMultiple"
        },
        "reveal": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.achievements.reveal",
          "path": "games/v1/achievements/{achievementId}/reveal",
          "httpMethod": "POST",
          "description": "Sets the state of the achievement with the given ID to `REVEALED` for the currently authenticated player.",
          "flatPath": "games/v1/achievements/{achievementId}/reveal"
        },
        "unlock": {
          "description": "Unlocks this achievement for the currently authenticated player.",
          "id": "games.achievements.unlock",
          "path": "games/v1/achievements/{achievementId}/unlock",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/achievements/{achievementId}/unlock",
          "httpMethod": "POST"
        },
        "list": {
          "path": "games/v1/players/{playerId}/achievements",
          "flatPath": "games/v1/players/{playerId}/achievements",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Lists the progress for all your application's achievements for the currently authenticated player.",
          "id": "games.achievements.list"
        },
        "increment": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.achievements.increment",
          "path": "games/v1/achievements/{achievementId}/increment",
          "description": "Increments the steps of the achievement with the given ID for the currently authenticated player.",
          "httpMethod": "POST",
          "flatPath": "games/v1/achievements/{achievementId}/increment"
        }
      }
    },
    "revisions": {
      "methods": {
        "check": {
          "flatPath": "games/v1/revisions/check",
          "description": "Checks whether the games client is out of date.",
          "httpMethod": "GET",
          "id": "games.revisions.check",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/revisions/check"
        }
      }
    },
    "players": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/players/{playerId}",
          "path": "games/v1/players/{playerId}",
          "description": "Retrieves the Player resource with the given ID. To retrieve the player for the currently authenticated user, set `playerId` to `me`.",
          "id": "games.players.get",
          "httpMethod": "GET"
        },
        "list": {
          "description": "Get the collection of players for the currently authenticated user.",
          "path": "games/v1/players/me/players/{collection}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.players.list",
          "httpMethod": "GET",
          "flatPath": "games/v1/players/me/players/{collection}"
        }
      }
    },
    "snapshots": {
      "methods": {
        "list": {
          "path": "games/v1/players/{playerId}/snapshots",
          "httpMethod": "GET",
          "flatPath": "games/v1/players/{playerId}/snapshots",
          "id": "games.snapshots.list",
          "scopes": [
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Retrieves a list of snapshots created by your application for the player corresponding to the player ID."
        },
        "get": {
          "path": "games/v1/snapshots/{snapshotId}",
          "flatPath": "games/v1/snapshots/{snapshotId}",
          "description": "Retrieves the metadata for a given snapshot ID.",
          "httpMethod": "GET",
          "id": "games.snapshots.get",
          "scopes": [
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    },
    "scores": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "GET",
          "path": "games/v1/players/{playerId}/leaderboards/{leaderboardId}/scores/{timeSpan}",
          "description": "Get high scores, and optionally ranks, in leaderboards for the currently authenticated player. For a specific time span, `leaderboardId` can be set to `ALL` to retrieve data for all leaderboards in a given time span. `NOTE: You cannot ask for 'ALL' leaderboards and 'ALL' timeSpans in the same request; only one parameter may be set to 'ALL'.",
          "id": "games.scores.get",
          "flatPath": "games/v1/players/{playerId}/leaderboards/{leaderboardId}/scores/{timeSpan}"
        },
        "listWindow": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.scores.listWindow",
          "path": "games/v1/leaderboards/{leaderboardId}/window/{collection}",
          "description": "Lists the scores in a leaderboard around (and including) a player's score.",
          "flatPath": "games/v1/leaderboards/{leaderboardId}/window/{collection}"
        },
        "list": {
          "description": "Lists the scores in a leaderboard, starting from the top.",
          "flatPath": "games/v1/leaderboards/{leaderboardId}/scores/{collection}",
          "id": "games.scores.list",
          "path": "games/v1/leaderboards/{leaderboardId}/scores/{collection}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "submitMultiple": {
          "flatPath": "games/v1/leaderboards/scores",
          "id": "games.scores.submitMultiple",
          "path": "games/v1/leaderboards/scores",
          "description": "Submits multiple scores to leaderboards.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "submit": {
          "description": "Submits a score to the specified leaderboard.",
          "httpMethod": "POST",
          "flatPath": "games/v1/leaderboards/{leaderboardId}/scores",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.scores.submit",
          "path": "games/v1/leaderboards/{leaderboardId}/scores"
        }
      }
    },
    "applications": {
      "methods": {
        "getEndPoint": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/applications/getEndPoint",
          "path": "games/v1/applications/getEndPoint",
          "httpMethod": "POST",
          "description": "Returns a URL for the requested end point type.",
          "id": "games.applications.getEndPoint"
        },
        "verify": {
          "path": "games/v1/applications/{applicationId}/verify",
          "flatPath": "games/v1/applications/{applicationId}/verify",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.applications.verify",
          "httpMethod": "GET",
          "description": "Verifies the auth token provided with this request is for the application with the specified ID, and returns the ID of the player it was granted for."
        },
        "played": {
          "id": "games.applications.played",
          "httpMethod": "POST",
          "description": "Indicate that the currently authenticated user is playing your application.",
          "flatPath": "games/v1/applications/played",
          "path": "games/v1/applications/played",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "get": {
          "flatPath": "games/v1/applications/{applicationId}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/applications/{applicationId}",
          "httpMethod": "GET",
          "id": "games.applications.get",
          "description": "Retrieves the metadata of the application with the given ID. If the requested application is not available for the specified `platformType`, the returned response will not include any instance data."
        }
      }
    },
    "achievementDefinitions": {
      "methods": {
        "list": {
          "path": "games/v1/achievements",
          "flatPath": "games/v1/achievements",
          "httpMethod": "GET",
          "id": "games.achievementDefinitions.list",
          "description": "Lists all the achievement definitions for your application.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    },
    "leaderboards": {
      "methods": {
        "list": {
          "path": "games/v1/leaderboards",
          "id": "games.leaderboards.list",
          "flatPath": "games/v1/leaderboards",
          "description": "Lists all the leaderboard metadata for your application.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "GET"
        },
        "get": {
          "id": "games.leaderboards.get",
          "path": "games/v1/leaderboards/{leaderboardId}",
          "httpMethod": "GET",
          "flatPath": "games/v1/leaderboards/{leaderboardId}",
          "description": "Retrieves the metadata of the leaderboard with the given ID.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    },
    "events": {
      "methods": {
        "record": {
          "path": "games/v1/events",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Records a batch of changes to the number of times events have occurred for the currently authenticated user of this application.",
          "id": "games.events.record",
          "flatPath": "games/v1/events"
        },
        "listByPlayer": {
          "path": "games/v1/events",
          "flatPath": "games/v1/events",
          "description": "Returns a list showing the current progress on events in this application for the currently authenticated user.",
          "id": "games.events.listByPlayer",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "listDefinitions": {
          "description": "Returns a list of the event definitions in this application.",
          "path": "games/v1/eventDefinitions",
          "httpMethod": "GET",
          "id": "games.events.listDefinitions",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/eventDefinitions"
        }
      }
    }
  },
  "documentationLink": "https://developers.google.com/games/",
  "basePath": "",
  "protocol": "rest"
}
