{
  "description": "The Google Play games service allows developers to enhance games with social leaderboards, achievements, game state, sign-in with Google, and more.",
  "canonicalName": "Games",
  "batchPath": "batch",
  "servicePath": "",
  "ownerName": "Google",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/games": {
          "description": "Create, edit, and delete your Google Play Games activity"
        },
        "https://www.googleapis.com/auth/drive.appdata": {
          "description": "View and manage its own configuration data in your Google Drive"
        }
      }
    }
  },
  "title": "Google Play Game Services",
  "ownerDomain": "google.com",
  "version": "v1",
  "name": "games",
  "revision": "20201022",
  "basePath": "",
  "mtlsRootUrl": "https://games.mtls.googleapis.com/",
  "discoveryVersion": "v1",
  "rootUrl": "https://games.googleapis.com/",
  "baseUrl": "https://games.googleapis.com/",
  "kind": "discovery#restDescription",
  "resources": {
    "players": {
      "methods": {
        "get": {
          "id": "games.players.get",
          "path": "games/v1/players/{playerId}",
          "httpMethod": "GET",
          "flatPath": "games/v1/players/{playerId}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Retrieves the Player resource with the given ID. To retrieve the player for the currently authenticated user, set `playerId` to `me`."
        },
        "list": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/players/me/players/{collection}",
          "description": "Get the collection of players for the currently authenticated user.",
          "path": "games/v1/players/me/players/{collection}",
          "id": "games.players.list"
        }
      }
    },
    "stats": {
      "methods": {
        "get": {
          "description": "Returns engagement and spend statistics in this application for the currently authenticated user.",
          "path": "games/v1/stats",
          "httpMethod": "GET",
          "id": "games.stats.get",
          "flatPath": "games/v1/stats",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    },
    "revisions": {
      "methods": {
        "check": {
          "path": "games/v1/revisions/check",
          "flatPath": "games/v1/revisions/check",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Checks whether the games client is out of date.",
          "id": "games.revisions.check",
          "httpMethod": "GET"
        }
      }
    },
    "achievements": {
      "methods": {
        "setStepsAtLeast": {
          "path": "games/v1/achievements/{achievementId}/setStepsAtLeast",
          "flatPath": "games/v1/achievements/{achievementId}/setStepsAtLeast",
          "httpMethod": "POST",
          "description": "Sets the steps for the currently authenticated player towards unlocking an achievement. If the steps parameter is less than the current number of steps that the player already gained for the achievement, the achievement is not modified.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.achievements.setStepsAtLeast"
        },
        "increment": {
          "httpMethod": "POST",
          "description": "Increments the steps of the achievement with the given ID for the currently authenticated player.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/achievements/{achievementId}/increment",
          "id": "games.achievements.increment",
          "flatPath": "games/v1/achievements/{achievementId}/increment"
        },
        "unlock": {
          "description": "Unlocks this achievement for the currently authenticated player.",
          "id": "games.achievements.unlock",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/achievements/{achievementId}/unlock",
          "flatPath": "games/v1/achievements/{achievementId}/unlock",
          "httpMethod": "POST"
        },
        "reveal": {
          "description": "Sets the state of the achievement with the given ID to `REVEALED` for the currently authenticated player.",
          "path": "games/v1/achievements/{achievementId}/reveal",
          "flatPath": "games/v1/achievements/{achievementId}/reveal",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "POST",
          "id": "games.achievements.reveal"
        },
        "list": {
          "flatPath": "games/v1/players/{playerId}/achievements",
          "description": "Lists the progress for all your application's achievements for the currently authenticated player.",
          "id": "games.achievements.list",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/players/{playerId}/achievements",
          "httpMethod": "GET"
        },
        "updateMultiple": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.achievements.updateMultiple",
          "path": "games/v1/achievements/updateMultiple",
          "flatPath": "games/v1/achievements/updateMultiple",
          "httpMethod": "POST",
          "description": "Updates multiple achievements for the currently authenticated player."
        }
      }
    },
    "leaderboards": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.leaderboards.get",
          "path": "games/v1/leaderboards/{leaderboardId}",
          "httpMethod": "GET",
          "flatPath": "games/v1/leaderboards/{leaderboardId}",
          "description": "Retrieves the metadata of the leaderboard with the given ID."
        },
        "list": {
          "description": "Lists all the leaderboard metadata for your application.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "GET",
          "flatPath": "games/v1/leaderboards",
          "id": "games.leaderboards.list",
          "path": "games/v1/leaderboards"
        }
      }
    },
    "snapshots": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "path": "games/v1/snapshots/{snapshotId}",
          "description": "Retrieves the metadata for a given snapshot ID.",
          "id": "games.snapshots.get",
          "flatPath": "games/v1/snapshots/{snapshotId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/games"
          ]
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/players/{playerId}/snapshots",
          "id": "games.snapshots.list",
          "httpMethod": "GET",
          "flatPath": "games/v1/players/{playerId}/snapshots",
          "description": "Retrieves a list of snapshots created by your application for the player corresponding to the player ID."
        }
      }
    },
    "metagame": {
      "methods": {
        "listCategoriesByPlayer": {
          "id": "games.metagame.listCategoriesByPlayer",
          "httpMethod": "GET",
          "flatPath": "games/v1/players/{playerId}/categories/{collection}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/players/{playerId}/categories/{collection}",
          "description": "List play data aggregated per category for the player corresponding to `playerId`."
        },
        "getMetagameConfig": {
          "path": "games/v1/metagameConfig",
          "id": "games.metagame.getMetagameConfig",
          "description": "Return the metagame configuration data for the calling application.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/metagameConfig"
        }
      }
    },
    "events": {
      "methods": {
        "record": {
          "path": "games/v1/events",
          "httpMethod": "POST",
          "id": "games.events.record",
          "description": "Records a batch of changes to the number of times events have occurred for the currently authenticated user of this application.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/events"
        },
        "listDefinitions": {
          "description": "Returns a list of the event definitions in this application.",
          "flatPath": "games/v1/eventDefinitions",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/eventDefinitions",
          "httpMethod": "GET",
          "id": "games.events.listDefinitions"
        },
        "listByPlayer": {
          "path": "games/v1/events",
          "httpMethod": "GET",
          "flatPath": "games/v1/events",
          "id": "games.events.listByPlayer",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Returns a list showing the current progress on events in this application for the currently authenticated user."
        }
      }
    },
    "snapshotsExtended": {
      "methods": {
        "resolveSnapshotHead": {
          "description": "Resolves any potential conflicts according to the resolution policy specified in the request and returns the snapshot head after the resolution.",
          "id": "games.snapshotsExtended.resolveSnapshotHead",
          "httpMethod": "POST",
          "flatPath": "games/v1/snapshotsExtended/{snapshotName}:resolveHead",
          "path": "games/v1/snapshotsExtended/{snapshotName}:resolveHead",
          "scopes": [
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    },
    "applications": {
      "methods": {
        "verify": {
          "id": "games.applications.verify",
          "flatPath": "games/v1/applications/{applicationId}/verify",
          "description": "Verifies the auth token provided with this request is for the application with the specified ID, and returns the ID of the player it was granted for.",
          "httpMethod": "GET",
          "path": "games/v1/applications/{applicationId}/verify",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "get": {
          "id": "games.applications.get",
          "path": "games/v1/applications/{applicationId}",
          "httpMethod": "GET",
          "description": "Retrieves the metadata of the application with the given ID. If the requested application is not available for the specified `platformType`, the returned response will not include any instance data.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/applications/{applicationId}"
        },
        "played": {
          "flatPath": "games/v1/applications/played",
          "description": "Indicate that the currently authenticated user is playing your application.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/applications/played",
          "httpMethod": "POST",
          "id": "games.applications.played"
        }
      }
    },
    "achievementDefinitions": {
      "methods": {
        "list": {
          "id": "games.achievementDefinitions.list",
          "description": "Lists all the achievement definitions for your application.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/achievements",
          "httpMethod": "GET",
          "flatPath": "games/v1/achievements"
        }
      }
    },
    "scores": {
      "methods": {
        "submitMultiple": {
          "id": "games.scores.submitMultiple",
          "path": "games/v1/leaderboards/scores",
          "description": "Submits multiple scores to leaderboards.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/leaderboards/scores"
        },
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.scores.get",
          "description": "Get high scores, and optionally ranks, in leaderboards for the currently authenticated player. For a specific time span, `leaderboardId` can be set to `ALL` to retrieve data for all leaderboards in a given time span. `NOTE: You cannot ask for 'ALL' leaderboards and 'ALL' timeSpans in the same request; only one parameter may be set to 'ALL'.",
          "flatPath": "games/v1/players/{playerId}/leaderboards/{leaderboardId}/scores/{timeSpan}",
          "path": "games/v1/players/{playerId}/leaderboards/{leaderboardId}/scores/{timeSpan}"
        },
        "submit": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "POST",
          "path": "games/v1/leaderboards/{leaderboardId}/scores",
          "description": "Submits a score to the specified leaderboard.",
          "id": "games.scores.submit",
          "flatPath": "games/v1/leaderboards/{leaderboardId}/scores"
        },
        "list": {
          "description": "Lists the scores in a leaderboard, starting from the top.",
          "id": "games.scores.list",
          "httpMethod": "GET",
          "flatPath": "games/v1/leaderboards/{leaderboardId}/scores/{collection}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/leaderboards/{leaderboardId}/scores/{collection}"
        },
        "listWindow": {
          "path": "games/v1/leaderboards/{leaderboardId}/window/{collection}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.scores.listWindow",
          "httpMethod": "GET",
          "flatPath": "games/v1/leaderboards/{leaderboardId}/window/{collection}",
          "description": "Lists the scores in a leaderboard around (and including) a player's score."
        }
      }
    }
  },
  "protocol": "rest",
  "id": "games:v1",
  "documentationLink": "https://developers.google.com/games/"
}
