{
  "basePath": "",
  "protocol": "rest",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/gmail.addons.current.message.action": {
          "description": "View your email messages when you interact with the add-on"
        },
        "https://www.googleapis.com/auth/gmail.settings.basic": {
          "description": "See, edit, create, or change your email settings and filters in Gmail"
        },
        "https://www.googleapis.com/auth/gmail.readonly": {
          "description": "View your email messages and settings"
        },
        "https://www.googleapis.com/auth/gmail.send": {
          "description": "Send email on your behalf"
        },
        "https://www.googleapis.com/auth/gmail.addons.current.message.metadata": {
          "description": "View your email message metadata when the add-on is running"
        },
        "https://www.googleapis.com/auth/gmail.labels": {
          "description": "See and edit your email labels"
        },
        "https://www.googleapis.com/auth/gmail.addons.current.message.readonly": {
          "description": "View your email messages when the add-on is running"
        },
        "https://www.googleapis.com/auth/gmail.addons.current.action.compose": {
          "description": "Manage drafts and send emails when you interact with the add-on"
        },
        "https://www.googleapis.com/auth/gmail.modify": {
          "description": "View and modify but not delete your email"
        },
        "https://www.googleapis.com/auth/gmail.settings.sharing": {
          "description": "Manage your sensitive mail settings, including who can manage your mail"
        },
        "https://mail.google.com/": {
          "description": "Read, compose, send, and permanently delete all your email from Gmail"
        },
        "https://www.googleapis.com/auth/gmail.compose": {
          "description": "Manage drafts and send emails"
        },
        "https://www.googleapis.com/auth/gmail.metadata": {
          "description": "View your email message metadata such as labels and headers, but not the email body"
        },
        "https://www.googleapis.com/auth/gmail.insert": {
          "description": "Add emails into your Gmail mailbox"
        }
      }
    }
  },
  "kind": "discovery#restDescription",
  "name": "gmail",
  "revision": "20210301",
  "discoveryVersion": "v1",
  "title": "Gmail API",
  "ownerDomain": "google.com",
  "servicePath": "",
  "rootUrl": "https://gmail.googleapis.com/",
  "version": "v1",
  "mtlsRootUrl": "https://gmail.mtls.googleapis.com/",
  "batchPath": "batch",
  "documentationLink": "https://developers.google.com/gmail/api/",
  "id": "gmail:v1",
  "baseUrl": "https://gmail.googleapis.com/",
  "ownerName": "Google",
  "canonicalName": "Gmail",
  "resources": {
    "users": {
      "resources": {
        "threads": {
          "methods": {
            "trash": {
              "flatPath": "gmail/v1/users/{userId}/threads/{id}/trash",
              "httpMethod": "POST",
              "id": "gmail.users.threads.trash",
              "path": "gmail/v1/users/{userId}/threads/{id}/trash",
              "description": "Moves the specified thread to the trash.",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            },
            "delete": {
              "scopes": [
                "https://mail.google.com/"
              ],
              "path": "gmail/v1/users/{userId}/threads/{id}",
              "flatPath": "gmail/v1/users/{userId}/threads/{id}",
              "description": "Immediately and permanently deletes the specified thread. This operation cannot be undone. Prefer `threads.trash` instead.",
              "httpMethod": "DELETE",
              "id": "gmail.users.threads.delete"
            },
            "get": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.message.action",
                "https://www.googleapis.com/auth/gmail.addons.current.message.metadata",
                "https://www.googleapis.com/auth/gmail.addons.current.message.readonly",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "httpMethod": "GET",
              "flatPath": "gmail/v1/users/{userId}/threads/{id}",
              "id": "gmail.users.threads.get",
              "description": "Gets the specified thread.",
              "path": "gmail/v1/users/{userId}/threads/{id}"
            },
            "modify": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "httpMethod": "POST",
              "id": "gmail.users.threads.modify",
              "description": "Modifies the labels applied to the thread. This applies to all messages in the thread.",
              "flatPath": "gmail/v1/users/{userId}/threads/{id}/modify",
              "path": "gmail/v1/users/{userId}/threads/{id}/modify"
            },
            "list": {
              "httpMethod": "GET",
              "path": "gmail/v1/users/{userId}/threads",
              "flatPath": "gmail/v1/users/{userId}/threads",
              "description": "Lists the threads in the user's mailbox.",
              "id": "gmail.users.threads.list",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ]
            },
            "untrash": {
              "id": "gmail.users.threads.untrash",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "path": "gmail/v1/users/{userId}/threads/{id}/untrash",
              "description": "Removes the specified thread from the trash.",
              "flatPath": "gmail/v1/users/{userId}/threads/{id}/untrash",
              "httpMethod": "POST"
            }
          }
        },
        "drafts": {
          "methods": {
            "update": {
              "description": "Replaces a draft's content.",
              "id": "gmail.users.drafts.update",
              "flatPath": "gmail/v1/users/{userId}/drafts/{id}",
              "supportsMediaUpload": true,
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "httpMethod": "PUT",
              "path": "gmail/v1/users/{userId}/drafts/{id}"
            },
            "send": {
              "description": "Sends the specified, existing draft to the recipients in the `To`, `Cc`, and `Bcc` headers.",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "flatPath": "gmail/v1/users/{userId}/drafts/send",
              "id": "gmail.users.drafts.send",
              "supportsMediaUpload": true,
              "path": "gmail/v1/users/{userId}/drafts/send",
              "httpMethod": "POST"
            },
            "delete": {
              "flatPath": "gmail/v1/users/{userId}/drafts/{id}",
              "description": "Immediately and permanently deletes the specified draft. Does not simply trash it.",
              "httpMethod": "DELETE",
              "id": "gmail.users.drafts.delete",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "path": "gmail/v1/users/{userId}/drafts/{id}"
            },
            "create": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "id": "gmail.users.drafts.create",
              "httpMethod": "POST",
              "supportsMediaUpload": true,
              "path": "gmail/v1/users/{userId}/drafts",
              "description": "Creates a new draft with the `DRAFT` label.",
              "flatPath": "gmail/v1/users/{userId}/drafts"
            },
            "get": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "path": "gmail/v1/users/{userId}/drafts/{id}",
              "httpMethod": "GET",
              "id": "gmail.users.drafts.get",
              "description": "Gets the specified draft.",
              "flatPath": "gmail/v1/users/{userId}/drafts/{id}"
            },
            "list": {
              "description": "Lists the drafts in the user's mailbox.",
              "flatPath": "gmail/v1/users/{userId}/drafts",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "httpMethod": "GET",
              "path": "gmail/v1/users/{userId}/drafts",
              "id": "gmail.users.drafts.list"
            }
          }
        },
        "labels": {
          "methods": {
            "create": {
              "httpMethod": "POST",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "flatPath": "gmail/v1/users/{userId}/labels",
              "path": "gmail/v1/users/{userId}/labels",
              "description": "Creates a new label.",
              "id": "gmail.users.labels.create"
            },
            "get": {
              "id": "gmail.users.labels.get",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "flatPath": "gmail/v1/users/{userId}/labels/{id}",
              "httpMethod": "GET",
              "description": "Gets the specified label.",
              "path": "gmail/v1/users/{userId}/labels/{id}"
            },
            "delete": {
              "flatPath": "gmail/v1/users/{userId}/labels/{id}",
              "id": "gmail.users.labels.delete",
              "path": "gmail/v1/users/{userId}/labels/{id}",
              "httpMethod": "DELETE",
              "description": "Immediately and permanently deletes the specified label and removes it from any messages and threads that it is applied to.",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            },
            "patch": {
              "description": "Patch the specified label.",
              "path": "gmail/v1/users/{userId}/labels/{id}",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "httpMethod": "PATCH",
              "id": "gmail.users.labels.patch",
              "flatPath": "gmail/v1/users/{userId}/labels/{id}"
            },
            "update": {
              "path": "gmail/v1/users/{userId}/labels/{id}",
              "httpMethod": "PUT",
              "flatPath": "gmail/v1/users/{userId}/labels/{id}",
              "description": "Updates the specified label.",
              "id": "gmail.users.labels.update",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            },
            "list": {
              "id": "gmail.users.labels.list",
              "flatPath": "gmail/v1/users/{userId}/labels",
              "path": "gmail/v1/users/{userId}/labels",
              "description": "Lists all labels in the user's mailbox.",
              "httpMethod": "GET",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ]
            }
          }
        },
        "messages": {
          "resources": {
            "attachments": {
              "methods": {
                "get": {
                  "description": "Gets the specified message attachment.",
                  "path": "gmail/v1/users/{userId}/messages/{messageId}/attachments/{id}",
                  "flatPath": "gmail/v1/users/{userId}/messages/{messageId}/attachments/{id}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.addons.current.message.action",
                    "https://www.googleapis.com/auth/gmail.addons.current.message.readonly",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly"
                  ],
                  "id": "gmail.users.messages.attachments.get"
                }
              }
            }
          },
          "methods": {
            "get": {
              "path": "gmail/v1/users/{userId}/messages/{id}",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.message.action",
                "https://www.googleapis.com/auth/gmail.addons.current.message.metadata",
                "https://www.googleapis.com/auth/gmail.addons.current.message.readonly",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "flatPath": "gmail/v1/users/{userId}/messages/{id}",
              "httpMethod": "GET",
              "description": "Gets the specified message.",
              "id": "gmail.users.messages.get"
            },
            "delete": {
              "id": "gmail.users.messages.delete",
              "httpMethod": "DELETE",
              "path": "gmail/v1/users/{userId}/messages/{id}",
              "flatPath": "gmail/v1/users/{userId}/messages/{id}",
              "description": "Immediately and permanently deletes the specified message. This operation cannot be undone. Prefer `messages.trash` instead.",
              "scopes": [
                "https://mail.google.com/"
              ]
            },
            "batchDelete": {
              "description": "Deletes many messages by message ID. Provides no guarantees that messages were not already deleted or even existed at all.",
              "flatPath": "gmail/v1/users/{userId}/messages/batchDelete",
              "httpMethod": "POST",
              "scopes": [
                "https://mail.google.com/"
              ],
              "id": "gmail.users.messages.batchDelete",
              "path": "gmail/v1/users/{userId}/messages/batchDelete"
            },
            "modify": {
              "flatPath": "gmail/v1/users/{userId}/messages/{id}/modify",
              "path": "gmail/v1/users/{userId}/messages/{id}/modify",
              "description": "Modifies the labels on the specified message.",
              "httpMethod": "POST",
              "id": "gmail.users.messages.modify",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            },
            "insert": {
              "supportsMediaUpload": true,
              "path": "gmail/v1/users/{userId}/messages",
              "httpMethod": "POST",
              "id": "gmail.users.messages.insert",
              "description": "Directly inserts a message into only this user's mailbox similar to `IMAP APPEND`, bypassing most scanning and classification. Does not send a message.",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.insert",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "flatPath": "gmail/v1/users/{userId}/messages"
            },
            "send": {
              "path": "gmail/v1/users/{userId}/messages/send",
              "id": "gmail.users.messages.send",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.send"
              ],
              "flatPath": "gmail/v1/users/{userId}/messages/send",
              "httpMethod": "POST",
              "description": "Sends the specified message to the recipients in the `To`, `Cc`, and `Bcc` headers.",
              "supportsMediaUpload": true
            },
            "import": {
              "description": "Imports a message into only this user's mailbox, with standard email delivery scanning and classification similar to receiving via SMTP. Does not send a message. Note: This function doesn't trigger forwarding rules or filters set up by the user.",
              "id": "gmail.users.messages.import",
              "supportsMediaUpload": true,
              "flatPath": "gmail/v1/users/{userId}/messages/import",
              "path": "gmail/v1/users/{userId}/messages/import",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.insert",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "httpMethod": "POST"
            },
            "untrash": {
              "path": "gmail/v1/users/{userId}/messages/{id}/untrash",
              "httpMethod": "POST",
              "description": "Removes the specified message from the trash.",
              "id": "gmail.users.messages.untrash",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "flatPath": "gmail/v1/users/{userId}/messages/{id}/untrash"
            },
            "list": {
              "path": "gmail/v1/users/{userId}/messages",
              "flatPath": "gmail/v1/users/{userId}/messages",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "id": "gmail.users.messages.list",
              "httpMethod": "GET",
              "description": "Lists the messages in the user's mailbox."
            },
            "trash": {
              "description": "Moves the specified message to the trash.",
              "path": "gmail/v1/users/{userId}/messages/{id}/trash",
              "flatPath": "gmail/v1/users/{userId}/messages/{id}/trash",
              "httpMethod": "POST",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "id": "gmail.users.messages.trash"
            },
            "batchModify": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "path": "gmail/v1/users/{userId}/messages/batchModify",
              "id": "gmail.users.messages.batchModify",
              "httpMethod": "POST",
              "description": "Modifies the labels on the specified messages.",
              "flatPath": "gmail/v1/users/{userId}/messages/batchModify"
            }
          }
        },
        "history": {
          "methods": {
            "list": {
              "httpMethod": "GET",
              "description": "Lists the history of all changes to the given mailbox. History results are returned in chronological order (increasing `historyId`).",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "flatPath": "gmail/v1/users/{userId}/history",
              "path": "gmail/v1/users/{userId}/history",
              "id": "gmail.users.history.list"
            }
          }
        },
        "settings": {
          "methods": {
            "updateLanguage": {
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "httpMethod": "PUT",
              "description": "Updates language settings. If successful, the return object contains the `displayLanguage` that was saved for the user, which may differ from the value passed into the request. This is because the requested `displayLanguage` may not be directly supported by Gmail but have a close variant that is, and so the variant may be chosen and saved instead.",
              "flatPath": "gmail/v1/users/{userId}/settings/language",
              "path": "gmail/v1/users/{userId}/settings/language",
              "id": "gmail.users.settings.updateLanguage"
            },
            "getPop": {
              "flatPath": "gmail/v1/users/{userId}/settings/pop",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "httpMethod": "GET",
              "id": "gmail.users.settings.getPop",
              "description": "Gets POP settings.",
              "path": "gmail/v1/users/{userId}/settings/pop"
            },
            "updateImap": {
              "httpMethod": "PUT",
              "id": "gmail.users.settings.updateImap",
              "flatPath": "gmail/v1/users/{userId}/settings/imap",
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "path": "gmail/v1/users/{userId}/settings/imap",
              "description": "Updates IMAP settings."
            },
            "getVacation": {
              "description": "Gets vacation responder settings.",
              "path": "gmail/v1/users/{userId}/settings/vacation",
              "id": "gmail.users.settings.getVacation",
              "flatPath": "gmail/v1/users/{userId}/settings/vacation",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "httpMethod": "GET"
            },
            "updateVacation": {
              "id": "gmail.users.settings.updateVacation",
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "httpMethod": "PUT",
              "path": "gmail/v1/users/{userId}/settings/vacation",
              "description": "Updates vacation responder settings.",
              "flatPath": "gmail/v1/users/{userId}/settings/vacation"
            },
            "updateAutoForwarding": {
              "path": "gmail/v1/users/{userId}/settings/autoForwarding",
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.sharing"
              ],
              "httpMethod": "PUT",
              "id": "gmail.users.settings.updateAutoForwarding",
              "description": "Updates the auto-forwarding setting for the specified account. A verified forwarding address must be specified when auto-forwarding is enabled. This method is only available to service account clients that have been delegated domain-wide authority.",
              "flatPath": "gmail/v1/users/{userId}/settings/autoForwarding"
            },
            "getImap": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "id": "gmail.users.settings.getImap",
              "httpMethod": "GET",
              "path": "gmail/v1/users/{userId}/settings/imap",
              "flatPath": "gmail/v1/users/{userId}/settings/imap",
              "description": "Gets IMAP settings."
            },
            "getLanguage": {
              "description": "Gets language settings.",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "flatPath": "gmail/v1/users/{userId}/settings/language",
              "path": "gmail/v1/users/{userId}/settings/language",
              "httpMethod": "GET",
              "id": "gmail.users.settings.getLanguage"
            },
            "getAutoForwarding": {
              "id": "gmail.users.settings.getAutoForwarding",
              "path": "gmail/v1/users/{userId}/settings/autoForwarding",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "flatPath": "gmail/v1/users/{userId}/settings/autoForwarding",
              "httpMethod": "GET",
              "description": "Gets the auto-forwarding setting for the specified account."
            },
            "updatePop": {
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "flatPath": "gmail/v1/users/{userId}/settings/pop",
              "id": "gmail.users.settings.updatePop",
              "description": "Updates POP settings.",
              "path": "gmail/v1/users/{userId}/settings/pop",
              "httpMethod": "PUT"
            }
          },
          "resources": {
            "delegates": {
              "methods": {
                "create": {
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "flatPath": "gmail/v1/users/{userId}/settings/delegates",
                  "path": "gmail/v1/users/{userId}/settings/delegates",
                  "id": "gmail.users.settings.delegates.create",
                  "description": "Adds a delegate with its verification status set directly to `accepted`, without sending any verification email. The delegate user must be a member of the same G Suite organization as the delegator user. Gmail imposes limitations on the number of delegates and delegators each user in a G Suite organization can have. These limits depend on your organization, but in general each user can have up to 25 delegates and up to 10 delegators. Note that a delegate user mu[...]"
                },
                "delete": {
                  "path": "gmail/v1/users/{userId}/settings/delegates/{delegateEmail}",
                  "description": "Removes the specified delegate (which can be of any verification status), and revokes any verification that may have been required for using it. Note that a delegate user must be referred to by their primary email address, and not an email alias. This method is only available to service account clients that have been delegated domain-wide authority.",
                  "httpMethod": "DELETE",
                  "flatPath": "gmail/v1/users/{userId}/settings/delegates/{delegateEmail}",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "id": "gmail.users.settings.delegates.delete"
                },
                "get": {
                  "path": "gmail/v1/users/{userId}/settings/delegates/{delegateEmail}",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "id": "gmail.users.settings.delegates.get",
                  "description": "Gets the specified delegate. Note that a delegate user must be referred to by their primary email address, and not an email alias. This method is only available to service account clients that have been delegated domain-wide authority.",
                  "httpMethod": "GET",
                  "flatPath": "gmail/v1/users/{userId}/settings/delegates/{delegateEmail}"
                },
                "list": {
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "flatPath": "gmail/v1/users/{userId}/settings/delegates",
                  "description": "Lists the delegates for the specified account. This method is only available to service account clients that have been delegated domain-wide authority.",
                  "httpMethod": "GET",
                  "id": "gmail.users.settings.delegates.list",
                  "path": "gmail/v1/users/{userId}/settings/delegates"
                }
              }
            },
            "sendAs": {
              "resources": {
                "smimeInfo": {
                  "methods": {
                    "insert": {
                      "description": "Insert (upload) the given S/MIME config for the specified send-as alias. Note that pkcs12 format is required for the key.",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "httpMethod": "POST",
                      "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo",
                      "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo",
                      "id": "gmail.users.settings.sendAs.smimeInfo.insert"
                    },
                    "delete": {
                      "httpMethod": "DELETE",
                      "description": "Deletes the specified S/MIME config for the specified send-as alias.",
                      "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}",
                      "id": "gmail.users.settings.sendAs.smimeInfo.delete"
                    },
                    "setDefault": {
                      "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}/setDefault",
                      "id": "gmail.users.settings.sendAs.smimeInfo.setDefault",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}/setDefault",
                      "description": "Sets the default S/MIME config for the specified send-as alias.",
                      "httpMethod": "POST"
                    },
                    "get": {
                      "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly",
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "id": "gmail.users.settings.sendAs.smimeInfo.get",
                      "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}",
                      "description": "Gets the specified S/MIME config for the specified send-as alias.",
                      "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}",
                      "httpMethod": "GET"
                    },
                    "list": {
                      "description": "Lists S/MIME configs for the specified send-as alias.",
                      "httpMethod": "GET",
                      "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo",
                      "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo",
                      "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly",
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "id": "gmail.users.settings.sendAs.smimeInfo.list"
                    }
                  }
                }
              },
              "methods": {
                "create": {
                  "description": "Creates a custom \"from\" send-as alias. If an SMTP MSA is specified, Gmail will attempt to connect to the SMTP service to validate the configuration before creating the alias. If ownership verification is required for the alias, a message will be sent to the email address and the resource's verification status will be set to `pending`; otherwise, the resource will be created with verification status set to `accepted`. If a signature is provided, Gmail will sani[...]",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "httpMethod": "POST",
                  "path": "gmail/v1/users/{userId}/settings/sendAs",
                  "id": "gmail.users.settings.sendAs.create",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs"
                },
                "patch": {
                  "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "httpMethod": "PATCH",
                  "description": "Patch the specified send-as alias.",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.basic",
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "id": "gmail.users.settings.sendAs.patch"
                },
                "list": {
                  "path": "gmail/v1/users/{userId}/settings/sendAs",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "id": "gmail.users.settings.sendAs.list",
                  "description": "Lists the send-as aliases for the specified account. The result includes the primary send-as address associated with the account as well as any custom \"from\" aliases.",
                  "httpMethod": "GET"
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "description": "Deletes the specified send-as alias. Revokes any verification that may have been required for using it. This method is only available to service account clients that have been delegated domain-wide authority.",
                  "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "id": "gmail.users.settings.sendAs.delete",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}"
                },
                "get": {
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "httpMethod": "GET",
                  "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "id": "gmail.users.settings.sendAs.get",
                  "description": "Gets the specified send-as alias. Fails with an HTTP 404 error if the specified address is not a member of the collection.",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}"
                },
                "update": {
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.basic",
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "description": "Updates a send-as alias. If a signature is provided, Gmail will sanitize the HTML before saving it with the alias. Addresses other than the primary address for the account can only be updated by service account clients that have been delegated domain-wide authority.",
                  "httpMethod": "PUT",
                  "id": "gmail.users.settings.sendAs.update"
                },
                "verify": {
                  "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/verify",
                  "id": "gmail.users.settings.sendAs.verify",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "description": "Sends a verification email to the specified send-as alias address. The verification status must be `pending`. This method is only available to service account clients that have been delegated domain-wide authority.",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/verify",
                  "httpMethod": "POST"
                }
              }
            },
            "filters": {
              "methods": {
                "create": {
                  "description": "Creates a filter. Note: you can only create a maximum of 1,000 filters.",
                  "flatPath": "gmail/v1/users/{userId}/settings/filters",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "httpMethod": "POST",
                  "path": "gmail/v1/users/{userId}/settings/filters",
                  "id": "gmail.users.settings.filters.create"
                },
                "delete": {
                  "description": "Deletes a filter.",
                  "flatPath": "gmail/v1/users/{userId}/settings/filters/{id}",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "path": "gmail/v1/users/{userId}/settings/filters/{id}",
                  "id": "gmail.users.settings.filters.delete"
                },
                "list": {
                  "id": "gmail.users.settings.filters.list",
                  "description": "Lists the message filters of a Gmail user.",
                  "path": "gmail/v1/users/{userId}/settings/filters",
                  "flatPath": "gmail/v1/users/{userId}/settings/filters",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ]
                },
                "get": {
                  "flatPath": "gmail/v1/users/{userId}/settings/filters/{id}",
                  "httpMethod": "GET",
                  "id": "gmail.users.settings.filters.get",
                  "path": "gmail/v1/users/{userId}/settings/filters/{id}",
                  "description": "Gets a filter.",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ]
                }
              }
            },
            "forwardingAddresses": {
              "methods": {
                "create": {
                  "id": "gmail.users.settings.forwardingAddresses.create",
                  "path": "gmail/v1/users/{userId}/settings/forwardingAddresses",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "description": "Creates a forwarding address. If ownership verification is required, a message will be sent to the recipient and the resource's verification status will be set to `pending`; otherwise, the resource will be created with verification status set to `accepted`. This method is only available to service account clients that have been delegated domain-wide authority.",
                  "httpMethod": "POST",
                  "flatPath": "gmail/v1/users/{userId}/settings/forwardingAddresses"
                },
                "get": {
                  "flatPath": "gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}",
                  "path": "gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "httpMethod": "GET",
                  "id": "gmail.users.settings.forwardingAddresses.get",
                  "description": "Gets the specified forwarding address."
                },
                "list": {
                  "flatPath": "gmail/v1/users/{userId}/settings/forwardingAddresses",
                  "description": "Lists the forwarding addresses for the specified account.",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "path": "gmail/v1/users/{userId}/settings/forwardingAddresses",
                  "id": "gmail.users.settings.forwardingAddresses.list",
                  "httpMethod": "GET"
                },
                "delete": {
                  "path": "gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}",
                  "flatPath": "gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "httpMethod": "DELETE",
                  "description": "Deletes the specified forwarding address and revokes any verification that may have been required. This method is only available to service account clients that have been delegated domain-wide authority.",
                  "id": "gmail.users.settings.forwardingAddresses.delete"
                }
              }
            }
          }
        }
      },
      "methods": {
        "getProfile": {
          "path": "gmail/v1/users/{userId}/profile",
          "httpMethod": "GET",
          "description": "Gets the current user's Gmail profile.",
          "flatPath": "gmail/v1/users/{userId}/profile",
          "id": "gmail.users.getProfile",
          "scopes": [
            "https://mail.google.com/",
            "https://www.googleapis.com/auth/gmail.compose",
            "https://www.googleapis.com/auth/gmail.metadata",
            "https://www.googleapis.com/auth/gmail.modify",
            "https://www.googleapis.com/auth/gmail.readonly"
          ]
        },
        "watch": {
          "description": "Set up or update a push notification watch on the given user mailbox.",
          "path": "gmail/v1/users/{userId}/watch",
          "id": "gmail.users.watch",
          "flatPath": "gmail/v1/users/{userId}/watch",
          "httpMethod": "POST",
          "scopes": [
            "https://mail.google.com/",
            "https://www.googleapis.com/auth/gmail.metadata",
            "https://www.googleapis.com/auth/gmail.modify",
            "https://www.googleapis.com/auth/gmail.readonly"
          ]
        },
        "stop": {
          "flatPath": "gmail/v1/users/{userId}/stop",
          "path": "gmail/v1/users/{userId}/stop",
          "id": "gmail.users.stop",
          "httpMethod": "POST",
          "scopes": [
            "https://mail.google.com/",
            "https://www.googleapis.com/auth/gmail.metadata",
            "https://www.googleapis.com/auth/gmail.modify",
            "https://www.googleapis.com/auth/gmail.readonly"
          ],
          "description": "Stop receiving push notifications for the given user mailbox."
        }
      }
    }
  },
  "description": "The Gmail API lets you view and manage Gmail mailbox data like threads, messages, and labels."
}
