{
  "version": "v4",
  "ownerDomain": "google.com",
  "version_module": true,
  "discoveryVersion": "v1",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/drive.file": {
          "description": "View and manage Google Drive files and folders that you have opened or created with this app"
        },
        "https://www.googleapis.com/auth/drive": {
          "description": "See, edit, create, and delete all of your Google Drive files"
        },
        "https://www.googleapis.com/auth/spreadsheets": {
          "description": "See, edit, create, and delete your spreadsheets in Google Drive"
        },
        "https://www.googleapis.com/auth/drive.readonly": {
          "description": "See and download all your Google Drive files"
        },
        "https://www.googleapis.com/auth/spreadsheets.readonly": {
          "description": "View your Google Spreadsheets"
        }
      }
    }
  },
  "revision": "20201130",
  "name": "sheets",
  "protocol": "rest",
  "servicePath": "",
  "description": "Reads and writes Google Sheets.",
  "ownerName": "Google",
  "resources": {
    "spreadsheets": {
      "resources": {
        "values": {
          "methods": {
            "batchUpdate": {
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/spreadsheets"
              ],
              "httpMethod": "POST",
              "flatPath": "v4/spreadsheets/{spreadsheetId}/values:batchUpdate",
              "id": "sheets.spreadsheets.values.batchUpdate",
              "path": "v4/spreadsheets/{spreadsheetId}/values:batchUpdate",
              "description": "Sets values in one or more ranges of a spreadsheet. The caller must specify the spreadsheet ID, a valueInputOption, and one or more ValueRanges."
            },
            "append": {
              "httpMethod": "POST",
              "flatPath": "v4/spreadsheets/{spreadsheetId}/values/{range}:append",
              "id": "sheets.spreadsheets.values.append",
              "description": "Appends values to a spreadsheet. The input range is used to search for existing data and find a \"table\" within that range. Values will be appended to the next row of the table, starting with the first column of the table. See the [guide](/sheets/api/guides/values#appending_values) and [sample code](/sheets/api/samples/writing#append_values) for specific details of how tables are detected and data is appended. The caller must specify the spreadsheet ID, range, and [...]",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/spreadsheets"
              ],
              "path": "v4/spreadsheets/{spreadsheetId}/values/{range}:append"
            },
            "batchClear": {
              "path": "v4/spreadsheets/{spreadsheetId}/values:batchClear",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/spreadsheets"
              ],
              "flatPath": "v4/spreadsheets/{spreadsheetId}/values:batchClear",
              "description": "Clears one or more ranges of values from a spreadsheet. The caller must specify the spreadsheet ID and one or more ranges. Only values are cleared -- all other properties of the cell (such as formatting, data validation, etc..) are kept.",
              "id": "sheets.spreadsheets.values.batchClear"
            },
            "batchGet": {
              "description": "Returns one or more ranges of values from a spreadsheet. The caller must specify the spreadsheet ID and one or more ranges.",
              "flatPath": "v4/spreadsheets/{spreadsheetId}/values:batchGet",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/drive.readonly",
                "https://www.googleapis.com/auth/spreadsheets",
                "https://www.googleapis.com/auth/spreadsheets.readonly"
              ],
              "httpMethod": "GET",
              "id": "sheets.spreadsheets.values.batchGet",
              "path": "v4/spreadsheets/{spreadsheetId}/values:batchGet"
            },
            "batchUpdateByDataFilter": {
              "id": "sheets.spreadsheets.values.batchUpdateByDataFilter",
              "description": "Sets values in one or more ranges of a spreadsheet. The caller must specify the spreadsheet ID, a valueInputOption, and one or more DataFilterValueRanges.",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/spreadsheets"
              ],
              "flatPath": "v4/spreadsheets/{spreadsheetId}/values:batchUpdateByDataFilter",
              "path": "v4/spreadsheets/{spreadsheetId}/values:batchUpdateByDataFilter"
            },
            "clear": {
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/spreadsheets"
              ],
              "id": "sheets.spreadsheets.values.clear",
              "flatPath": "v4/spreadsheets/{spreadsheetId}/values/{range}:clear",
              "path": "v4/spreadsheets/{spreadsheetId}/values/{range}:clear",
              "httpMethod": "POST",
              "description": "Clears values from a spreadsheet. The caller must specify the spreadsheet ID and range. Only values are cleared -- all other properties of the cell (such as formatting, data validation, etc..) are kept."
            },
            "update": {
              "path": "v4/spreadsheets/{spreadsheetId}/values/{range}",
              "flatPath": "v4/spreadsheets/{spreadsheetId}/values/{range}",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/spreadsheets"
              ],
              "httpMethod": "PUT",
              "description": "Sets values in a range of a spreadsheet. The caller must specify the spreadsheet ID, range, and a valueInputOption.",
              "id": "sheets.spreadsheets.values.update"
            },
            "batchClearByDataFilter": {
              "flatPath": "v4/spreadsheets/{spreadsheetId}/values:batchClearByDataFilter",
              "httpMethod": "POST",
              "path": "v4/spreadsheets/{spreadsheetId}/values:batchClearByDataFilter",
              "id": "sheets.spreadsheets.values.batchClearByDataFilter",
              "description": "Clears one or more ranges of values from a spreadsheet. The caller must specify the spreadsheet ID and one or more DataFilters. Ranges matching any of the specified data filters will be cleared. Only values are cleared -- all other properties of the cell (such as formatting, data validation, etc..) are kept.",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/spreadsheets"
              ]
            },
            "batchGetByDataFilter": {
              "path": "v4/spreadsheets/{spreadsheetId}/values:batchGetByDataFilter",
              "httpMethod": "POST",
              "description": "Returns one or more ranges of values that match the specified data filters. The caller must specify the spreadsheet ID and one or more DataFilters. Ranges that match any of the data filters in the request will be returned.",
              "flatPath": "v4/spreadsheets/{spreadsheetId}/values:batchGetByDataFilter",
              "id": "sheets.spreadsheets.values.batchGetByDataFilter",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/spreadsheets"
              ]
            },
            "get": {
              "id": "sheets.spreadsheets.values.get",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/drive.readonly",
                "https://www.googleapis.com/auth/spreadsheets",
                "https://www.googleapis.com/auth/spreadsheets.readonly"
              ],
              "path": "v4/spreadsheets/{spreadsheetId}/values/{range}",
              "flatPath": "v4/spreadsheets/{spreadsheetId}/values/{range}",
              "description": "Returns a range of values from a spreadsheet. The caller must specify the spreadsheet ID and a range."
            }
          }
        },
        "sheets": {
          "methods": {
            "copyTo": {
              "path": "v4/spreadsheets/{spreadsheetId}/sheets/{sheetId}:copyTo",
              "id": "sheets.spreadsheets.sheets.copyTo",
              "httpMethod": "POST",
              "flatPath": "v4/spreadsheets/{spreadsheetId}/sheets/{sheetId}:copyTo",
              "description": "Copies a single sheet from a spreadsheet to another spreadsheet. Returns the properties of the newly created sheet.",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/spreadsheets"
              ]
            }
          }
        },
        "developerMetadata": {
          "methods": {
            "get": {
              "flatPath": "v4/spreadsheets/{spreadsheetId}/developerMetadata/{metadataId}",
              "description": "Returns the developer metadata with the specified ID. The caller must specify the spreadsheet ID and the developer metadata's unique metadataId.",
              "path": "v4/spreadsheets/{spreadsheetId}/developerMetadata/{metadataId}",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/spreadsheets"
              ],
              "httpMethod": "GET",
              "id": "sheets.spreadsheets.developerMetadata.get"
            },
            "search": {
              "httpMethod": "POST",
              "id": "sheets.spreadsheets.developerMetadata.search",
              "path": "v4/spreadsheets/{spreadsheetId}/developerMetadata:search",
              "description": "Returns all developer metadata matching the specified DataFilter. If the provided DataFilter represents a DeveloperMetadataLookup object, this will return all DeveloperMetadata entries selected by it. If the DataFilter represents a location in a spreadsheet, this will return all developer metadata associated with locations intersecting that region.",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/spreadsheets"
              ],
              "flatPath": "v4/spreadsheets/{spreadsheetId}/developerMetadata:search"
            }
          }
        }
      },
      "methods": {
        "getByDataFilter": {
          "id": "sheets.spreadsheets.getByDataFilter",
          "description": "Returns the spreadsheet at the given ID. The caller must specify the spreadsheet ID. This method differs from GetSpreadsheet in that it allows selecting which subsets of spreadsheet data to return by specifying a dataFilters parameter. Multiple DataFilters can be specified. Specifying one or more data filters will return the portions of the spreadsheet that intersect ranges matched by any of the filters. By default, data within grids will not be returned. You can includ[...]",
          "httpMethod": "POST",
          "flatPath": "v4/spreadsheets/{spreadsheetId}:getByDataFilter",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/spreadsheets"
          ],
          "path": "v4/spreadsheets/{spreadsheetId}:getByDataFilter"
        },
        "create": {
          "path": "v4/spreadsheets",
          "id": "sheets.spreadsheets.create",
          "flatPath": "v4/spreadsheets",
          "description": "Creates a spreadsheet, returning the newly created spreadsheet.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/spreadsheets"
          ]
        },
        "batchUpdate": {
          "httpMethod": "POST",
          "id": "sheets.spreadsheets.batchUpdate",
          "description": "Applies one or more updates to the spreadsheet. Each request is validated before being applied. If any request is not valid then the entire request will fail and nothing will be applied. Some requests have replies to give you some information about how they are applied. The replies will mirror the requests. For example, if you applied 4 updates and the 3rd one had a reply, then the response will have 2 empty replies, the actual reply, and another empty reply, in that or[...]",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/spreadsheets"
          ],
          "flatPath": "v4/spreadsheets/{spreadsheetId}:batchUpdate",
          "path": "v4/spreadsheets/{spreadsheetId}:batchUpdate"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly",
            "https://www.googleapis.com/auth/spreadsheets",
            "https://www.googleapis.com/auth/spreadsheets.readonly"
          ],
          "flatPath": "v4/spreadsheets/{spreadsheetId}",
          "httpMethod": "GET",
          "description": "Returns the spreadsheet at the given ID. The caller must specify the spreadsheet ID. By default, data within grids will not be returned. You can include grid data one of two ways: * Specify a field mask listing your desired fields using the `fields` URL parameter in HTTP * Set the includeGridData URL parameter to true. If a field mask is set, the `includeGridData` parameter is ignored For large spreadsheets, it is recommended to retrieve only the specific fields of the [...]",
          "id": "sheets.spreadsheets.get",
          "path": "v4/spreadsheets/{spreadsheetId}"
        }
      }
    }
  },
  "documentationLink": "https://developers.google.com/sheets/",
  "batchPath": "batch",
  "kind": "discovery#restDescription",
  "fullyEncodeReservedExpansion": true,
  "id": "sheets:v4",
  "title": "Google Sheets API",
  "mtlsRootUrl": "https://sheets.mtls.googleapis.com/",
  "canonicalName": "Sheets",
  "rootUrl": "https://sheets.googleapis.com/",
  "basePath": "",
  "baseUrl": "https://sheets.googleapis.com/"
}
