{
  "batchPath": "batch",
  "baseUrl": "https://slides.googleapis.com/",
  "discoveryVersion": "v1",
  "name": "slides",
  "ownerDomain": "google.com",
  "title": "Google Slides API",
  "mtlsRootUrl": "https://slides.mtls.googleapis.com/",
  "resources": {
    "presentations": {
      "resources": {
        "pages": {
          "methods": {
            "get": {
              "httpMethod": "GET",
              "path": "v1/presentations/{presentationId}/pages/{pageObjectId}",
              "flatPath": "v1/presentations/{presentationId}/pages/{pageObjectId}",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/drive.readonly",
                "https://www.googleapis.com/auth/presentations",
                "https://www.googleapis.com/auth/presentations.readonly"
              ],
              "id": "slides.presentations.pages.get",
              "description": "Gets the latest version of the specified page in the presentation."
            },
            "getThumbnail": {
              "httpMethod": "GET",
              "path": "v1/presentations/{presentationId}/pages/{pageObjectId}/thumbnail",
              "description": "Generates a thumbnail of the latest version of the specified page in the presentation and returns a URL to the thumbnail image. This request counts as an [expensive read request](/slides/limits) for quota purposes.",
              "id": "slides.presentations.pages.getThumbnail",
              "flatPath": "v1/presentations/{presentationId}/pages/{pageObjectId}/thumbnail",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/drive.readonly",
                "https://www.googleapis.com/auth/presentations",
                "https://www.googleapis.com/auth/presentations.readonly"
              ]
            }
          }
        }
      },
      "methods": {
        "batchUpdate": {
          "description": "Applies one or more updates to the presentation. Each request is validated before being applied. If any request is not valid, then the entire request will fail and nothing will be applied. Some requests have replies to give you some information about how they are applied. Other requests do not need to return information; these each return an empty reply. The order of replies matches that of the requests. For example, suppose you call batchUpdate with four updates, and o[...]",
          "path": "v1/presentations/{presentationId}:batchUpdate",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly",
            "https://www.googleapis.com/auth/presentations",
            "https://www.googleapis.com/auth/spreadsheets",
            "https://www.googleapis.com/auth/spreadsheets.readonly"
          ],
          "id": "slides.presentations.batchUpdate",
          "flatPath": "v1/presentations/{presentationId}:batchUpdate"
        },
        "create": {
          "id": "slides.presentations.create",
          "flatPath": "v1/presentations",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/presentations"
          ],
          "httpMethod": "POST",
          "description": "Creates a blank presentation using the title given in the request. If a `presentationId` is provided, it is used as the ID of the new presentation. Otherwise, a new ID is generated. Other fields in the request, including any provided content, are ignored. Returns the created presentation.",
          "path": "v1/presentations"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly",
            "https://www.googleapis.com/auth/presentations",
            "https://www.googleapis.com/auth/presentations.readonly"
          ],
          "httpMethod": "GET",
          "description": "Gets the latest version of the specified presentation.",
          "flatPath": "v1/presentations/{presentationsId}",
          "path": "v1/presentations/{+presentationId}",
          "id": "slides.presentations.get"
        }
      }
    }
  },
  "version_module": true,
  "revision": "20201120",
  "documentationLink": "https://developers.google.com/slides/",
  "protocol": "rest",
  "servicePath": "",
  "rootUrl": "https://slides.googleapis.com/",
  "description": "Reads and writes Google Slides presentations.",
  "fullyEncodeReservedExpansion": true,
  "kind": "discovery#restDescription",
  "id": "slides:v1",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/drive.readonly": {
          "description": "See and download all your Google Drive files"
        },
        "https://www.googleapis.com/auth/spreadsheets.readonly": {
          "description": "View your Google Spreadsheets"
        },
        "https://www.googleapis.com/auth/drive": {
          "description": "See, edit, create, and delete all of your Google Drive files"
        },
        "https://www.googleapis.com/auth/presentations.readonly": {
          "description": "View your Google Slides presentations"
        },
        "https://www.googleapis.com/auth/drive.file": {
          "description": "View and manage Google Drive files and folders that you have opened or created with this app"
        },
        "https://www.googleapis.com/auth/spreadsheets": {
          "description": "See, edit, create, and delete your spreadsheets in Google Drive"
        },
        "https://www.googleapis.com/auth/presentations": {
          "description": "View and manage your Google Slides presentations"
        }
      }
    }
  },
  "canonicalName": "Slides",
  "ownerName": "Google",
  "version": "v1",
  "basePath": ""
}
