{
  "id": "vault:v1",
  "version": "v1",
  "protocol": "rest",
  "servicePath": "",
  "fullyEncodeReservedExpansion": true,
  "name": "vault",
  "description": "Archiving and eDiscovery for G Suite.",
  "discoveryVersion": "v1",
  "ownerDomain": "google.com",
  "batchPath": "batch",
  "canonicalName": "Vault",
  "resources": {
    "operations": {
      "methods": {
        "delete": {
          "description": "Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`.",
          "path": "v1/{+name}",
          "httpMethod": "DELETE",
          "flatPath": "v1/operations/{operationsId}",
          "id": "vault.operations.delete"
        },
        "list": {
          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`. NOTE: the `name` binding allows API services to override the binding to use different resource name schemes, such as `users/*/operations`. To override the binding, API services can add a binding such as `\"/v1/{name=users/*}/operations\"` to their service configuration. For backwards compatibility, the default name includes the operatio[...]",
          "flatPath": "v1/operations",
          "id": "vault.operations.list",
          "httpMethod": "GET",
          "path": "v1/{+name}"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery",
            "https://www.googleapis.com/auth/ediscovery.readonly"
          ],
          "flatPath": "v1/operations/{operationsId}",
          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
          "httpMethod": "GET",
          "id": "vault.operations.get",
          "path": "v1/{+name}"
        },
        "cancel": {
          "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it becomes an[...]",
          "flatPath": "v1/operations/{operationsId}:cancel",
          "id": "vault.operations.cancel",
          "path": "v1/{+name}:cancel",
          "httpMethod": "POST"
        }
      }
    },
    "matters": {
      "resources": {
        "savedQueries": {
          "methods": {
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ],
              "flatPath": "v1/matters/{matterId}/savedQueries",
              "path": "v1/matters/{matterId}/savedQueries",
              "httpMethod": "GET",
              "description": "Lists saved queries within a matter. An empty page token in ListSavedQueriesResponse denotes no more saved queries to list.",
              "id": "vault.matters.savedQueries.list"
            },
            "create": {
              "description": "Creates a saved query.",
              "flatPath": "v1/matters/{matterId}/savedQueries",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "httpMethod": "POST",
              "id": "vault.matters.savedQueries.create",
              "path": "v1/matters/{matterId}/savedQueries"
            },
            "get": {
              "id": "vault.matters.savedQueries.get",
              "flatPath": "v1/matters/{matterId}/savedQueries/{savedQueryId}",
              "description": "Retrieves a saved query by Id.",
              "httpMethod": "GET",
              "path": "v1/matters/{matterId}/savedQueries/{savedQueryId}",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ]
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "httpMethod": "DELETE",
              "path": "v1/matters/{matterId}/savedQueries/{savedQueryId}",
              "description": "Deletes a saved query by Id.",
              "id": "vault.matters.savedQueries.delete",
              "flatPath": "v1/matters/{matterId}/savedQueries/{savedQueryId}"
            }
          }
        },
        "holds": {
          "resources": {
            "accounts": {
              "methods": {
                "create": {
                  "flatPath": "v1/matters/{matterId}/holds/{holdId}/accounts",
                  "id": "vault.matters.holds.accounts.create",
                  "path": "v1/matters/{matterId}/holds/{holdId}/accounts",
                  "scopes": [
                    "https://www.googleapis.com/auth/ediscovery"
                  ],
                  "description": "Adds a HeldAccount to a hold. Accounts can only be added to a hold that has no held_org_unit set. Attempting to add an account to an OU-based hold will result in an error.",
                  "httpMethod": "POST"
                },
                "list": {
                  "path": "v1/matters/{matterId}/holds/{holdId}/accounts",
                  "httpMethod": "GET",
                  "id": "vault.matters.holds.accounts.list",
                  "description": "Lists HeldAccounts for a hold. This will only list individually specified held accounts. If the hold is on an OU, then use Admin SDK to enumerate its members.",
                  "scopes": [
                    "https://www.googleapis.com/auth/ediscovery",
                    "https://www.googleapis.com/auth/ediscovery.readonly"
                  ],
                  "flatPath": "v1/matters/{matterId}/holds/{holdId}/accounts"
                },
                "delete": {
                  "id": "vault.matters.holds.accounts.delete",
                  "path": "v1/matters/{matterId}/holds/{holdId}/accounts/{accountId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/ediscovery"
                  ],
                  "description": "Removes a HeldAccount from a hold. If this request leaves the hold with no held accounts, the hold will not apply to any accounts.",
                  "flatPath": "v1/matters/{matterId}/holds/{holdId}/accounts/{accountId}",
                  "httpMethod": "DELETE"
                }
              }
            }
          },
          "methods": {
            "addHeldAccounts": {
              "httpMethod": "POST",
              "id": "vault.matters.holds.addHeldAccounts",
              "path": "v1/matters/{matterId}/holds/{holdId}:addHeldAccounts",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "flatPath": "v1/matters/{matterId}/holds/{holdId}:addHeldAccounts",
              "description": "Adds HeldAccounts to a hold. Returns a list of accounts that have been successfully added. Accounts can only be added to an existing account-based hold."
            },
            "get": {
              "path": "v1/matters/{matterId}/holds/{holdId}",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ],
              "httpMethod": "GET",
              "description": "Gets a hold by ID.",
              "id": "vault.matters.holds.get",
              "flatPath": "v1/matters/{matterId}/holds/{holdId}"
            },
            "update": {
              "description": "Updates the OU and/or query parameters of a hold. You cannot add accounts to a hold that covers an OU, nor can you add OUs to a hold that covers individual accounts. Accounts listed in the hold will be ignored.",
              "httpMethod": "PUT",
              "id": "vault.matters.holds.update",
              "flatPath": "v1/matters/{matterId}/holds/{holdId}",
              "path": "v1/matters/{matterId}/holds/{holdId}",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ]
            },
            "list": {
              "description": "Lists holds within a matter. An empty page token in ListHoldsResponse denotes no more holds to list.",
              "path": "v1/matters/{matterId}/holds",
              "id": "vault.matters.holds.list",
              "httpMethod": "GET",
              "flatPath": "v1/matters/{matterId}/holds",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ]
            },
            "removeHeldAccounts": {
              "id": "vault.matters.holds.removeHeldAccounts",
              "path": "v1/matters/{matterId}/holds/{holdId}:removeHeldAccounts",
              "description": "Removes HeldAccounts from a hold. Returns a list of statuses in the same order as the request. If this request leaves the hold with no held accounts, the hold will not apply to any accounts.",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "flatPath": "v1/matters/{matterId}/holds/{holdId}:removeHeldAccounts"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "flatPath": "v1/matters/{matterId}/holds",
              "id": "vault.matters.holds.create",
              "description": "Creates a hold in the given matter.",
              "httpMethod": "POST",
              "path": "v1/matters/{matterId}/holds"
            },
            "delete": {
              "httpMethod": "DELETE",
              "path": "v1/matters/{matterId}/holds/{holdId}",
              "description": "Removes a hold by ID. This will release any HeldAccounts on this Hold.",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "id": "vault.matters.holds.delete",
              "flatPath": "v1/matters/{matterId}/holds/{holdId}"
            }
          }
        },
        "exports": {
          "methods": {
            "delete": {
              "httpMethod": "DELETE",
              "path": "v1/matters/{matterId}/exports/{exportId}",
              "flatPath": "v1/matters/{matterId}/exports/{exportId}",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "id": "vault.matters.exports.delete",
              "description": "Deletes an Export."
            },
            "list": {
              "httpMethod": "GET",
              "flatPath": "v1/matters/{matterId}/exports",
              "id": "vault.matters.exports.list",
              "path": "v1/matters/{matterId}/exports",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ],
              "description": "Lists Exports."
            },
            "get": {
              "httpMethod": "GET",
              "flatPath": "v1/matters/{matterId}/exports/{exportId}",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ],
              "path": "v1/matters/{matterId}/exports/{exportId}",
              "description": "Gets an Export.",
              "id": "vault.matters.exports.get"
            },
            "create": {
              "httpMethod": "POST",
              "description": "Creates an Export.",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "flatPath": "v1/matters/{matterId}/exports",
              "path": "v1/matters/{matterId}/exports",
              "id": "vault.matters.exports.create"
            }
          }
        }
      },
      "methods": {
        "list": {
          "id": "vault.matters.list",
          "description": "Lists matters the user has access to.",
          "path": "v1/matters",
          "httpMethod": "GET",
          "flatPath": "v1/matters",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery",
            "https://www.googleapis.com/auth/ediscovery.readonly"
          ]
        },
        "close": {
          "description": "Closes the specified matter. Returns matter with updated state.",
          "httpMethod": "POST",
          "flatPath": "v1/matters/{matterId}:close",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "path": "v1/matters/{matterId}:close",
          "id": "vault.matters.close"
        },
        "reopen": {
          "httpMethod": "POST",
          "flatPath": "v1/matters/{matterId}:reopen",
          "path": "v1/matters/{matterId}:reopen",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "description": "Reopens the specified matter. Returns matter with updated state.",
          "id": "vault.matters.reopen"
        },
        "removePermissions": {
          "description": "Removes an account as a matter collaborator.",
          "id": "vault.matters.removePermissions",
          "httpMethod": "POST",
          "path": "v1/matters/{matterId}:removePermissions",
          "flatPath": "v1/matters/{matterId}:removePermissions",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ]
        },
        "create": {
          "flatPath": "v1/matters",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "httpMethod": "POST",
          "path": "v1/matters",
          "description": "Creates a new matter with the given name and description. The initial state is open, and the owner is the method caller. Returns the created matter with default view.",
          "id": "vault.matters.create"
        },
        "count": {
          "id": "vault.matters.count",
          "httpMethod": "POST",
          "flatPath": "v1/matters/{matterId}:count",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "description": "Counts the artifacts within the context of a matter and returns a detailed breakdown of metrics.",
          "path": "v1/matters/{matterId}:count"
        },
        "addPermissions": {
          "description": "Adds an account as a matter collaborator.",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "flatPath": "v1/matters/{matterId}:addPermissions",
          "id": "vault.matters.addPermissions",
          "path": "v1/matters/{matterId}:addPermissions",
          "httpMethod": "POST"
        },
        "undelete": {
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "flatPath": "v1/matters/{matterId}:undelete",
          "path": "v1/matters/{matterId}:undelete",
          "httpMethod": "POST",
          "description": "Undeletes the specified matter. Returns matter with updated state.",
          "id": "vault.matters.undelete"
        },
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery",
            "https://www.googleapis.com/auth/ediscovery.readonly"
          ],
          "flatPath": "v1/matters/{matterId}",
          "description": "Gets the specified matter.",
          "path": "v1/matters/{matterId}",
          "id": "vault.matters.get"
        },
        "update": {
          "description": "Updates the specified matter. This updates only the name and description of the matter, identified by matter ID. Changes to any other fields are ignored. Returns the default view of the matter.",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "id": "vault.matters.update",
          "path": "v1/matters/{matterId}",
          "flatPath": "v1/matters/{matterId}",
          "httpMethod": "PUT"
        },
        "delete": {
          "id": "vault.matters.delete",
          "description": "Deletes the specified matter. Returns matter with updated state.",
          "httpMethod": "DELETE",
          "flatPath": "v1/matters/{matterId}",
          "path": "v1/matters/{matterId}",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ]
        }
      }
    }
  },
  "version_module": true,
  "rootUrl": "https://vault.googleapis.com/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/ediscovery": {
          "description": "Manage your eDiscovery data"
        },
        "https://www.googleapis.com/auth/ediscovery.readonly": {
          "description": "View your eDiscovery data"
        }
      }
    }
  },
  "ownerName": "Google",
  "mtlsRootUrl": "https://vault.mtls.googleapis.com/",
  "revision": "20210125",
  "kind": "discovery#restDescription",
  "basePath": "",
  "title": "G Suite Vault API",
  "documentationLink": "https://developers.google.com/vault",
  "baseUrl": "https://vault.googleapis.com/"
}
