{
  "description": "Retrieves your YouTube Analytics data.",
  "title": "YouTube Analytics API",
  "protocol": "rest",
  "fullyEncodeReservedExpansion": true,
  "discoveryVersion": "v1",
  "mtlsRootUrl": "https://youtubeanalytics.mtls.googleapis.com/",
  "resources": {
    "groups": {
      "methods": {
        "list": {
          "id": "youtubeAnalytics.groups.list",
          "description": "Returns a collection of groups that match the API request parameters. For example, you can retrieve all groups that the authenticated user owns, or you can retrieve one or more groups by their unique IDs.",
          "httpMethod": "GET",
          "flatPath": "v2/groups",
          "path": "v2/groups",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ]
        },
        "delete": {
          "httpMethod": "DELETE",
          "flatPath": "v2/groups",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "description": "Deletes a group.",
          "path": "v2/groups",
          "id": "youtubeAnalytics.groups.delete"
        },
        "update": {
          "path": "v2/groups",
          "id": "youtubeAnalytics.groups.update",
          "description": "Modifies a group. For example, you could change a group's title.",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "flatPath": "v2/groups",
          "httpMethod": "PUT"
        },
        "insert": {
          "flatPath": "v2/groups",
          "path": "v2/groups",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "description": "Creates a group.",
          "httpMethod": "POST",
          "id": "youtubeAnalytics.groups.insert"
        }
      }
    },
    "reports": {
      "methods": {
        "query": {
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "httpMethod": "GET",
          "id": "youtubeAnalytics.reports.query",
          "description": "Retrieve your YouTube Analytics reports.",
          "path": "v2/reports",
          "flatPath": "v2/reports"
        }
      }
    },
    "groupItems": {
      "methods": {
        "insert": {
          "path": "v2/groupItems",
          "description": "Creates a group item.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "flatPath": "v2/groupItems",
          "id": "youtubeAnalytics.groupItems.insert"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "id": "youtubeAnalytics.groupItems.delete",
          "flatPath": "v2/groupItems",
          "path": "v2/groupItems",
          "description": "Removes an item from a group.",
          "httpMethod": "DELETE"
        },
        "list": {
          "flatPath": "v2/groupItems",
          "httpMethod": "GET",
          "description": "Returns a collection of group items that match the API request parameters.",
          "id": "youtubeAnalytics.groupItems.list",
          "path": "v2/groupItems",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ]
        }
      }
    }
  },
  "name": "youtubeAnalytics",
  "kind": "discovery#restDescription",
  "batchPath": "batch",
  "version": "v2",
  "id": "youtubeAnalytics:v2",
  "servicePath": "",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/youtubepartner": {
          "description": "View and manage your assets and associated content on YouTube"
        },
        "https://www.googleapis.com/auth/yt-analytics.readonly": {
          "description": "View YouTube Analytics reports for your YouTube content"
        },
        "https://www.googleapis.com/auth/yt-analytics-monetary.readonly": {
          "description": "View monetary and non-monetary YouTube Analytics reports for your YouTube content"
        },
        "https://www.googleapis.com/auth/youtube.readonly": {
          "description": "View your YouTube account"
        },
        "https://www.googleapis.com/auth/youtube": {
          "description": "Manage your YouTube account"
        }
      }
    }
  },
  "rootUrl": "https://youtubeanalytics.googleapis.com/",
  "documentationLink": "https://developers.google.com/youtube/analytics",
  "ownerDomain": "google.com",
  "canonicalName": "YouTube Analytics",
  "baseUrl": "https://youtubeanalytics.googleapis.com/",
  "revision": "20200801",
  "version_module": true,
  "basePath": "",
  "ownerName": "Google"
}
