# https://github.com/googleapis/repo-automation-bots/tree/main/packages/auto-approve

rules:

# incoming PRs from yoshi-code-bot
- author: "yoshi-code-bot"

# Title for PRs from yoshi-code-bot MUST start with `chore: Update discovery artifacts`.
# Title must be regex.
  title: "^chore: Update discovery artifacts"

# The only changed file paths in an incoming PR MUST be exactly
# `"^docs/dyn/index.md$"` or follow either one of these patterns `"docs/dyn/*.html"`
# or `"googleapiclient/discovery_cache/documents/*.json"` . These are
# listed in regex. If this property is omitted, auto-approve bot will allow PRs
# that match the author and title to merge, without checking the file paths.
  changedFiles:
  - "^docs/dyn/index.md$"
  - "^docs/dyn/.*\\.html$"
  - "^googleapiclient/discovery_cache/documents/.*\\.json$"
